### ISSUE TITLE
Add support for Object.defineProperty()

### ISSUE THREAD

**Issue by joshtynjala** [craftyjs/Crafty#10]
IE9 supports Object.defineProperty(), but not __defineGetter__ and __defineSetter__. Support for Object.defineProperty() should be added so that IE9 doesn't need to fall back to the enterframe event.

IE8 also supports Object.defineProperty(), but only specifically for DOM Objects, unfortunately. A try/catch around the call can provide a way to make it into the fallback case when running in IE8.

**Comment by louisstow** [comment]
Does IE9 not require a DOM element?

**Comment by joshtynjala** [comment]
IE9 allows Object.defineProperty() on any Object. That's a limitation only in IE8.

**Comment by louisstow** [comment]
Fixed
