### ISSUE TITLE
"visible" property only works for Canvas objects

### ISSUE THREAD

**Issue by rcfox** [craftyjs/Crafty#100]
Setting the visible property seems to only work for Canvas objects. DOM objects can do foo.DOM().css("display","none"); but it would be nice to have this be unified.

**Comment by louisstow** [comment]
I think this has been fixed in the latest release which I should really
release tomorrow. I have lots of marking to do so fingers crossed. Would
also like to test it a bit more too.

**Comment by rcfox** [comment]
Ah, I guess I should be using headrev then.
