### ISSUE TITLE
Sprite width not accurate

### ISSUE THREAD

**Issue by proyb6** [craftyjs/Crafty#1002]
The image contain 17x16px in black and another 17x16px in red, without any gap in between, when rendering block1 at 77.256 or 5.399999999, it appear an extra px which expose the red block which is glaring to look at in situation e.g pause animation, simulator, etc.

```
Crafty.sprite(1, "img/blackredblock.png", {block1 : [0, 0, 17, 16]});
Crafty.e("Canvas, block1").attr({x: 5.39999999999, y:e.y});
```

I think Sprite need some improvement and a "gap" which existing Sprite has, does not apply to my use case.

**Comment by matthijsgroen** [comment]
I noticed as well, that's why I always have 1 transparent pixel between each element in the spritesheet. paddingX and paddingY is your friend :-)

**Comment by proyb6** [comment]
Nope, "gap" which existing Sprite has, does not apply to my use case.

**Comment by 200sc** [comment]
Proyb6, the padding is exactly the problem here. You can't reliably display separate images on a sprite sheet if there isn't any gap between the two sprites in said image. You yourself said there are no pixels between the two blocks in the image.

**Comment by starwed** [comment]
Closing, since AFAIK this is an inherent limitation of sprite-sheets and canvas.

(I think that the clamping involved with WebGL might prevent the issue there, though?)
