### ISSUE TITLE
Need improvement on Tween smooth animation?

### ISSUE THREAD

**Issue by proyb6** [craftyjs/Crafty#1004]
The animations are quite jerky even on Electron running with 60fps and has tweaks to enabled hardware accelerated, how can it be improve? Phaser example is quite acceptable with only slightly jerky.

Jerky animation when movement from left to right on an viewport with 100px x 700px.

```
Crafty.sprite(1, "assets/img/s.png",{star : [ 0, 0, 15, 43 ]});

Crafty.e("DOM, star, Tween").attr({x:300,y:300}).tween({x:1800}, 6000)
or
Crafty.e("Canvas, star, Tween").attr({x:300,y:300}).tween({x:1800}, 6000)
```

**Comment by 200sc** [comment]
Is [this](http://imgur.com/DlFjXmy) what you mean by jerky? That's what I get when I run this code locally.

Have you tried any of the easing methods?

**Comment by proyb6** [comment]
@Sythe2o0 Right, I use smoothstep and what are other easing method could be use if they are sufficient to tween probably hundreds of images, sprites? As far as it's hard to find on the web.

If some objects are off the screen, does using .visible=false on sprites help to improve performance?

**Comment by 200sc** [comment]
Yes, visibility changes will affect performance but if you are concerned about performance you should be using WebGL. Visibility changes in WebGL will be significantly more impactful performance-wise. I would not try to tween a hundred images in Crafty at the same time. Especially if those elements are collision elements, you will struggle to get good performance.

 I don't really think this is about the described issue any more, however, so I think this can be closed.

**Comment by proyb6** [comment]
Is there any way to flatten multiple sprites if those are static objects? This seem to be missing in Craftyjs that is available in other game engine. WebGL use significant power consumption and I left Phaser and other engines to settle Craftyjs to fix crazy fps.

**Comment by 200sc** [comment]
You can either have good performance or low power consumption, realistically. No, Crafty doesn't have a utility to compress multiple entities into a single entity, as far as I am aware.

**Comment by proyb6** [comment]
Alright, thanks.
