### ISSUE TITLE
Mouselook snap behaviour

### ISSUE THREAD

**Issue by naasking** [craftyjs/Crafty#1009]
If an element is off-screen and mouselook is enabled, then the first click or mousedown+move triggers a jarring 'snap' centering behaviour:

https://jsfiddle.net/zh4gtmk6/1/

I definitely expect the viewport to follow the mouse at all times, and not center the whole viewport for me first based on all included objects. Is this the intended behaviour?

**Comment by 200sc** [comment]
I think it is intended, yes. Have you tried turning [clampToEntities](http://craftyjs.com/api/Crafty-viewport.html#Crafty-viewport-clampToEntities) [off](https://jsfiddle.net/zh4gtmk6/2/)?

**Comment by Sythe2o0** [comment]
Can you mark this issue as closed before coming back here with more issues? Maybe pick someone out to ask some questions about how to work with Crafty before bringing your concerns to be issues?

**Comment by naasking** [comment]
That works. I totally missed that, so my bad!
