### ISSUE TITLE
mouseWheelDispatch doesn't work in IE 11

### ISSUE THREAD

**Issue by naasking** [craftyjs/Crafty#1014]
https://jsfiddle.net/qy0xvLLt/2/

Zooming using the wheel mouse works fine in Firefox and Chrome, but not IE11. I don't see any errors in the console, so I'm not sure what's going on there. The docs list the non-standard mousewheel event is used, but the standard/cross-browser event is 'wheel'. I've read seen reports elsewhere that  this specific event fixes IE11 wheel scrolling issues.

**Comment by mucaho** [comment]
Let's add additional mouse wheel event fallbacks, see https://developer.mozilla.org/en-US/docs/Web/Events/wheel#Listening_to_this_event_across_browser
