### ISSUE TITLE
Request: Change sprite by its name in Sprite.sprite

### ISSUE THREAD

**Issue by dekdevy** [craftyjs/Crafty#1015]
Im not sure, maybe I am missing something but there seems to be no proper way to change an entities sprite / tile of a sprite (not sure, the naming isnt quite clear).  
Lets say we have a sprite(map):  

`Crafty.sprite(50, "imgs/mysprites.png", {dog:[0,0], cat:[0,1,3,1]});`  

So now we have `dog` and `cat` .  
Now I have an entity, animal. I initiate it as a cat.  

`var animal  = Crafty.e("2D, DOM, cat");`  

How would I change the sprite to be a dog?  
The only approach seems to be to remove the `cat` component.. and add a `dog` component? Thats not a proper approach I am sure. How would I do this?

**Comment by mucaho** [comment]
See [`Sprite.sprite`](http://craftyjs.com/api/Sprite.html#-sprite).
The following _should_ work:

``` js
Crafty.sprite(50, "imgs/mysprites.png", {dog:[0,0], cat:[0,1,3,1]});
var cat = Crafty.e("2D, DOM, cat");
var dog = cat.sprite(0, 0, 1, 1);
```

**Comment by dekdevy** [comment]
Hmm, so that means that I cant reuse the values that I entered during my initiation in the spritesheet?  
I dont know about the sprite coordinates in my actual code, I import it from a JSON object that i created with texturepacker and import via the `Crafty.load` function. So I really need to be able to change the sprite using the names that I set up in my JSON object. Later, I simply want to be able to re-use the sprites that i created through crafty.load:

```
var planet = Crafty.e("2D, DOM, Sprite");  

planet.sprite('mars');  

planet.sprite('venus);  
```

**Comment by 200sc** [comment]
The way I've always done that is with animation reels. Reels can have string names and are usually created in a component's init. This is a lot more useful in the long term, as in most games, most images are either animating regularly or never change their sprite. If you give a reel a single element, the animate call will act like that sprite call.

**Comment by mucaho** [comment]
@Sythe2o0 
That sounds good. Could you provide us with an example, please (maybe use the `dog` and `cat` from @dekdevy's code )?

**Comment by 200sc** [comment]
```
var cat = Crafty.e("2D, Dom, cat, SpriteAnimation");
cat.reel("dog", 100, [[0,0]]);
cat.animate("dog",-1)
```

Note I've only done this with sprites which are the same size and dog and cat don't look like they are the same size.

**Comment by mucaho** [comment]
@Sythe2o0 thanks for the example!
In lieu of that alternative working with different tile sizes, I'm definitely for the inclusion of such a feature to change the tile by supplying a string parameter (e.g. as `player.sprite('dog')`).

@dekdevy: Perhaps you could hang on to that JSON object and read the tile dimensions from it, until this gets updated?

**Comment by dekdevy** [comment]
thanks! sounds good. cant wait for this feature :)

edit: @mucaho yep thats what I am doing for now. I wrote my own little function that writes the info into the entities sprite component from my json object whenever i want to change it. that way i can change it with one function call and all i need is the name :)

**Comment by starwed** [comment]
> The only approach seems to be to remove the cat component.. and add a dog component? Thats not a proper approach I am sure. How would I do this?

I'd say that actually is the "correct" way in a component based system.  :)  That said, there could be a helper function on sprite that makes it simpler to change the current sprite, and helps avoid any unnecessary performance hit.

**Comment by dekdevy** [comment]
@starwed I actually dont think its the correct way for a component based system. Components in itself are awesome, but I this is a design inconsistency with other Crafty components.
Components act to provide a function, like the text component - It displays a text. You can talk to the component and tell it to display any different text whenever you want. Thats good and thats how components make sense and are perfectly usable. You wouldnt delete a text component and add a new one, just to show a different text.  
By the current logic, the sprite components themselves become the function, instead of provide it. You have to manually add and keep track of them, and they have no other purpose, cant be modified or reused like the other components. 

But like you said in the end, the whole thing is easily solved with @mucaho 's proposal :)

**Comment by mucaho** [comment]
To be frank, it's a bit non-intuitive when the component `dog` can change its visual appearance to be that of `cat` :) I would maybe prefer to add the whole spritesheet `animal` as only one single component to the component pool, which can be added to an entity and then you could change sprites via coordinates or identifier (but that's out-of-scope of the follow-up PR and could be discussed further in future).

**Comment by dekdevy** [comment]
@mucaho you're right, my example wasnt the best :) Sorry if this caused any trouble.. I see you already have this coming in the master soon and im truly excited! Thanks so much!

**Comment by mucaho** [comment]
No trouble at all, we are discussing :)

---

Now that this functionality was added: If you want to be extra pedantic about current semantics, you can declare the whole spritesheet as a sprite component and change the individual sprite components with `Sprite.sprite`:

``` js
Crafty.sprite(50, "imgs/mysprites.png", {
    animal: [0, 0, 4, 1]
    dog: [0, 0],
    cat: [0, 1, 3, 1]
});
Crafty.e("2D, DOM, animal")
     .sprite('dog');
```
