### ISSUE TITLE
X and Y is not getting applied with top/left on DOM

### ISSUE THREAD

**Issue by Hinton** [craftyjs/Crafty#102]
DOM elements dos not get top or left applied when setting x and y cordinates.
This example worked fine in 0.4.2 but broke when updating to 0.4.3

``` javascript
var text = Crafty.e('2D, DOM, Text')
    .text('Loading!')
        .attr({
            w: Crafty.viewport.width,
            x: 0,
            y: Crafty.viewport.height / 2 - 40
    });
```

**Comment by mpetrovic** [comment]
It looks like _changed is never being set to false, so it never goes through the DrawManager again.

**Comment by mpetrovic** [comment]
Oh wait, maybe not. It looks like the last version switched from using top/left to translate(). And there seems to be something wrong with our css transforms implementation, since I can't get .rotate() to work either.

**Comment by louisstow** [comment]
I changed that because Chrome 12 stopped working with DOM and it was sort of a knee-jerk fix for the time being. The Fruit Assassin demo suddenly stopped on Chrome using 0.4.2 and I have no idea why. Seems to be a browser bug.

**Comment by louisstow** [comment]
This is fixed in the latest commit
