### ISSUE TITLE
Crafty.clone: maximum call stack exceeded

### ISSUE THREAD

**Issue by naasking** [craftyjs/Crafty#1022]
Can't seem to clone entities:

https://jsfiddle.net/x2oszt7b/

**Comment by mucaho** [comment]
~~You are using an invalid selector [`Crafty()`](http://craftyjs.com/api/Crafty.html).~~ **EDIT:** There are actually two `clone` functionalities, I got a bit confused.
You can clone an entity retrieved by the selector `Crafty(x.getId()).clone()` or clone the entity directly `x.clone()` instead.
https://jsfiddle.net/x2oszt7b/2/

Judging from the implementation [`Crafty.clone`](http://craftyjs.com/api/Crafty-clone.html) should be used for 'plain' objects with no cyclic references, the documentation should state that and link to the other [`clone`](http://craftyjs.com/api/Crafty%20Core.html#-clone) method for cloning entities.

**Comment by starwed** [comment]
This is definitely a doc bug, for not making the limitations of clone clear.  In this case, it's trying to do a deep clone, and almost definitely running into a recursive loop where a property of an object refers back to the original object.  (And thus, giving the "maximum call stack exceeded" message.)

In general, [cloning javascript objects](http://stackoverflow.com/questions/728360/most-elegant-way-to-clone-a-javascript-object) is tricky.  We do provide a special-cased one for copying entities, though I'm not sure it really covers every use case.

**Comment by starwed** [comment]
This is definitely a doc bug, for not making the limitations of clone clear.  In this case, it's trying to do a deep clone, and almost definitely running into a recursive loop where a property of an object refers back to the original object.  (And thus, giving the "maximum call stack exceeded" message.)

In general, [cloning javascript objects](http://stackoverflow.com/questions/728360/most-elegant-way-to-clone-a-javascript-object) is tricky.  We do provide a special-cased one for copying entities, though I'm not sure it really covers every use case.

_e:_ We could probably track the recursion level ourselves, and break out of the loop before the browser interferes.  That at least would provide better feedback when something goes wrong.
