### ISSUE TITLE
Audio repeating when passed 'play once' argument

### ISSUE THREAD

**Issue by anthwinter** [craftyjs/Crafty#1027]
The line I am referring to is: https://github.com/craftyjs/Crafty/blob/develop/src/sound/sound.js#L237

The condition checks if "repeat == -1". However, if I have passed the play method a 'repeat' argument that is 1, the c.onEnd function seems to think 'repeat' is -1 when the "ended" event occurs.

Should "repeat == -1" not be "c.repeat == -1" ?

**Comment by mucaho** [comment]
Hmm, can't reproduce the issue. The following works for me (on firefox 44, linux):

``` js
Crafty.audio.add("beep", "beep.wav");
Crafty.audio.play("beep", 1); // plays sound once
```

Which browser(+version) and OS are you using?

If you change `repeat == -1` to `c.repeat == -1`, does that fix the issue for you? The `onEnd` anonymous function expression should inherit the variables of the parent function's scope (it builds a closure), so it shouldn't matter, if I understand correctly.

**Comment by anthwinter** [comment]
Yeah, changing it to c.repeat makes it work. 

I was getting the issue on Chrome 50 with Windows 8.0

It does only seem to happen with playing multiple sounds. Ill try and get more debug info and report back to be 100% sure.

As far as I'm aware it should create a closure over the play method, but I wonder if other sounds that call the play method are somehow changing the argument?... Ill do some more digging.

**Comment by 200sc** [comment]
I'd guess that you're right, and the variable is being redefined inside the function's scope on new play calls, which the single-play call sees as it's new repeat variable. I think changing it to c.repeat is the way to go.

**Comment by mucaho** [comment]
Alrighty, see also a4f5bb9b3b117f1f8f4df39273c852f6c98825a4 for reference.
If this small change fixes the issue, let's go ahead and add it.
Additionally, if applicable, we should add a testcase to `tests/audio.js` for that.
