### ISSUE TITLE
At 0.4.3, when you issue rotate method to a 2D object, it throws an error

### ISSUE THREAD

**Issue by Mithrandir0x** [craftyjs/Crafty#103]
When rotate method is called from a 2D object, it throws an error. I've made a jsFiddle pinky example: http://jsfiddle.net/Mithrandir0x/36vub/5/

At 2D.js (line 547) the 'e' parameter just gives the angle to rotate. Am I using wrong the function? Should I call rotate this way?

``` javascript
var ent = Crafty.e('2D, DOM, Mouse');
ent.attr({ x: 0, y: 0, w: 32, h: 32 });
ent.rotate({ o: { x: 0, y: 0 }, theta: 45 });
```

**Comment by mpetrovic** [comment]
Using .rotate requires the syntax you mentioned. Using attr('rotate', x) will just take a value and use the last origin to rotate around.

I think ideally the interface should be the same regardless which method you use. And that interface should probably more like this:
    entity.rotate(angle, origin{x, y})
with the origin being optional, defaulting to the last origin used.

**Comment by louisstow** [comment]
You should be doing `this.rotation += 45` or something like that.

**Comment by louisstow** [comment]
Closing this because the syntax is incorrect and rotation should be set through the property `rotation`
