### ISSUE TITLE
Hex colors with only 3 chars (E.G: #fff) don't work.

### ISSUE THREAD

**Issue by ChildishGiant** [craftyjs/Crafty#1030]

**Comment by matthijsgroen** [comment]
That's because it's not CSS. A pull request could be made. Maybe I can do so later this week

**Comment by matthijsgroen** [comment]
There is currently an implementation for it, but is specs are faulty.

The test is that if color `#123` is assigned, the resulting RGB (ranged 255) should be:

```
r = 1
g = 2
b = 3
```

But this should actually be:

```
r = 17
g = 34
b = 51
```

I will update this spec and implementation in a pull request shortly

**Comment by mucaho** [comment]
> There is currently an implementation for it, but is specs are faulty.

Yep, for reference, the [standard css3 color specification](https://www.w3.org/TR/css3-color/#rgb-color) says:

> The three-digit RGB notation (#rgb) is converted into six-digit form (#rrggbb) by replicating digits, not by adding zeros. For example, #fb0 expands to #ffbb00.
