### ISSUE TITLE
Error when attempting to give an entity an image.

### ISSUE THREAD

**Issue by ChildishGiant** [craftyjs/Crafty#1031]
Here's my code:

```
window.onload = function() {
  var $h = $(window).height();
  var $w = $(window).width();

  var $nw = ($h-$h/10) / 3 * 4
  var $nh = $nw / 4 * 3

  Crafty.init($nw,$nh, document.getElementById('game'));

  Crafty.e('Floor, 2D, Canvas, Color')
    .attr({x: 0, y: 250, w: 250, h: 10})
    .color('green');

  var queen = Crafty.e('2D, Canvas, Image, Fourway')
    .attr({x: 0, y: 0, w: 50, h: 50})
    .image("assets/queen.png", "no-repeat")
    .fourway(200)
};
```

Here's the error: `'CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated. Please use 'CanvasRenderingContext2D.imageSmoothingEnabled' instead.`

**Comment by 200sc** [comment]
This shouldn't cause any functional problem. It's done for older browser compatibility, I believe.

**Comment by mucaho** [comment]
Does your game crash after this error occurs, or is it more like a warning and your game runs fine? As Sythe2o0 said, it's because of browser compatibility.

**Comment by ChildishGiant** [comment]
It runs fine but I can't give an entity an image.

**Comment by mucaho** [comment]
Hmm, I can't reproduce the issue on firefox 44 nor chromium 49 (linux) - the image gets displayed correctly (despite the same warning I receive in chromium).
Could you please run https://jsfiddle.net/s52bkc2x/ and see if that works for you? You should be able see a small kitten on screen.
However, I had trouble with `$nw` and `$nh` in firefox, these values were extremely small (< 10 px) for me.

**Comment by ChildishGiant** [comment]
I see the kitten so it's probably on my end. $nw and $nh for me are fine (E.G:1528,1146)

**Comment by mucaho** [comment]
Maybe `"assets/queen.png"` fails to load? Try preloading them with [`Crafty.load`](http://craftyjs.com/api/Crafty-load.html).
