### ISSUE TITLE
dynamicTextGeneration is not a function

### ISSUE THREAD

**Issue by Mertovski** [craftyjs/Crafty#1063]
Hi, when I try to use the following code
```
Crafty.e("2D, DOM, Text, Motion").attr({ x: 100, y: 100, vx: 10 })
 .text(function () { return "My position is " + this._x })
 .dynamicTextGeneration(true);

```
I get a Uncaught TypeError: dynamicTextGeneration is not a function(..)

**Comment by starwed** [comment]
Just to check, what version of Crafty are you using?  `dynamicTextGeneration` is present in the develop branch, but not yet a full release.  (You can double check using [getVersion](http://craftyjs.com/api/Crafty-getVersion.html)).

**Comment by Mertovski** [comment]
That's probably the issue. Currently I'm using 0.7.1 which I had downloaded from craftyjs.com. I looked up how to install the dev branch and will work from there. Thanks!

**Comment by starwed** [comment]
Sounds like you got it sorted out, and this was just a case of using a develop feature against the release version, so closing.   (But if there are places where the docs were confusing, feel free to reopen as a doc issue.)
