### ISSUE TITLE
Click event not triggered when use crafty with angular 2

### ISSUE THREAD

**Issue by ihabZhaika** [craftyjs/Crafty#1068]
HI,
I have angular 2 app , i embed the library with it, the problem i face is mouse  events is not captured , i tried t the keyboard event and it work
to reproduce the problem , open angular 2 app , and try to use the library
```
    Crafty.init(600, 300);
    Crafty.background('rgb(127,127,127)');
    var myEntity = Crafty.e('2D, Canvas, Color, Mouse')
                         .attr({x: 10, y: 10, w: 40, h: 40})
                         .color('red')
                         .bind('Click', function(MouseEvent){
                           alert('clicked', MouseEvent);
                         });

```
    myEntity.bind('MouseUp', function(e) {
      if( e.mouseButton == Crafty.mouseButtons.RIGHT )
        Crafty.log("Clicked right button");
    });

    var a = Crafty.e("2D, DOM, Color")
          .attr({x: 100, y: 100, w: 50, h: 50})
          .color("red").bind("Click",function (e)
    {
      console.log("S");
    });
    a.bind('MouseUp', function(e) {
      if( e.mouseButton == Crafty.mouseButtons.RIGHT )
        Crafty.log("Clicked right button");
    });
          a.bind('KeyDown', function(e) {
            if(e.key == Crafty.keys.LEFT_ARROW) {
              this.x = this.x-10;
            } else if (e.key == Crafty.keys.RIGHT_ARROW) {
              this.x = this.x+10;
            } else if (e.key == Crafty.keys.UP_ARROW) {
              this.y = this.y-10;
            } else if (e.key == Crafty.keys.DOWN_ARROW) {
              this.y = this.y+10;
            }
          });

**Comment by ihabZhaika** [comment]
Update :
when i resize the browser the event work , so i tired this code :
```
var player = Crafty.e("2D");
    player.onMouseDown = function(e) {
        Crafty.log(e.mouseButton, e.realX, e.realY);
    };
Crafty.addEvent(player, Crafty.stage.elem, "mousedown", player.onMouseDown);
```
what i noticed that the e.realY is negative and not in the canvas bounds , when i resize the browser , it gives correct values
so what it could be ?

**Comment by starwed** [comment]
I suspect you're doing something with angular that changes the location of the stage after crafty inits.  Once the page is completely setup (by both angular+crafty), try calling [crafty.viewport.reload](http://craftyjs.com/api/Crafty-stage.html#Crafty-viewport-reload).  

We do this automatically when the browser window size changes, which is why that's fixing things.  Last time I checked doing this automatically when the DOM itself changes had a perf impact, so we rely on the user of Crafty knowing when to call it!

**Comment by ihabZhaika** [comment]
it works , thx

**Comment by starwed** [comment]
Glad that helps.  (There is some more context in #452 if anyone is curious.)
