### ISSUE TITLE
Use exists canvas

### ISSUE THREAD

**Issue by ghost** [craftyjs/Crafty#1069]
Crafty.init(0,0,"rrr");

This code is create again canvas in canvas. Can i use exists canvas ?

**Comment by starwed** [comment]
Crafty supports supplying [an existing element for the stage](http://craftyjs.com/api/Crafty-init.html), but not for the canvas/dom/webgl layers.  Is there a reason you need to use the specific canvas element created by react?

(You could theoretically manually swap out the canvas used by a particular layer, but I'd guess that things like click detection and viewport manipulation would break.)

**Comment by starwed** [comment]
I don't think this would be that useful of a feature, but anyone with a specific reason why they need it should feel free to reopen.
