### ISSUE TITLE
prevent keyboard event propagation to the browser

### ISSUE THREAD

**Issue by ihabZhaika** [craftyjs/Crafty#1081]
Hi,
i am following this example
http://craftyjs.com/api/KeyboardEvent.html

but i had one issue , that when the browser have scroll bar , lets say vertical , when i click on the up or on the down arrows , the browser scroll bar moves , is there is a way to stop the "KeyDown" event from propagating to the browser ?

**Comment by starwed** [comment]
The [existing implementation](https://github.com/craftyjs/Crafty/blob/5c34e4039278e39defc230858d1e83c078935f50/src/controls/inputs.js#L572-L588) does *attempt* to prevent this very issue, so there's likely a bug with it.

I wonder if `Crafty.selected` is being incorrectly set to false on startup -- perhaps try setting it to true in your initial setup?

**Comment by ihabZhaika** [comment]
hi,
i tried , still get the same result ,
i noticed that when i click any other key with the arrows , the slider do not move any more
any suggestions ?

**Comment by starwed** [comment]
Hmm, sounds like there's a bug somewhere.  I'll see if I can reproduce locally.

In the mean time, if you don't actually want scrollbars, and they're appearing when making the game fullscreen, you should be able to use css to prevent that, e.g.:

```
  <style type='text/css'> body{margin:0;} </style>
```

**Comment by starwed** [comment]
Ok, so I can reproduce the issue locally, but setting `Crafty.selected = true` after init fixes things:

```
Crafty.init();
Crafty.selected = true;
Crafty.stage.fullscreen = true;
```

Actually clicking on the document (and thus triggering the logic that sets Crafty.selected to be true) also works.

**Comment by ihabZhaika** [comment]
mm , tried , not working for me , the sides still moving
if you found a solution for the bug update me , and i try to find a way

**Comment by ihabZhaika** [comment]
hi,
changed the location of the method calls to every where , but still no hope

**Comment by ihabZhaika** [comment]
Other problem that i faced , when
 Crafty.selected = true;
i get extra white space which i dont need , and when i click on any way that is no the canvas and move the arrows , the object in the game moves too
so is it related the the main problem ?

**Comment by starwed** [comment]
> I get extra white space which i dont need , and when i click on any way that is no the canvas and move the arrows , the object in the game moves too
so is it related the the main problem 

Crafty doesn't suppress any of the normal html behavior.  If you have more content than will fit in the browser window, it will overflow, causing the scrolling behavior.

There are a couple of possible resolutions, depending on what's going on:
- If you're trying to have Crafty fill the page, but there are just a few pixels of whitespace surrounding your game, try setting the body margin to 0 in a stylesheet.  (Or just include this snippet in the page's header: `<style type='text/css'> body{ margin:0; }  </style>`
- If you have actual content outside of Crafty, you need to use your browser dev tools to see what's triggering the overflow behavior.  You can probably suppress it by setting the [overflow](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow) property on the right element.

**Comment by ihabZhaika** [comment]
Hi,
1 - was not able to solve the problem what the suggested solution , the white space appear when the browser width is wider than the canvas  , this happens with < Crafty.stage.fullscreen = true; >
2 - even with
```
Crafty.selected = true;
Crafty.stage.fullscreen = true;
```
when moving the arrows , the scroll bar still moving with it
when the page loaded , the arrows don't move the scroll bars , but when click on the page and back to the canvas this phenomenon happens

**Comment by starwed** [comment]
>was not able to solve the problem what the suggested solution , the white space appear when the browser width is wider than the canvas , this happens with `Crafty.stage.fullscreen = true;`

This sounds like an issue with the layout of the page as a whole.  Can you give a link to an example?

**Comment by ihabZhaika** [comment]
hi,
its little bit hard to do so because it load the data from local DB , if you want i can arrange team viewer access

**Comment by starwed** [comment]
>its little bit hard to do so because it load the data from local DB , if you want i can arrange team viewer access

It might be good to use Firefox/Chrome devtools to see if you can track down where the whitespace is coming from.  For instance, you can use Firefox's page inspector to figure this out.  If you haven't had to do this before, there are some [tutorials](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_the_box_model) on MDN.  Most likely some elements surrounding the Crafty canvas have extra padding and/or margins.

**Comment by ihabZhaika** [comment]
hi,
its from the canvas object ,
any way the full screen did not help to solve the main problem , so i wont use it ,
i dont think that i will find a solution for the main  problem so i will close it
