### ISSUE TITLE
How to use two different sprite animations on a single entity?

### ISSUE THREAD

**Issue by 9itish** [craftyjs/Crafty#1082]
I am trying to add two different animations to an entity. The first animation loops continuously while the second only plays on mouse click. The problem is that once I play the second animation, the entity stands still. It does not go back to playing the first animation. I tried the following code to make the entity play both animation but it seems like the code keeps adding extra data to the memory. How can I prevent that? 

```javascript
player.bind('Click', function(evt) {
    player.animate("first_anim", 1)
    .bind('AnimationEnd', function() {
      console.log(this.getReel());
      player.animate("second_anim", -1);
    });
});
```

The console outputs an extra reel object each time  a click happens like this:

```
Object {id: "first_anim",...
//Second Click
Object {id: "first_anim",...
Object {id: "second_anim",...
//Third Click
Object {id: "first_anim",...
Object {id: "second_anim",...
Object {id: "second_anim",...
and so on.
```

Is there some other more proper way of doing this?

Thanks.

**Comment by 200sc** [comment]
A fiddle would help to resolve the animation issue, but it looks like your extra memory is coming from you calling .bind() on every click event.

If you want the animation switch to only happen once, use the .one() call to create a binding which will immediately unbind after it is first triggered. That might also solve your animation issue depending on what your animations are.

**Comment by 9itish** [comment]
Thanks @Sythe2o0, that did solve the issue. I had to use `.one('AnimationEnd', function()` instead of `.bind('AnimationEnd', function()`. (I guess that's what you meant). I still have one doubt.

How does this `.one()` method actually work? 

I thought what I am doing here is checking if the entity has been clicked and play "first_anim" if it has been clicked. That "first_anim" is bound to "AnimationEnd" event so that I can start the second animation once the first one ends. If this "second_animation" is being added to the memory multiple times, then I guess the "first_animation" should have been added multiple times too because both the click event and the AnimationEnd event are using the same `.bind()` method.

**Comment by 200sc** [comment]
So you aren't binding on the animation itself, you're binding on the player. That means each time Click comes through player gets another AnimationEnd binding. 

The difference is that .bind("Click") only gets called once. .one() is effectively binding and immediately unbinding once the callback has been triggered once (hence the name one). Otherwise, once "second_animation" ends it will trigger the animate function again.

**Comment by 9itish** [comment]
Thanks @Sythe2o0. That was a silly misunderstanding on my part. I missed the fact that I am binding the AnimationEnd event inside the Click event. Moving the AnimationEnd event outside of the click event solved the issue too. 👍

**Comment by starwed** [comment]
Glad you figured out what was up!   Closing this issue as resolved.
