### ISSUE TITLE
Unable to play a sound multiple times more than once.

### ISSUE THREAD

**Issue by 9itish** [craftyjs/Crafty#1083]
This is the code I am using:

```javascript
box.bind('Click', function() {
  Crafty.audio.play("beep", 3);
});
```

According to this code, the beep sound should be played three times on each click on the box. However, the beep sound plays three times only on the first click. On second and subsequent clicks, the beep sound plays only once. Why is that?

Thanks.

**Comment by starwed** [comment]
Which version of Crafty are you using?

**Comment by 9itish** [comment]
I am using version 0.7.1. :)

**Comment by starwed** [comment]
There was a similar error that is fixed in 0.8.  You might want to try
upgrading to the release candidate, and see if that fixes things!

**Comment by 9itish** [comment]
Thanks @starwed. Is there a webpage where Crafty keeps track of bugs found in different versions?

**Comment by starwed** [comment]
With a new release, we typically put any fixed bugs in the [release notes](https://github.com/craftyjs/Crafty/wiki/Release-Notes),  and open bugs will be present here on github.  But there's currently no place that calls out known fixed bugs with the current version.
