### ISSUE TITLE
Keyboard event doesn't work as intended

### ISSUE THREAD

**Issue by djsell** [craftyjs/Crafty#109]
Normalization of the keyboard events (and probably other events) doesn't work on Firefox 5.0 on Ubuntu (and likely other platforms / browsers).

It appears that the event object is actually read only in some browsers, so e.key doesn't get set.  Looking at the jQuery code, they seem to get around it by making a clone of the original event and using that as a proxy.

**Comment by sorenbs** [comment]
Would you mind writing a small example that demonstrates the problem and point to the exact place in the jquery code.

**Comment by sorenbs** [comment]
Hmm. I added the following logging in the KeyboardDispatch function and tested it on FF6/win FF4/ubuntu FF6/ubuntu and was not able to reproduce the behavior

keyboardDispatch: function(e) {
        e.key = e.keyCode || e.which;
        console.log(e.key + " - " + e.keyCode || e.which);

Am i misunderstanding something?

**Comment by djsell** [comment]
Sorry I didn't get back to you before, I just saw this message.  I seem unable to reproduce it now, too.  Weird.  Maybe I was doing something wrong at the time?  Anywho, here is the reference in jQuery

https://github.com/jquery/jquery/blob/master/src/event.js#L457

**Comment by sorenbs** [comment]
That's interesting. I will leave it there for now, but if this issue comes up again we know where to look.
