### ISSUE TITLE
Incorrect version

### ISSUE THREAD

**Issue by Boggartmob** [craftyjs/Crafty#1095]
As I can see on http://craftyjs.com current version is 0.8.0. However version.js file contains "0.7.0" string. Also NPM shows 0.7.1.

Please fix this.

**Comment by starwed** [comment]
Ah, the [release](https://github.com/craftyjs/Crafty/blob/release/package.json) branch has the correct version, but I guess we didn't backmerge that into develop.  I'll fix that.  *e:* That part is fixed.

Right now only @kevinsimper and @mucaho can publish to the [npm repo](https://www.npmjs.com/package/craftyjs), so tagging them about that.

**Comment by mucaho** [comment]
Published 0.8 to npm. Let me know if there are any issues. If kevin could add starwed to the npm repo that would be rad.   
edit: Actually I can add you too, starwed. Can you [create an account](https://www.npmjs.com/signup) and tell me your username?

**Comment by starwed** [comment]
@mucaho Thanks for publishing 0.8!  

Just created an account: [starwed](https://www.npmjs.com/~starwed).

**Comment by mucaho** [comment]
Done. Use "npm login" followed by "npm publish" from the root Crafty
directory once you have run "grunt release".
