### ISSUE TITLE
Event Binding for Isometric Tiles

### ISSUE THREAD

**Issue by MakerPlays** [craftyjs/Crafty#110]
The mouse events that are applied to the tiles in the isometric demo (http://craftyjs.com/demos/isometric/) seem to fail with version 0.4.3. I setup a local version and updated the code from "Crafty.isometric.init(128)" to "Crafty.isometric.size(128)", but the events don't seem to be catching. Thoughts?

**Comment by louisstow** [comment]
What browser are you using? Seems to work for me in Chrome 13.

**Comment by MakerPlays** [comment]
Using Chrome 13. None of the mouse events are firing, including: mouseout, mouseover and click. 

```
Example

http://jsfiddle.net/BSdjJ/2/
```

**Comment by louisstow** [comment]
All events in 0.4.3 are PascalCase: Click, MouseDown, MouseUp, etc, etc.

http://jsfiddle.net/BSdjJ/3/

**Comment by MakerPlays** [comment]
Ahh, thank-you.

Maybe setup some enums?

**Comment by MakerPlays** [comment]
So the "bind" function uses Pascal Case, but "addEvent" does not?

This following section does not use Pascal Case, but does work: (http://jsfiddle.net/BSdjJ/3/)

```
Crafty.addEvent(this, Crafty.stage.elem, "mousedown", function (e) {
    if (e.button > 1) return;
    var base = { x: e.clientX, y: e.clientY };

    function scroll(e) {
        var dx = base.x - e.clientX,
            dy = base.y - e.clientY;
        base = { x: e.clientX, y: e.clientY };
        Crafty.viewport.x -= dx;
        Crafty.viewport.y -= dy;
    };

    Crafty.addEvent(this, Crafty.stage.elem, "mousemove", scroll);
    Crafty.addEvent(this, Crafty.stage.elem, "mouseup", function () {
        Crafty.removeEvent(this, Crafty.stage.elem, "mousemove", scroll);
    });
});
```

This following section does use Pascal Case, but does not work: (http://jsfiddle.net/BSdjJ/4/)

```
Crafty.addEvent(this, Crafty.stage.elem, "MouseDown", function (e) {
    if (e.button > 1) return;
    var base = { x: e.clientX, y: e.clientY };

    function scroll(e) {
        var dx = base.x - e.clientX,
            dy = base.y - e.clientY;
        base = { x: e.clientX, y: e.clientY };
        Crafty.viewport.x -= dx;
        Crafty.viewport.y -= dy;
    };

    Crafty.addEvent(this, Crafty.stage.elem, "MouseMove", scroll);
    Crafty.addEvent(this, Crafty.stage.elem, "MouseUp", function () {
        Crafty.removeEvent(this, Crafty.stage.elem, "MouseMove", scroll);
    });
});
```

**Comment by louisstow** [comment]
Correct.

addEvent is a way to make DOM events so has to follow browser conventions.

**Comment by MakerPlays** [comment]
Ok, thanks for the help.
