### ISSUE TITLE
Variation in behavior when component 'required' order changed (Mouse component)

### ISSUE THREAD

**Issue by catchouli** [craftyjs/Crafty#1140]
Sorry about the cryptic title, this is kind of a weird issue. I have only just started using this library, so I might be doing something wrong.

My issue is the following:
1. Create a component with the required: set to '2D, Mouse, Canvas, Color'
2. Create an entity with this component
3. Destroy the entity
4. Create another entity with this component
5. It no longer correctly gets mouse events (it did before destroying the original entity)

On the other hand, if I specify the required components as '2D, Canvas, Color, Mouse', it works correctly.

My reproducer:
https://jsfiddle.net/ks8ryt69/1/

If you run this you'll find that the mousemove event will not fire. If you uncomment the commented out line, it will now work.

I couldn't find any notes on this gotcha and it took me quite a while to figure out the problem, so I'm assuming it's a bug.

It's not critical, since there's a simple workaround, but if I'm doing something wrong please let me know.

**Comment by mucaho** [comment]
Thank you for tracking this bug down!  
From my initial debugging the problem seems to be in the implementation of `AreaMap` component. It incorrectly decrements the amount of pointer entities of the current draw layer twice, when the entity is destroyed.

**Comment by starwed** [comment]
>From my initial debugging the problem seems to be in the implementation of AreaMap component. It incorrectly decrements the amount of pointer entities of the current draw layer twice, when the entity is destroyed.

Yup -- looks like it removes it on the "LayerDetached" event, and also when the entity is destroyed.  Since a "LayerDetached" event is also fired on destruction, it will double-decrement.   (Unless the "Renderable" component is removed before the destructor for `AreaMap` runs, which is why it can be order dependent.)

**Comment by starwed** [comment]
@Catchouli This is now fixed in the develop branch.  Thanks for the bug report!

**Comment by catchouli** [comment]
np :) thanks for the library - I've enjoyed using it

if you wanna see what I've done with it (+ node and some other libs) https://dev.talkhaus.com:13000/ test1234:password1234

(e: fixed link)
