### ISSUE TITLE
addComponents supports multiple arguments, requires does not

### ISSUE THREAD

**Issue by matthijsgroen** [craftyjs/Crafty#1149]
`#.addComponent`

https://github.com/craftyjs/Crafty/blob/b73ba75c27a214a3686bd453b2c76e2dc6bab61c/src/core/core.js#L293-L298

`#.requires`

https://github.com/craftyjs/Crafty/blob/b73ba75c27a214a3686bd453b2c76e2dc6bab61c/src/core/core.js#L426-L428

shouldn't it be `this.addComponent.apply(this, arguments)` ?

**Comment by starwed** [comment]
Seems reasonable to me.

**Comment by starwed** [comment]
Fixed in #1150
