### ISSUE TITLE
Top and Left attributes not set with 0.4.3

### ISSUE THREAD

**Issue by hex** [craftyjs/Crafty#115]
I am trying to create a simple isometric system using Crafty but it seems that the tiles don't get any top/left attributes for positioning. It works only in Chrome (with translate3d) in any other browser they all get stacked one on top of each other. 

If I am using the dev version of Crafty it works but the pan mode stops working and also when I switch the rendering from DOM to Canvas it stops working. I need to use a stable version of Crafty because I want it to use it in a live project. How can I fix this issue? 

I set up a fiddle right here: http://jsfiddle.net/hexaust/m3HMs/

**Comment by sorenbs** [comment]
The dev version contains a complete rewrite of the drawing stuff.
The main branch is an evolution of the 0.4.3 version and it seems to fix the top/left issue. At least in IE9 and FF4/5/6. 
See this: http://jsfiddle.net/m3HMs/11/
Could you test if this works for you? If so i guess we should release a 0.4.4 or something as 0.4.3 is kinda broken :-)

**Comment by hex** [comment]
It seems that the snapshot fixed most of the problems and it works in Firefox now, and IE 9, in IE8 throws some javascript errors and it won't work. One thing that I noticed it doesn't work anymore is the areamap. Try hovering from tile [1, 3] to [2, 2] and see how the area changed ( compared  http://jsfiddle.net/hexaust/m3HMs/ with http://jsfiddle.net/m3HMs/11/ ).

**Comment by sorenbs** [comment]
I think i got the areamap issue under control. The IE8 issue is fixed also, but there seems to be another issue preventing the MouseOver event from being fired in IE8. Please give it a try and let me know.

**Comment by hex** [comment]
The areamap works now! As you said in IE8 the mouse events aren't working. MouseOver and Click, when I turn the "swap mode: ON" I can't select the buildings by clicking them. Still the panning mode works. Everything alright in IE9.

**Comment by sorenbs** [comment]
I hope this does the trick. Please report any other IE problems you see.

**Comment by hex** [comment]
The mouse events are working in IE8 now, thank you very much!
