### ISSUE TITLE
Components don't receive mouse events when stage doesn't have defined size

### ISSUE THREAD

**Issue by michaelmelanson** [craftyjs/Crafty#1153]
I ran into an issue where I was trying to attach mouse events to a component and the event handlers weren't firing. After stepping through the event handling code, I found the problem was that it wasn't locating the target object because the viewport's width was `NaN`, so when translating the mouse event's location to the local coordinates, it ended up with `x: NaN`.

I reduced the bug down to how the stage gets initialized: it happens if you don't give the stage a defined size. For example:

```javascript
<html>
  <head></head>
  <body>
    <div id="game"></div>
    <script type="text/javascript" src="https://rawgithub.com/craftyjs/Crafty/release/dist/crafty-min.js"></script>
    
    <script>
      const buggy = true;
      
      if (buggy) {
        Crafty.init(document.getElementById('game'));
      } else {
        Crafty.init(500, 350, document.getElementById('game'));
      }

      Crafty.e("2D, DOM, Text, Mouse")
        .text("Click me")
        .bind('Click', function() {
          alert("Clicked!");
        })
        .attr({x: 0, y: 0, w: 100, h: 50});
    </script>
  </body>
</html>
```

https://codepen.io/michaelmelanson/pen/LzpGmb?editors=1000

In this example, the event handler will not get fired if `buggy=true`.

**Comment by starwed** [comment]
>I reduced the bug down to how the stage gets initialized: it happens if you don't give the stage a defined size.

In a strict sense this isn't a bug -- [Crafty.init](http://craftyjs.com/api/Crafty-init.html) does not support passing only the stage element without a width and height, nor do the docs indicate that it does.  I can see how it would be surprising, though.  (Also, you can definitely specify the size without the stage element, and the docs don't technically indicate that this is possible either.  The real signature is `[width, height[, stage_elem]]`)

If we modify the method to allow this, there are two options:
- The stage element gets resized to match the window size
- The stage size gets set to the current size of the stage element

The first is probably most consistent with the existing behavior -- what would you expect?

**Comment by michaelmelanson** [comment]
Interesting. I don't know where I got the idea that this is supported. But in most ways it works. This is the first problem I've run into. 

My mental model here is that it would have the first behaviour: that it would resize the stage to fill its container.

**Comment by starwed** [comment]
Opened a PR that I believe would fix this issue.  Does that look correct to you?

>Interesting. I don't know where I got the idea that this is supported. But in most ways it works. This is the first problem I've run into.

I believe it would have automatically created the default stage element, meaning that only things which checked the stage size dimensions would have been screwed up.
