### ISSUE TITLE
npm craftyjs dependency error

### ISSUE THREAD

**Issue by A-ZC-Lau** [craftyjs/Crafty#1157]
Getting the following error when I try to import it:
```
This dependency was not found:

* fs in ./~/craftyjs/src/graphics/color.js, ./~/craftyjs/src/graphics/image.js and 1 other

To install it, you can run: npm install --save fs
```

Any known work arounds or future fixes?

**Comment by starwed** [comment]
>Getting the following error when I try to import it

Possibly dumb question (I don't really have much experience actually using crafty as an npm module) -- what specifically are you importing?  For concreteness, could you give the exact code that triggers the error?

**Comment by A-ZC-Lau** [comment]
Hmm, well I'm using it in combination with Vue.js, so that might be an issue too. I believe I was just doing a standard `import 'craftyjs'` or `require('craftyjs')`

**Comment by starwed** [comment]
I tried updating [this example](https://github.com/kevinsimper/craftyjs-npm-example) to use crafty `0.8.0`, and it seemed to work correctly.

Maybe following the pattern of that example will help?

**Comment by lau-a** [comment]
I'll try it again in the future.

**Comment by starwed** [comment]
Closing, since I couldn't reproduce.

(But anyone should feel free to reopen if they run into this issue.)

**Comment by falnos24865** [comment]
Pinging this issue as I get this same error in both 0.8.0 and 0.9.0. Looking at the code I see that 

- src/graphics/color.js
- src/graphics/image.js
- src/graphics/sprite.js

 have a `var fs = require('fs')` line in them, which is likely the issue.

**Comment by falnos24865** [comment]
Just to give a bit more context: I ran into this issue when using the `npm` module `craftyjs`. When I downloaded the production version of Craft and used that, it works. So likely an issue with the `npm install craftyjs` setup.
