### ISSUE TITLE
How to tile texture to entity

### ISSUE THREAD

**Issue by w96k** [craftyjs/Crafty#1159]
The question in the title, I need to create moving background and as a workaround, I created an animated background using CSS animation property. Is there any built-in craftyjs method for tiling the whole entity? If yes, show an example. Thank you.

**Comment by matthijsgroen** [comment]
Normally I attach multiple entities together using attach, and create some code that when scrolling the background a system attaches or adds new parts of background as it moves. and cleaning up the parts that are scrolled out of view.

**Comment by w96k** [comment]
Thanks for the answer (:
I think attach() method is what I needed
