### ISSUE TITLE
Setting 2 tweens on the same property causes confusing results

### ISSUE THREAD

**Issue by mpetrovic** [craftyjs/Crafty#116]
To reproduce:
http://jsfiddle.net/7CNgR/2/

This is most likely the result of having 2 enterframe handlers, both of which modify the same property. 

Discussion:
https://groups.google.com/d/topic/craftyjs/hyNVgGVmtg0/discussion

**Comment by mpetrovic** [comment]
Commit:
https://github.com/louisstow/Crafty/commit/396925bebf4674b1ef88d7ef3a68ab56bc6b18fc

**Comment by sorenbs** [comment]
Looks good.
