### ISSUE TITLE
Nightly build breaks my game

### ISSUE THREAD

**Issue by matthijsgroen** [craftyjs/Crafty#1163]
I want to prepare my game to use the latest version of crafty, but a lot of changes since 0.8.0 seem to break my game:

- Crafty crashes when removing a component that was not added (fixed in #1162)
- Scenery build up uses parts that are attached to eachother. somehow the attached part is no longer visible (has something changed here?)
- Normally when the ship touched the edges of the screen, it was merely pushed back. Now, the ship instantly explodes... (has collision detection changed?)
- The ship even explodes during the intro animation

Is there a clear list of changes so that I know if I need to change some things in my game, or that there are bugs in Crafty that were not detected before?

I've recorded a video of the game running in Crafty 0.8.0, and in the Crafty Nightly build.

https://www.youtube.com/watch?v=2HhmVEDtypk

**Comment by starwed** [comment]
There have definitely been some breaking changes; I'll try to put together a full list, but for now I'll link to some PRs that are likely suspects.

There were some changes to how motion works that might be screwing up your game, as well as some implementation changes to collision detection that could be producing bugs.  Here are the PRs:
- https://github.com/craftyjs/Crafty/pull/1146 (removes the "Moved" event and changes to how "Move" is triggered.  In particular, x/y motion will now happen at the same time for objects with Motion.)
- https://github.com/craftyjs/Crafty/pull/1147 (Optimizations to collision methods)
- https://github.com/craftyjs/Crafty/pull/1144 (Split filtered/unfiltered spatial hashmap search into two methods)

**Comment by starwed** [comment]
I compiled a full list of release notes and added them [here](https://github.com/craftyjs/Crafty/wiki/Release-Notes), with a section listing breaking changes.

I'll hold off on creating a testing branch until we figure out if the problems you're seeing are due to breaking changes or bugs.

**Comment by matthijsgroen** [comment]
Wow super! I will try to update and make the game compatible If I find anything that is missing I'll report it here.

**Comment by matthijsgroen** [comment]
One of the issues was that I used the `shift` method with only an `x` provided (assuming the `y` would automatically be `0`) This was not the case, so I needed to add the extra argument for y)

https://github.com/craftyjs/Crafty/blob/df863802ec537568fa2bbf62f74e579b9e4a68a9/src/spatial/2d.js#L660

**Comment by matthijsgroen** [comment]
Thanks to the list the game is almost working again! I will close this issue later and add the stuff I needed to change (that could help others)

**Comment by starwed** [comment]
Cool, I'm going to go ahead and create  an "official" testing branch.

**Comment by matthijsgroen** [comment]
The only thing that is not correctly working is the collision detection. 

![collision-issue](https://user-images.githubusercontent.com/23627/34931757-9ab50254-f9d0-11e7-8e0c-72a9afbe416e.gif)

I marked the 'Solid' areas in red, and the ship should be kept in this area. for collision with the top and the left of the screen this seems correct, but not with the right or bottom of the screen.

Having a collision 'shape' or just use the entire entity as shape makes no difference (I disabled the shape and show the entire entity with 'SolidHitBox' here.

**Comment by matthijsgroen** [comment]
With 0.8 the collision is correct, resulting in this: 

![collision-issue-0 80](https://user-images.githubusercontent.com/23627/34932077-ceccdbe2-f9d1-11e7-851c-9d8b6daf4a35.gif)

**Comment by matthijsgroen** [comment]
@starwed any hints what I should change to fix this? or is this an issue within Crafty?

**Comment by matthijsgroen** [comment]
For me the 'Solid' and 'Edge' Items did not have the 'Collision' component. When that is added, the collision is correct again. Is this the way to go?

**Comment by matthijsgroen** [comment]
Fixed at https://github.com/craftyjs/Crafty/pull/1168

**Comment by starwed** [comment]
Sorry, somehow didn't get any github notifications for these comments!  Luckily I ran into the same collision issue myself, glad it resolved the last (?) of your problems with 0.9 as well.
