### ISSUE TITLE
Travis nightly not always correct

### ISSUE THREAD

**Issue by matthijsgroen** [craftyjs/Crafty#1165]
Some PR's were merged in today (#1164 and #1161 )

This triggered 2 travis builds, but the first build (#1164) was finished last, resulting in a 'nightly' build that misses 1 PR (#1161)

Is there a manual way to retrigger the build process?

**Comment by matthijsgroen** [comment]
https://github.com/craftyjs/Crafty-Distro/commit/c55f4bb7a73b01e7168b3608ef990bce5945fc6b

is the result of the last build

**Comment by starwed** [comment]
Builds can be retriggered from [here](https://travis-ci.org/craftyjs/Crafty/builds).

I went ahead and triggered the build associated with 1161, so I think that should update the distro repo?

*e:* confirmed that the distro repo now contains the correct version.
