### ISSUE TITLE
Crafty selection `.get(0)` is not the same with only one result

### ISSUE THREAD

**Issue by matthijsgroen** [craftyjs/Crafty#1174]
I noticed I cannot do 

```javacript
Crafty("MyComponent").get(0)
```

in a consistent manner. When I have 2 entities in the scene with "MyComponent" this works as expected.

When I have one entity however, the `Crafty("MyComponent")` is directly returning this entity instead of an array with results. So when calling `.get(0)` will result in a call on the entity, that in my case always ends up with `undefined`.

**Comment by matthijsgroen** [comment]
https://github.com/craftyjs/Crafty/blob/f4a79d79c2fe31375e3818ed43d501f100641f5f/src/core/core.js#L117-L119

https://github.com/craftyjs/Crafty/blob/f4a79d79c2fe31375e3818ed43d501f100641f5f/src/core/core.js#L180-L182

**Comment by starwed** [comment]
Most of the methods present on a collection of entities are also present on single entities for this reason.

I suppose `get()` (and maybe some others?) should be as well.

**Comment by matthijsgroen** [comment]
Would it not be simpler to not make a special case for the single result? it makes the API way more clear to use it.

**Comment by matthijsgroen** [comment]
I think I know where the issue is coming from. I have an entity with an own 'get' method on it, that is causing a conflict here.
