### ISSUE TITLE
Support data-uri ?

### ISSUE THREAD

**Issue by chux0519** [craftyjs/Crafty#1188]
It seems that Cratfy does not support data-uri encoded assets. I want to wrap all my assets (data-uri) up in one big single js file, but once using the data uri as assets' url, it doesn't work.

Simply I changed the `isValidImage` method of [loader.js](https://github.com/chux0519/Crafty/blob/develop/src/core/loader.js#L266)

```
return f.startsWith('data:') || Crafty.imageWhitelist.indexOf(getExt(f)) !== -1;
```

It works, but will cause very long key in Crafty.assets.

Any idea / suggestion of this ?

**Comment by OhIAmFine** [comment]
I also meet the questions ,can Crafty have some solution？
