### ISSUE TITLE
Change 'each' function scope to first argument

### ISSUE THREAD

**Issue by matthijsgroen** [craftyjs/Crafty#1206]
https://github.com/craftyjs/Crafty/blob/f3982baa51af24d4e8a14a3194fd3f0e92a2dcba/src/core/core.js#L949

Currently, the `this` scope is set for a passed function. this creates scope juggling.

```
Crafty("2d").each(function() { 
  // work with a magic 'this', and  loosing the outer scope.
});
```

Code I wish I had:

```
Crafty("2d").each(entity => { 
  // no magic 'this', and keeping the outer scope.
});
```

It's essentially changing the code above to: 
```
  func(entities[this[i]], i); 
```

It makes it more in line how `forEach`, `map` etc work in JS.

Problem is, it is API breaking.

Any thoughts?

**Comment by matthijsgroen** [comment]
ps. I could create a `forEach` function for it, so that it does not break the API of the old function. But it would create confusion.

**Comment by starwed** [comment]
I think this is one of the many core Crafty methods that were conceptually borrowed from jQuery -- jQuery's [each](http://api.jquery.com/each/) has the same behavior.

I'll do some more research into our options here.

**Comment by matthijsgroen** [comment]
The function of jQuery does provide the element as second argument to the function, so that you can dodge the 'this' scope changing when using lambda functions.

Personally I would prefer vanillaJS way of working above jQuery 😅

**Comment by matthijsgroen** [comment]
I've fixed it by adding this after loading crafty:

```javascript
Crafty.fn.forEach = function(iterator) {
  this.each(function(index) {
    iterator(this, index);
  });
};
```

So now I can use: 

```javascript
Crafty("Enemy").forEach(enemy => enemy.destroy())
```
