### ISSUE TITLE
Text component for canvas

### ISSUE THREAD

**Issue by jhocking** [craftyjs/Crafty#121]
Currently the Text component only works for DOM elements, so I'm planning to write support for Canvas text. I just want to check if anyone else is already working on this, because I don't want to step on any toes.

**Comment by mpetrovic** [comment]
pretty sure the answer is no. Have at it.

**Comment by kyleshay** [comment]
looks like there is one by starmelt in his tutorial (https://github.com/starmelt/craftyjstut/wiki/Polishing-the-game) at the bottom of the page.

**Comment by ahilles107** [comment]
@jhocking - how about progres for this component?

**Comment by ahilles107** [comment]
please review and test https://github.com/louisstow/Crafty/pull/159/files

**Comment by jhocking** [comment]
Since posting my question I've switched focus to other projects and haven't done more work with Crafty. If/when I get back to this I look forward to trying out your Text code.

**Comment by ahilles107** [comment]
@louisstow you can close this issue
