### ISSUE TITLE
merge draving methods from dev

### ISSUE THREAD

**Issue by sorenbs** [craftyjs/Crafty#123]
merge draving methods from dev into master.

Create simple benchmarks that demonstrates the different performance characteristics for the old and new drawing system.

**Comment by louisstow** [comment]
I think the DOM method is faster but the canvas will be much slower (no more redraw regions). I'm just hoping browsers will step up their game and introduce h/w acc or something.

I also need to make it backwards compatible (i.e make sure ._x/y/w/h is still usable)

**Comment by mpetrovic** [comment]
All the latest browsers support hardware acceleration already. And I'm pretty sure it's on by default.

**Comment by louisstow** [comment]
Sweet! Naive redraw then :D. 

Actually I don't know if I implemented some basic optimization such as off screen elements. It definitely needs more work.

**Comment by sorenbs** [comment]
A bit surprisingly Chrome is the slow one here http://www.tomshardware.com/reviews/web-browser-performance-standard-html5,3013-10.html
But that is probably a non-issue as the entire install base is pretty much updated instantly when they do add hardware acceleration.

**Comment by mpetrovic** [comment]
That's kind of sad, I thought Chrome was better than that. Especially after
all the commercials they made me watch on Hulu about how fast their browser
was :p

**Comment by sorenbs** [comment]
I had a look at the dev branch but as you say it needs some work to get the demos running. Do you think you could merge the new stuff in master into the dev branch Louis? I think that would make it easier to work on fixing what needs fixing.

**Comment by louisstow** [comment]
Sure.

Will just need to make it backwards compatible. Because there are no
getters/setters, there is no need for having _x and x properties. I will
have to make sure _x is always the same as x.

**Comment by sorenbs** [comment]
making _x a getter :-)

**Comment by mpetrovic** [comment]
Looks like this isn't happening. I'm also going back and redoing all of this to support separation of data and presentation, so the its a moot point.
