### ISSUE TITLE
pause game engine when tab not in focus

### ISSUE THREAD

**Issue by sorenbs** [craftyjs/Crafty#124]
The current behavior when the user navigates to another tab is to stop the drawing system, but it appears the game keeps running - at least partly - leading to flickering when the user switches back to the tab. 
Without having looked at the code it looks like the frame count is advanced and the game then tries to play all the missed frames at super speed. Not sure though.

**Comment by louisstow** [comment]
Hmm that sounds like the bug we had (still have) a while back where changing tabs and changing back would cause it to freeze. I think you are right. 

Isn't `requestAnimationFrame` meant to stop that?

Either way, I think this bug is a high priority.

**Comment by sorenbs** [comment]
The loop that runs the game state update is based on time, so essentially we played all the "missed" steps when requestAnimationFrame made the first callback after a pause. Could you check if my fix breaks something or could be optimized somehow?

**Comment by sorenbs** [comment]
Might be better to use the page visibility api http://code.google.com/chrome/whitepapers/pagevisibility.html to move this functionality out of the game loop.

We should also trigger GamePaused and GameResumed events
