### ISSUE TITLE
Does Crafty work on iPhone?

### ISSUE THREAD

**Issue by jhocking** [craftyjs/Crafty#125]
I just tried a bunch of the demos on craftyjs.com (Fruit Assassin, Isometric, Connect Four) plus the game from startmelt's tutorial on my iPhone 3Gs and none of them would load. While those demos didn't load, the Gridshock game did; I believe that was developed using an older version of Crafty.

I'm not in any rush and plan to look at that issue more closely later, but in the meantime do you know why Crafty doesn't work on iPhone?

**Comment by louisstow** [comment]
There was a brief time and version where Mobile was actively being
supported. Unfortunately lots has changed and no work has been done to
optimize mobile and check for bugs. Hopefully in the near future more time
could be spent on it.

**Comment by hex** [comment]
That would be great, lot of game nowadays are optimized for mobile devices, and Crafty surely would need a strong mobile support.

**Comment by mpetrovic** [comment]
i don't have a smartphone to test on, so I've been ignoring it, just coding as efficiently as possible. Is there a reliable emulator out there?

**Comment by jhocking** [comment]
I may take a look at getting Crafty working on my phone, I was just
wondering if the relevant issues were already known.

**Comment by sorenbs** [comment]
Cool. If you identify any subtasks that you don't want to tackle yourself please feel free to open tickets for them.

**Comment by beckheng** [comment]
I have problem on iPad.
I create a simple game with Crafty. It works on Chrome/Firefox/Safari(Widnows Version).
When I try to play on iPad. The display of layout is difference from above browsers.

So I set the User Agent as iPad of the Safari(Widnows Version) and retry the game.
The display of layout is as same as the Safari on iPad.

Thanks for this.

**Comment by mpetrovic** [comment]
Something like this is useless to us.

Where's the simple game? What do you expect? What's wrong with it? How is
it wrong?

When you ask for help, give details.

On Sun, Dec 18, 2011 at 9:03 PM, Beckheng Lam <
reply@reply.github.com

**Comment by beckheng** [comment]
It' a demo game base on Crafty v0.4.4.
You may follow this url:
http://yixinit.com/gamedev/LongTimeNoSee/balloon.htm

The layout is difference between Safari on Windows and Safari on iPad.

PS. The page language is Chinese.

**Comment by mpetrovic** [comment]
how is the layout different? got a screenshot? can ipads even do that?

On Sun, Dec 18, 2011 at 11:02 PM, Beckheng Lam <
reply@reply.github.com

**Comment by beckheng** [comment]
Please view images here:
http://yixinit.com/gamedev/screenshot/balloon_on_Safari_Windows.jpg
http://yixinit.com/gamedev/screenshot/balloon_on_Safari_Windows_iPad-User-Agent.jpg

The second image is captured from Windows too. But the user-agent of Safari is set as iPad.

Please let me know if you need more information. Or give some advice to fix my issue.
Thanks.

**Comment by sorenbs** [comment]
Crafty does a bunch of stuff when on mobile. The idea is to scale to screen size and hide scroll bars to provide a more native feel. I am not sure how well this works though. Could you try to turn this off by doing
Crafty.mobile = false;
before you initialize Crafty?

**Comment by beckheng** [comment]
I try it.
It's what I expect now.

I would not find the Crafty.mobile from http://craftyjs.com/api/ before.

I feel your goal and know why this happens now. 
Thanks.

**Comment by sorenbs** [comment]
Great. Let us know if you have any other problems.

**Comment by ahilles107** [comment]
Crafty works on Iphone and ipad - i think that we can close this very old issiue?

**Comment by beckheng** [comment]
Hi,

Sorry about this.
I though it was closed automatically.
Thank you very much!

2012/5/29 Paweł Mikołajczuk <
reply@reply.github.com
