### ISSUE TITLE
Compare memory consumption on FF6 between 0.5 and 0.4.5

### ISSUE THREAD

**Issue by sorenbs** [craftyjs/Crafty#127]
See this discussion: https://groups.google.com/forum/#!topic/craftyjs/v_IKimZctQo

Currently the DOM implementation leaks memory in firefox. When the new drawing implementation from DEV branch is merged to master (scheduled for the 0.5 release) it should be tested if it fixes the memory leak.
If not decide what to do about it.

**Comment by louisstow** [comment]
What's the latest on this issue? Does the latest snapshot help at all?

**Comment by sorenbs** [comment]
This is still a problem in the snapshot. I have not tested the dev branch.
On 22 Oct 2011 17:39, "Louis Stowasser" <
reply@reply.github.com>
wrote:

**Comment by sorenbs** [comment]
There might be some useful stats on about:memory

Also, this is an interesting read on the improvements coming in FF11 onwards memory-wise http://blog.mozilla.com/nnethercote/2011/11/01/spidermonkey-is-on-a-diet/

**Comment by ahilles107** [comment]
This issue shoud be closed i think.

**Comment by sorenbs** [comment]
I still think this is an issue that we should do something about. 
I have added a description to make this issue more actionable. Thoughts?

**Comment by ahilles107** [comment]
we must have more data about this memory leak.

**Comment by sorenbs** [comment]
Then i guess the first phase is to gather more data :-)

What i know is, 

1) when you run this program it eats infinite memory on FF (tested on FF 8) but not in chrome or IE

setInterval(function () {
        var a = Crafty.e("2D, DOM, Color").color("red").attr({w:20, h:20})
        .bind("EnterFrame", function () {
            this.x += 1;
            if (this.x > 400)
                this.destroy();
        });
    }, 1);

2) If you use Canvas instead of DOM there is no problem
3) Installing adblock plus makes firefox eat memory faster

This is a problem because many games (including the fruit assassin demo) creates and destroy a lot of entities.
My guess is that somehow we are not freeing DOM elements correctly, but i have not done any thorough analysis.

**Comment by ahilles107** [comment]
On my ff 9 (ubuntu) it works without any leaks.

**Comment by sorenbs** [comment]
Just tested fruit assassin on FF 11, windows. The memory buildup is much slower than on FF 8, but there is still a clear  pattern. mem usage increases slowly, then it drops suddenly (but not as much as it had increased) and the cycle is repeated.
After 20 minutes it cycles between 220 and 250 mb (it used 130 at startup).
Perhaps this is only a problem on windows.

**Comment by ahilles107** [comment]
like i said, ff9 ubuntu after 30 minutes cycle and still 160mb (140 at startup) - for me is the ff issue.

**Comment by BlackScorp** [comment]
i tested the GTA Demo on Ubuntu 11.10 x64 with FF 8.0 in this Resolution it works. if i save the Demo local and make it FullScreen, my FireFox asks me to stop crafty.js. if i change to DOM then it start to load but it lags so much that iam not able to Play. 

on developing i saw that as well, thats why my current Project is using DOM and not Canvas
