### ISSUE TITLE
DOM component needs more POWWWEEEER!

### ISSUE THREAD

**Issue by louisstow** [craftyjs/Crafty#130]
Currently the DOM component doesn't give much control in the way of shuffling it's element around the DOM tree.

See the jQuery API for examples of what could be implemented: http://api.jquery.com/category/manipulation/

**Comment by mpetrovic** [comment]
How much shuffling around does a DOM element need to do?

I think all that really needs to happen is a simpler way to give it a parent other than the inner, so they could be assigned to sort of 'layers'. We'd have the main viewport layer, and then we could have an overlay or HUD layer, and then perhaps a background layer that displays stuff in the distance.

**Comment by louisstow** [comment]
Yeah I agree. Mainly just needs to be able to change the parent. Actually I have a feeling that was implemented.

**Comment by mpetrovic** [comment]
Nope. 

We can add a new element to the DOM directly, and then pass it into entity.dom() to set a new parent, but that's a round-about way to do it.

**Comment by louisstow** [comment]
Ah it was in the dev branch:

https://github.com/louisstow/Crafty/blob/dev/src/DOM.js

Guess we can close this issue, just merge the dev (once it's thoroughly tested).
