### ISSUE TITLE
MBR and SAT collision don't mix

### ISSUE THREAD

**Issue by mfiano** [craftyjs/Crafty#131]
http://groups.google.com/group/craftyjs/browse_thread/thread/b06ffcbd47ed6fea

Quoted from sanojian in the link above:

I am not sure if this will help but I struggled with polygon collision 
until I realized that .hit() only works on other objects defined with 
a polygon.  So once you use a polygon for one object, you have to use 
polygons for all objects.  The default boundaries only detect hits on 
other objects with default boundaries

It seems MBR and SAT collision do not mix for now, assuming I was 
using them correctly.

I am not sure if this is a bug but it is very non-obvious. 

I can reproduce this. Only if I manually define a polygon for each object, does it take the new hitboxes into consideration. Setting a hitbox of just one object results in .hit() using the default polygon instead.

**Comment by sorenbs** [comment]
To fix this we need to call collision() from init() in Collision component, and make sure that collision() can handle being called twice.
