### ISSUE TITLE
Crafty mouse events on IE 8, 9 and Opera don't work.

### ISSUE THREAD

**Issue by hex** [craftyjs/Crafty#132]
The mouse events (MouseOver, MouseOut, Click... ) don't work on IE8 and IE9 and Opera. I got this problem when building my own app. I tested the isometric demo (with crafty 0.4.4.) and it doesn't work either.

**Comment by louisstow** [comment]
Hm from that I would say it's a problem with the `addEvent` method (IE and Opera use the same method).

**Comment by mpetrovic** [comment]
IE9 should be using addEventListener, since MS finally decided to grace us with its presence in their browser.

**Comment by sorenbs** [comment]
There was a bug in DOM.inner that caused the result to be NaN some times. Could one of you have a quick glance at the change i made?
