### ISSUE TITLE
Numerical inaccuracy in Polygon.rotate

### ISSUE THREAD

**Issue by alexpusch** [craftyjs/Crafty#134]
In polygon.rotate the result of the rotation is floored:

current[0] = Math.floor(x);
current[1] = Math.floor(y);

The results of this floor is an accumulated numerical error, that in turn breaks collision detected of rotating objects and other features that rotate polygons.

**Comment by louisstow** [comment]
So would you suggest removing the rounding?

**Comment by alexpusch** [comment]
Yes, unless there is some other reason for it of course.
