### ISSUE TITLE
Add MouseEnter event

### ISSUE THREAD

**Issue by statico** [craftyjs/Crafty#142]
Instead of binding MouseOver and MouseOut events to each other, it'd be great if one event was fired when the mouse first hovers over an entity: MouseEnter.

<3

**Comment by sorenbs** [comment]
Isn't that exactly what MouseOver does? Fires when the mouse first hovers over an entity.

**Comment by statico** [comment]
I'm pretty sure MouseOver fires continuously while the mouse is moved inside the rectangle.

**Comment by sorenbs** [comment]
I just tested this http://jsfiddle.net/ncWYk/1/

MouseOver fires only once
MouseMove fires continually

**Comment by statico** [comment]
Weird. I guess I'm nuts. Thanks for confirming this — I'll close the ticket.

**Comment by sorenbs** [comment]
My pleasure :-)
