### ISSUE TITLE
Crafty.sprite Signature

### ISSUE THREAD

**Issue by thepudding** [craftyjs/Crafty#146]
The signature in the comments:
```@sign public this Crafty.sprite([Number tile], String url, Object map[, Number paddingX[, Number paddingY]])

``````

Does not match the actual signature:
```sprite: function(tile, tileh, url, map, paddingX, paddingY)
``````

For instance
```Crafty.sprite("sprite.png", {a:[1,2,4,4]});

```
produces an error.
```

**Comment by sorenbs** [comment]
Many functions in Crafty implements overloading by looking at the type of the parameters or using the arguments keyword, so the actual signature is not always telling the truth. In sprite() the first 20 lines or so deals with exactly this.

Crafty.sprite("sprite.png", {a:[1,2,4,4]}); should work fine. If you could create a jsfiddle we can have a look and see what is wrong.

**Comment by louisstow** [comment]
The square braces (`[]`) denote optional field. If that produces an error it is indeed a bug. It is also now wrong because there is a tile height added to the mix.

**Comment by thepudding** [comment]
It might be un-javascripty, but what about using some sort of factory for sprite? That or possibly have a hash/object with named parameters? All the optional arguments are making the signature a little messy.

**Comment by louisstow** [comment]
Yeah that is a good point. It started off with 2 params and got big quickly.
