### ISSUE TITLE
Collision Events get implicitly cancelled

### ISSUE THREAD

**Issue by robkuz** [craftyjs/Crafty#147]
When a collision event is created and one of the listeners to that event
reverts the condition that lead to that collision event in the first place
the event gets silently cancelled out for all following listeners (callbacks).

This leads to the effect that one has to take care in which order listeners
to onHit are added and what those listeners do. At the end it makes for
very brittle code.

please see the fiddle over here http://jsfiddle.net/robertj/przxN/7/

Only if the order of the two onHit callbacks is reversed the debug message
is ever printed.

**Comment by grozen** [comment]
I am so on this.

**Comment by starwed** [comment]
This isn't really configured as a Crafty event in the first place -- and that would probably be the best way to fix it.

Currently `onHit` sets up a function that, on each "EnterFrame"  watches for hit events, and uses the callbacks when the hit state changes.  Each call to `onHit` sets up a new watcher.

If the watcher instead triggered  "OnHit" and "OnHitOff" events (or whatever it makes sense to call them), then any number of handlers bound to those events would get called.  Of course, these might then need to handle the "cancelled collision" case themselves.

**Comment by grozen** [comment]
That actually sounds considerably better than what I had in mind (consolidate all the individual callbacks, and call them as a unit).

Not very backwards compatible, but you know that I favor improvement over preservation. I do believe your solution would also fix this bug (all registered handlers will be called once the collision takes place, regardless of what side effects they cause).

However, like many aspects in Crafty collision could use some tests, so I set out to do that as well while I'm at it. Thing is, I tried setting up three entities that have the `Collision` and `SolidHitBox` components for said tests, only to end up with the following flicker-fest: http://jsfiddle.net/mCdUX/145/

Am I doing something wrong, or is this yet another bug? (Which I will gladly squish along with this, if it doesn't prove too much of a mess)

**EDIT:** I must not have saved my fiddle properly... but also the issue vanished after rebuilding Crafty. Must have been using an old version. Onward with solving this, then.

**Comment by grozen** [comment]
@starwed can we consider this issue closed? This bug was actually what caused me to introduce the event-based hit detection, following your sage advice.

Of course the problem persists if you keep using the old style `OnHit`, but using events instead solves the problem, as I demonstrated in the fiddle I linked to in my pull request.

**Comment by mucaho** [comment]
closed this, as it has been resolved with #699 .
