### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by sorenbs** [craftyjs/Crafty#156]
I think all functions that take parameters should have examples attached. This needs documentation:

Functions:
Crafty.matrix
Crafty.math all functions (example)
Crafty.map

Feel free to add what i've missed.

**Comment by pengyu** [comment]
The documents for the following are also missing.

Crafty.step
Crafty.timer
Crafty.map

**Comment by ahilles107** [comment]
i just documented:

Crafty.scene (example)
Color.tint
Sprite.sprite (example)
Sprite.crop (example)

**Comment by pengyu** [comment]
Thanks!

2012/1/3 Paweł Mikołajczuk
reply@reply.github.com:

> i just documented:
> 
> Crafty.scene (example)
> Color.tint
> Sprite.sprite (example)
> Sprite.crop (example)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/louisstow/Crafty/issues/156#issuecomment-3348090

## 

Regards,
Peng

**Comment by sorenbs** [comment]
Getting there :-)

**Comment by ahilles107** [comment]
can we close this?

**Comment by sorenbs** [comment]
sure
