### ISSUE TITLE
Image function with Canvas.

### ISSUE THREAD

**Issue by ahilles107** [craftyjs/Crafty#158]
entity.image() with Canvas sets image for all canvas object - shoud set image only for entity. For DOM it works properly.

**Comment by ahilles107** [comment]
@radzikowski it was fixed, or not?

**Comment by radzikowski** [comment]
@ahilles107 Yes, but I have to do some test with repeat, repeat-x, repeat-y

**Comment by ahilles107** [comment]
how about this?

**Comment by radzikowski** [comment]
I have to correct new branch structure and then I will send correct image rendering.

**Comment by radzikowski** [comment]
I think this is resolved. Close issue?

**Comment by ahilles107** [comment]
Yep, it working ok now!
