### ISSUE TITLE
Isometric Example

### ISSUE THREAD

**Issue by iwarner** [craftyjs/Crafty#166]
I get 

Uncaught TypeError: Cannot call method 'randomInt' of undefined

which corresponds to the line;

var which = Crafty.math.randomInt(0,1);

this works var which = Crafty.randRange(0,1); - from the example on the site

Cheers

**Comment by mpetrovic** [comment]
The example in github is currently use 0.4.5, which hasn't been released yet. Try using the snapshot, a link to which you can find in the wiki.

**Comment by iwarner** [comment]
Updated to snapshot and still get this - randRange does now not exist.

Uncaught TypeError: Cannot call method 'randomInt' of undefined

**Comment by mpetrovic** [comment]
Oh right. The snapshot is missing the math file. 

Try this:
http://www.guneva.net/crafty/live.php

**Comment by iwarner** [comment]
Thanks got it working now.

**Comment by iwarner** [comment]
Only issue is on my Mac through chrome using canvas it does not appear to be executing this section to remove a block.

```
        var tile = Crafty.e("2D, Canvas, "+ (!which ? "grass" : "stone") +", Mouse")
        .attr('z', i + 1 * y + 1).areaMap([64,0],[128,32],[128,96],[64,128],[0,96],[0,32]).bind('click', function(e)
        {
            console.log(e);

            // Destroy on right click
            if (e.button === '2') {
                this.destroy();
            }
```

**Comment by mpetrovic** [comment]
Are you right-clicking? 
If so, what button does it give when you do?

...you can right-click on Macs now, right?

**Comment by iwarner** [comment]
Yes right clicking - it works in this example
http://craftyjs.com/demos/isometric/

but not with my copy..

I can catch the event here 

```
Crafty.addEvent(this, Crafty.stage.elem, 'mousedown', function(e)
{
    if (e.button > 1) {
        console.log(e);
        return;
    }
```

MouseEvent
altKey: false
bubbles: true
button: 2
cancelBubble: false
cancelable: true
charCode: 0
clientX: 469
clientY: 396

**Comment by mpetrovic** [comment]
what does the console.log() report when you use it in the game, like in the
snippet from earlier?

On Fri, Jan 6, 2012 at 3:49 PM, Ian Warner <
reply@reply.github.com

**Comment by iwarner** [comment]
you mean this

 var tile = Crafty.e("2D, Canvas, "+ (!which ? "grass" : "stone") +", Mouse")
        .attr('z', i + 1 \* y + 1).areaMap([64,0],[128,32],[128,96],[64,128],[0,96],[0,32]).bind('click', function(e)
        {
            console.log(e);

```
        // Destroy on right click
        if (e.button === '2') {
            this.destroy();
        }
```

it doesnt report anything ...

**Comment by iwarner** [comment]
one difference i have found is that all my elements have:
visibility: visible;

attached to them - whereas the older tutorial did not

investigating

**Comment by iwarner** [comment]
Ok definitely a bug in your latest script somewhere, I have replicated the old tutorial verbatim and it works now on my local too.

Should try and keep the examples up with what is going on in the development.

**Comment by louisstow** [comment]
Which version? It's not in 0.4.4 yet, will be out in the next version
though. We've been updating docs before we release which should be soon.

On Sat, Jan 7, 2012 at 6:09 AM, Ian Warner <
reply@reply.github.com
