### ISSUE TITLE
document events

### ISSUE THREAD

**Issue by sorenbs** [craftyjs/Crafty#182]
We need some way to document events in the api doc. This includes
- [Done] a way to denote that a function/component triggers an event and add a description of when it happens
- a way to denote that a function/component binds to an event and add a description of what happens when it is triggered
- [Done for triggers] triggers and binds sections should be added to the generated api pages
- create an extra page with a list of all events and links to functions/components that triggers or binds them.

In a similar way we want to document what components a component requires
- requires section should be added to the generated api pages. Maybe [inherits/depends on/uses] would be better names?

**Comment by pengyu** [comment]
Besides creating automatically extracted document from the source code. I also make some stand-alone examples. Some of the are related with events. Take a look and see if you have any more example to contribute. The directory structure follows the current structure of the document (more or less).

https://github.com/pengyu/Crafty-JS-Examples

**Comment by sorenbs** [comment]
I have added support for @trigger tags in the documentation that will create a list of events on the api page. Now we just need to add the docs :-)
see https://github.com/louisstow/Crafty/commit/e5b1cdfb8ad64f5052ebcfbbc3c4e411671a4fc1

**Comment by mleveck** [comment]
This issue would also be helped if it were clear in the documentation which Controls inherit from each other. The example I'm thinking of Fourway requires Multiway, which means that Fourway throws a 'Moved' event as well. 

However, while the documentation notes that Multiway throws a 'Moved' event, it doesn't note that for Fourway, or that Fourway inherits form Multway. The only way to figure out that Fourway inherits this property is to look at the crafty.js code.

**Comment by sorenbs** [comment]
Would it work if we add a list of required components to the documentation
that is automatically linked?
Den 25/01/2012 01.05 skrev "mleveck" <
reply@reply.github.com

**Comment by mleveck** [comment]
Yes!

**Comment by ahilles107** [comment]
i think that we can close this issue - right?

**Comment by sorenbs** [comment]
Only the bullet points marked with [done] are done.
I think we should at least address the last one.

**Comment by pengyu** [comment]
[Done for triggers] triggers and binds sections should be added to the generated api pages

Besides the "bind" sections, there should be also a centralized page (or pages) that categorize all the events. For example, 'Change' has been used in many places in Crafty, without a central page, it is very hard to grasp what it does.

I think that this should be of high priority. Without a guideline of all the internal events that that is already supported in Crafty, it is difficult to add basic component that support these events constant with the current ones.

I'm pretty new to php. sorenbs: can you add this support fairly quickly?

2D.js:14:\* @trigger Change - when the entity has moved - { _x:Number, _y:Number, _w:Number, _h:Number } - Old position
2D.js:202:                  this.trigger("Change", old);
2D.js:583:      this.trigger("Change");
2D.js:629:      this.trigger("Change", old);
DOM.js:20:      this.bind("Change", function () {
DOM.js:233:     this.trigger("Change");
animation.js:6:\* @trigger Change - On each frame
animation.js:148:       this.trigger("Change");
canvas.js:19:       this.bind("Change", function (e) {
core.js:330:    \* @trigger Change - when properties change - {key: value}
core.js:351:                this.trigger("Change", key); //trigger change event
core.js:359:            this.trigger("Change", change); //trigger change event
drawing.js:25:  \* @trigger Change - when the color changes
drawing.js:40:      this.trigger("Change");
drawing.js:72:  \* @trigger Change - when the tint is applied
drawing.js:87:      this.trigger("Change");
drawing.js:129: \* @trigger Change - when the image is loaded
drawing.js:174:             self.trigger("Change");
drawing.js:188:     this.trigger("Change");
extensions.js:168:                      this.trigger("Change");
extensions.js:201:                      this.trigger("Change");
extensions.js:449:                  oldTarget.unbind('Change', change);
extensions.js:458:              target.bind('Change', change);
sprite.js:4:\* @trigger Change - when the sprites change
sprite.js:70:       this.trigger("Change");
sprite.js:107:      this.trigger("Change", old);
text.js:4:\* @trigger Change - when the text is changed
text.js:81:     this.trigger("Change");
text.js:106:        this.trigger("Change");
text.js:119:    \* @triggers Change
text.js:147:        this.trigger("Change");

**Comment by sorenbs** [comment]
I don't think it should be too hard to do. Just need to - you know - do it :-)

**Comment by pengyu** [comment]
Another feature might be helpful is the original document where a component appears, which should be able to be generated by document generator like doxygen.

**Comment by sorenbs** [comment]
You mean the name of the javascript file that the documentation comes from? That would be pretty helpful now i think of it.

**Comment by pengyu** [comment]
Yes. I mean the javascript file.

**Comment by pengyu** [comment]
Another possible feature is to generate an index. This will be useful as the document become longer and longer.

**Comment by sorenbs** [comment]
jhcp just submitted a patch to generate an indox of all events.
