### ISSUE TITLE
Collision Circle Bug

### ISSUE THREAD

**Issue by dbsleiman** [craftyjs/Crafty#203]
I'm not sure if it's a bug or just my misunderstanding of how to use it, but it seems that if you pass a circle to the collision constructor, no matter what values you pass for the x and y of the circle, it is always drawn at 0,0 relative to the entity.  According to the documentation, this shouldn't be the case:

<i>When creating a circle for an entity, each point should be offset or relative from the entities x and y (don't include the absolute values as it will automatically calculate this).</i>

I have managed to get around this by modified the following line of the collision constructor:

<code>this.map.shift(area.x, area.y);</code>

with

<code>this.map.shift(area._x + (poly.x || 0), area._y + (poly.y || 0));</code>

**Comment by nojacko** [comment]
I've come across this but too. Here you can see a good example. 

http://jsfiddle.net/mCdUX/112/

**Comment by sorenbs** [comment]
I have updated Circle to shift all points according to the passed (x,y).
