### ISSUE TITLE
Multiple @see's in the same line are not possible in the document.

### ISSUE THREAD

**Issue by pengyu** [craftyjs/Crafty#208]
If I want to have multiple @see in the same line, the generated document only has 1 incorrect hyperlink.

@see Crafty.stop @see Crafty.init

Although it is OK with multiple lines of @see, it is better to compress them into one line.

@see Crafty.stop
@see Crafty.init

**Comment by sorenbs** [comment]
Is this related to your comment in https://github.com/pengyu/Crafty/blob/1e984f3840481f5c87824e25c3de7cc352249c6b/src/core.js#L685

**Comment by pengyu** [comment]
Yes.

**Comment by sorenbs** [comment]
It should be possible to do
@see Crafty.stop, Crafty.init

**Comment by mpetrovic** [comment]
Can we close this issue then?
