### ISSUE TITLE
sprite padding not respected in animations

### ISSUE THREAD

**Issue by thedavidmeister** [craftyjs/Crafty#211]
the X and Y padding defined in Crafty.sprite() are not respected when running e.animate() with "SpriteAnimation", only the tile's height and width are used for the calculation so the animation never looks smooth.

**Comment by NyanLeek** [comment]
Please see:
https://groups.google.com/d/topic/craftyjs/SIG1cJXWW1U/discussion
for a fix.

**Comment by NyanLeek** [comment]
Fixed on commit 967fa2fa9f55f91aac89b22c5c2fdef587bb39de
