### ISSUE TITLE
.areaMap polygon overrides .collision(polygon)

### ISSUE THREAD

**Issue by NyanLeek** [craftyjs/Crafty#243]
If they are different methods used for different things (collisions and mouse events) they should have different polygons.

If you set a collision polygon, and then a different areamap for mouse events all the collisions occur within the areamap,
This is due to areaMap and collision storing its polygon in the same variable; this.map, and .isAt reading said map, however if i read the source correctly .isAt is only used for mouse events, so, a good solution would be setting areaMap to store its map in another variable and isAt reading accordingly, and defaulting to collision map if there's no areaMap map.

**Comment by ahilles107** [comment]
This issiue is allredy fixed?
