### ISSUE TITLE
StopDrag gets called on all entities the first time.

### ISSUE THREAD

**Issue by arjan0307** [craftyjs/Crafty#245]
Imagine the following situation:
      ```var foo, bar;
      foo = Crafty.e("2D, DOM, Draggable").attr({
        x: 100,
        y: 100,
        z: 1,
        h: 32,
        w: 32
      }).bind("StopDrag", function(e) {
        return console.log('foo');
      });
      bar = Crafty.e("2D, DOM, Draggable").attr({
        x: 200,
        y: 200,
        z: 1,
        h: 32,
        w: 32
      }).bind("StopDrag", function(e) {
        return console.log('bar');
      });

``````
Now the dragging works perfectly, the problem is however that the first time I drag something, both foo and bar are logged. The StopDrag function gets called for both instances. When I drag any of the entities a second time, just foo or bar is logged depending on which entity I dragged.

When I comment out the following line in the function enableDrag in crafty.js:
```Crafty.addEvent(this, Crafty.stage.elem, "mouseup", this._onup);```
Everything seems to work perfectly, when I drag one of my entities the first time, just foo or bar is logged depending on the entity I dragged.
``````

**Comment by radzikowski** [comment]
@ahilles107 You done some fixes with develop branch with this issue, are you?

**Comment by ahilles107** [comment]
Yep, it was #274
