### ISSUE TITLE
Audio.add crashes Crafty in Safari

### ISSUE THREAD

**Issue by jayvan** [craftyjs/Crafty#246]
Audio.add fails on the following line..
audio = new Audio(),

Which is a showstopper. We should test for audio support before creating audio objects so that worst case, users can play the game with no audio.

**Comment by mpetrovic** [comment]
what version of Safari are you using?

**Comment by jayvan** [comment]
5.1.2(6534.52.7) on mac.
On Apr 10, 2012 2:53 PM, "Matthew Petrovic" <
reply@reply.github.com>
wrote:

**Comment by mpetrovic** [comment]
What's the exact error? Audio is supported on Safari so it shouldn't be crashing like that.

**Comment by BlackScorp** [comment]
hm.. in the current version there is no audio = new Audi() code only this  return typeof Audio !== 'undefined' ? new Audio("") : document.createElement('audio');

**Comment by ahilles107** [comment]
It still crashes in Safari?

**Comment by sorenbs** [comment]
please reopen if this is still an issue.
