### ISSUE TITLE
adding 'Gravity' breaks the 'Twoway' component

### ISSUE THREAD

**Issue by DelishusCake** [craftyjs/Crafty#252]
If gravity is added to an entity to simulate jumping, the jumping part works, but two way movement breaks:

window.onload = function ()
{
  Crafty.init(800, 600).canvas.init();
  Crafty.scene("Level1", function()
  {
      Crafty.background("rgb(0, 255, 0)")
      Crafty.e("2D, DOM, Platform, Color")
          .attr({x: 5, y: 30, w: 50, h: 10})
          .color("rgb(0, 0, 255)");
      Crafty.e("2D, DOM, Twoway, Gravity, Color")
          .attr({x: 10, y: 10, w: 10, h: 10})
          .gravity(["Platform"])
          .twoway(50, 5)
          .color("rgb(255, 0, 0)");
      });
      Crafty.scene("Level1");
}

**Comment by airza** [comment]
I encountered the same problem., running essentially identical code.

**Comment by ghost** [comment]
Same problem here. Narrowed it down as a regression between 0.4.4 and 0.4.6. Everything works fine in 0.4.4, 0.4.5 has weird acting gravity and 0.4.6 breaks Twoway by attempting to fix the gravity issue.
