### ISSUE TITLE
Crafty.sprite(undefined, ...

### ISSUE THREAD

**Issue by robkuz** [craftyjs/Crafty#253]
Hi,

if one tries to load a sprite file with the size being undefined I dont get any error but sadly I dont get any sprites as well.

Crafty.sprite(undefined, "some/file.png", {});

I guess this is now the 3rd time I ran into this exact error and only after an hour or so realized that my size is undefined.

**Comment by ahilles107** [comment]
What You want to see when this happens? I think that isn't really issue.

**Comment by robkuz** [comment]
Why do you think that this isnt really an issue?
Obviously it doesnt load or show any sprite that is loaded when the first parameter is undefined.
This Method is not prepared to handle that situation. And either it should give a log warning or an error right away.

**Comment by ahilles107** [comment]
What You want to see when this happens? How we shoud show error message?

**Comment by robkuz** [comment]
I am not sure how exactly you should show an error message.
Crafty is very, very light on error messages in general ;-)
I think the most appropriate thing to do would be to throw an error.
