### ISSUE TITLE
MouseDown and Click

### ISSUE THREAD

**Issue by zemd** [craftyjs/Crafty#254]
I made component "Button" and I bind 2 events for MouseDown and Click:

this.bind("MouseDown", function () {
                console.log("MouseDown");
});
this.bind("Click", function () {
               console.log("Click");
});

But this doesn't work - MouseDown triggers only. When I remove MouseDown - Click event triggers ok.

**Comment by ahilles107** [comment]
with latest develop works great. I close this issiue.
