### ISSUE TITLE
Polygons

### ISSUE THREAD

**Issue by kamildrazkiewicz** [craftyjs/Crafty#268]
Has crafty got support for drawing a sample polygons (rects, circles etc.) ? Is the only way to draw it is use canvas directly?

**Comment by BlackScorp** [comment]
i just created a component to create a polygon with defining points, adding some functions like rect, circle and stuff and you got a full working Component 

http://jsfiddle.net/mCdUX/146/

and yes you can only Draw by using Canvas, SVG does not work and DOM never could draw

**Comment by kamildrazkiewicz** [comment]
Hi

I created a custom draw component(progress bar) and I would like to draw on each frame even object is out of draw 
region. Do I need to bind some event or use DrawManger? 

I tried to trigger "Draw" on "EnterFrame" event but object is blinking :(

**Comment by BlackScorp** [comment]
please use basic HTML for GUI elements , with jQuery like on the demo https://github.com/BlackScorp/cron/blob/gh-pages/index.html  i made div id interface into cr-stage

**Comment by kamildrazkiewicz** [comment]
ok, but some of my elements (like progrssbars) need to be move when the viewport is moving(dragging by mouse) so I tried to use Canvas. For static UI elements I using HTML. Can I do that with DOM drawing?

**Comment by kamildrazkiewicz** [comment]
Ok, I found a solution. I just triggered "Change" event and it works.
