### ISSUE TITLE
WiredHitBox - still draw lines after remove component

### ISSUE THREAD

**Issue by ahilles107** [craftyjs/Crafty#277]
If we remove WiredHitBox it shoud remove drawed collision lines. @BlackScorp

**Comment by BlackScorp** [comment]
basicly HitBox component is used for debuging, i didnt expected that it comes into release, maybe someone could make a better component? my knowledges in canvas are poor.

**Comment by ahilles107** [comment]
We use HitBox in Crafty DebugBar and it's very usefull - it shoud stay and get some improvments. If you don't have time for this then we will do this ;).

**Comment by BlackScorp** [comment]
do it please;) replace it with your own better code and setting up different colors and stuffs would be very nice

**Comment by BlackScorp** [comment]
@ahilles107 i started to make a new version https://github.com/BlackScorp/crafty_hitbox/tree/gh-pages  but it is not performant, maybe you can look throught
