### ISSUE TITLE
DOM Stage get's created irrespectively to the use of it.

### ISSUE THREAD

**Issue by atimmer** [craftyjs/Crafty#28]
The DOM Stage get's created irrespectively to the use of it, so if you would only use the canvas (which is preferably on any browser that fully supports it) the DOM Stage still get's created.

I would opt in for a parameter to the Crafty.init function to set the Stage, DOM or Canvas. This would allow for feature detection and delivering the Stage that is relevant for that browser.

This way you can support the older browsers without support for canvas and the newer browsers can make full utilization of Canvas and the browser's ability to Hardware accelerate it.

**Comment by louisstow** [comment]
In later versions, the stage will be mandatory due to a new optimization with multiple canvas elements.
