### ISSUE TITLE
viewport.mouselook is not taking zoom-level into account.

### ISSUE THREAD

**Issue by nocksock** [craftyjs/Crafty#285]
I already posted it into the [google-groups](https://groups.google.com/forum/?hl=en&fromgroups#!topic/craftyjs/_-pVfOMnkZU) but to avoid to let this slip into the back of heads I created an Issue for this. 

Here I recreated the problem: http://jsfiddle.net/noxoc/dQyy2/ It should basically not be possible to move the image horizontally.

**Comment by sorenbs** [comment]
Do you know what the status is on this?

**Comment by starwed** [comment]
Should now be fixed by #648!
