### ISSUE TITLE
better builder for documentation

### ISSUE THREAD

**Issue by ahilles107** [craftyjs/Crafty#286]
- list of all events triggered in crafty (on one page)
- better linking for @see
- more examples (.hit for example)
- some tweaks for look - unfortunately, @louisstow  decided to not implement changes for css from release 0.4.8 (https://github.com/craftyjs/Crafty/blob/master/build/global.css#L97 and line 98)

**Comment by starwed** [comment]
This is mostly taken care of -- there's a bug open for the css in the site's own tracker.  

And while we should always look for ways to improve docs, we don't need a blanket bug for that.  :)
