### ISSUE TITLE
Can't draw entities when viewport coords are negative

### ISSUE THREAD

**Issue by statico** [craftyjs/Crafty#29]
Crafty seems like a great library. Another developer and I ran into this bug when trying to create a scrolling-map game.

I made a quick demo of this bug — drag the white rectangle around:

> http://x.langworth.com/craftytest/

When the viewport coordinates are set to negative values, entities aren't drawn or updated correctly.

**Comment by louisstow** [comment]
Will have to take a look at that. The next version of Crafty has a completely different draw method which should solve pretty much every canvas drawing issue. Will try your demo with the new code.

**Comment by statico** [comment]
Awesome, thanks!

**Comment by statico** [comment]
(Argh, closed this issue by accident.)
