### ISSUE TITLE
Mouse position not available.

### ISSUE THREAD

**Issue by DelishusCake** [craftyjs/Crafty#291]
Getting the x and y positions of the mouse cursor is not possible, even through the mouse component. Not sure if this is an actual issue, but it may impair game development,

**Comment by ahilles107** [comment]
Coud you write example on jsfiddle.net?

**Comment by BlackScorp** [comment]
@DelishusCake http://jsfiddle.net/vRG2k/  click on the red cube to get absolute Position use screenX + Crafty.viewport._x
