### ISSUE TITLE
Stopping sounds

### ISSUE THREAD

**Issue by mkilling** [craftyjs/Crafty#292]
Is there any way to stop looping sounds?

**Comment by BlackScorp** [comment]
Crafty.audio.stop("soundname"); or Crafty.audio.stop() to stop all sounds

**Comment by cawoodm** [comment]
Consider adding `stop()` to the docs?
http://craftyjs.com/api/Crafty-audio.html

**Comment by darrentorpey** [comment]
It looks like the docs just haven't been re-built in a while. There's inline comment doc for stop() and others but they're not up at http://craftyjs.com/api/.
