### ISSUE TITLE
Crafty.timer.curTime does not get updated in IE

### ISSUE THREAD

**Issue by fromkeith** [craftyjs/Crafty#299]
The value **Crafty.timer.curTime** does not get updated in IE.

The problem is in

``` javascript
          init: function () {
          ...
                } else {
                    tick = setInterval(Crafty.timer.step, 1000 / FPS);
                }
          },
          ....
         step: function () {
                loops = 0;
                this.curTime = Date.now();
        ....
```

When setInterval calls the _Crafty.timer.step_ function pointer, it does not have the proper context. Hence, _this.curTime_ is not reference the timer object in the step function.
Possible fix:

``` javascript
         tick = setInterval(function () { Crafty.timer.step(); }, 1000 / FPS);
```

**Comment by ahilles107** [comment]
Can You make a PR and test your proposal fix?
