### ISSUE TITLE
Call for direction

### ISSUE THREAD

**Issue by a-zb** [craftyjs/Crafty#3]
Since time is of the essence, how can we help?

Checked out the code. I'm studying it now. Can you map out a small goal roadmap for Crafty.
Maybe we can help with the site a bit. I can jump on a couple of the links that are #comingsoon.

Let us know. Good job so far mate.

**Comment by louisstow** [comment]
Cheers.
- Better Isometric support (mainly z-index values)
- Fix bugs with HTML5 audio (see here: http://stackoverflow.com/questions/4435009/html5-audio-plays-randomly)
- Canvas text support
- Better collision

Those are the main lacking areas of Crafty so far. As for the site, I need a good bug tracker (preferably PHP) . Plan on just using SMF forums and WordPress for the blog. As for the extensions (or plugins). Hopefully I can get that going today. If you have any ideas, let me know.

**Comment by louisstow** [comment]
Closing this to clean up open issues
