### ISSUE TITLE
right click doesn't work

### ISSUE THREAD

**Issue by cggff** [craftyjs/Crafty#301]
Hello,

The right click doesn't work on the last version of craftyjs.
I've create two test (click in the box to rotate it).
- 0.4.9: http://jsfiddle.net/vGeWb/ (doesn't work right click)
- 0.4.3: http://jsfiddle.net/8ufKb/ (works right click)

Thanks.

**Comment by sorenbs** [comment]
Use MouseDown or MouseUp instead. Also to to accommodate for browser inconsistencies you should compare like this instead:

e.mouseButton === Crafty.mouseButtons.RIGHT

I will update http://craftyjs.com/api/Mouse.html
