### ISSUE TITLE
Inputs, textareas don't work over the canvas.

### ISSUE THREAD

**Issue by vodkabears** [craftyjs/Crafty#303]
Crafty intercepts keyboard events and cause of this inputs, textareas don't work. 

Example: http://jsfiddle.net/mCdUX/170/

---

with 0.4.8 and below - works fine.

Example: http://jsfiddle.net/mCdUX/171/

**Comment by mkoskela** [comment]
This is really annoying problem.

**Comment by tamagokun** [comment]
I've been able to fix this with:

``` javascript
Crafty.selected = false;
```

Then pass focus to your input. I've still experienced issues trying to click into text fields, but if you use .focus() it seems to work.

**Comment by mkoskela** [comment]
tamagokun, thanks for the tip. I got it working on desktop (Chrome) but only partly on iOS6. If you touch anything outside the focused input field Crafty becomes selected and keypresses don't work anymore.

Only working hack for me was to comment out preventDefaults in keyboardDispatch and touchDispatch in Crafty source code. I have to look into this as I get more accustomed with Crafty.

**Comment by vodkabears** [comment]
https://github.com/VodkaBears/Crafty/commit/4d0d58aeec823f0dda9f29cc7c8e5a7513ba0271

Hello, i think, i've fixed keyboardDispatch.

**Comment by mpetrovic** [comment]
you'll probably want to add select and option to that too

**Comment by vodkabears** [comment]
> you'll probably want to add select and option to that too

For fast access to options by keyboard? This is not so critical.
In fact, i forgot about it.

**Comment by starwed** [comment]
Is this fixed by #373 and #387?

**Comment by starwed** [comment]
I don't see this in either of the fiddles offered.  I'm going to assume this is fixed.

**Comment by starwed** [comment]
This is still an issue for touch events; needs basically the same fix as for mouse events.

**Comment by starwed** [comment]
Should be fixed by #646.
