### ISSUE TITLE
Text can be selected while dragging a component in Firefox

### ISSUE THREAD

**Issue by mkalam-alami** [craftyjs/Crafty#304]
I get a bug with the minimal example below and Firefox 13 (works fine with Chrome) :
1. Grab the red square
2. While moving it you can accidentally select the "Blah blah" text, which shouldn't happen
3. If you release the square when some text is selected, grabbing it again will make the Dragging feature glitchy.

``` html
<!doctype html>
<head>
  <script type="text/javascript" src="crafty-local.js"></script>
  <script type="text/javascript">

  window.onload = function() {

  Crafty.init(800, 600);

  Crafty.scene('DraggableBug', function() {

    Crafty.e('2D, DOM, Draggable')
      .attr({w: 200, h: 200, x: 30, y: 30})
      .css({'background-color': '#F00'});

    Crafty.e('2D, DOM, Text')
      .attr({x: 100, y: 100})
      .text("Blah blah blah");
  });

  Crafty.scene('DraggableBug');

  };

  </script>
</head>
<body>
</body>
</html>
```

**Comment by austinh** [comment]
I know this doesnt particularly solve the bug but have you tried using the css selector user-select: none?

Using this (with jQuery) solves any problems I have with this.
            $(this)
                .css({
                    '-moz-user-select':'none',
                    '-webkit-user-select':'none',
                    'user-select':'none',
                    '-o-user-select':'none',
                    '-ms-user-select':'none'
                });

// this prevents chrome bugs
this.onselectstart = function() { return false; };

Hopefully something like this can be implemented into core. :)

**Comment by mkalam-alami** [comment]
Yes that's what I eventually went for, things work fine if `user-select` is disabled. Personally I went with a:

```
div {
  -moz-user-select: none; 
  -khtml-user-select: none; 
  -webkit-user-select: none; 
  -o-user-select: none; 
}
```

in the page stylesheet.

**Comment by sorenbs** [comment]
We should add this to Crafty somehow. Please report if you get additional experience.

**Comment by starwed** [comment]
A [function](http://craftyjs.com/api/Text.html#-unselectable) to make text unselectable was added.  A developer would still have to manually call it, though.

Not sure if this bug should be closed, or if the "Draggable" component should automatically take care of this.

**Comment by mkalam-alami** [comment]
Nice addition :)

Now even though it doesn't affect the bug itself (being that Draggable gets glitchy on FF when combined with text selection), things seem much better on Firefox 20:

http://jsfiddle.net/L5SS8/

It must have been a Firefox issue, so I guess we can close this.
