### ISSUE TITLE
Text Component and MSIE < 9

### ISSUE THREAD

**Issue by austinh** [craftyjs/Crafty#306]
Using the Text component with the DOM renderer on IE7 and 8 (dont have access to 6) causes the following error:
SCRIPT87: Invalid argument. 
crafty.js, line 8234 character 5

This issue was also reported in March on the google groups.

https://groups.google.com/forum/#!msg/craftyjs/mK_cDWSCo64/HCvkCwE6ya8J

Commenting out the .font line works, but disables fonts for other browsers when using "DOM" rendering.

IE7 and 8 consider .font an invalid style selector. I'm not sure how to fix this as i've tried the following:

```
                    style['fontFamily'] = this._textFont["family"];
                    style['fontSize'] = this._textFont["size"];
                    style['fontStyle'] = this._textFont["type"];
                    style['fontWeight'] = this._textFont["weight"];
```

but it doesn't seem to work regardless.

**Comment by jlreymendez** [comment]
I have tried the same changes and It seemed to work for me.

**Comment by austinh** [comment]
Hm... I do not have access to full IE 7 or 8, and have been using IE Tester. Perhaps there is a difference?

Either way, if others could test this and a works, then I (or someone else) can make a pull request.

**Comment by jlreymendez** [comment]
Well, I used IE 9  in compatibility mode. I have access to a native IE7 so I will test it there as well.

**Comment by jlreymendez** [comment]
I had no luck, I get a lot of different errors in IE 7.. 

I think the code might need a pass through a js linter.

**Comment by mpetrovic** [comment]
The real question is 'do we care about IE7'. 

Because I certainly don't.

**Comment by austinh** [comment]
It's not just IE7 though, it's also IE8, and it should be a relatively simple fix.

**Comment by jlreymendez** [comment]
Well if the engine says it supports IE7 then I think the idea is to make it work in IE7.

**Comment by mpetrovic** [comment]
IE8 we should definitely fix. If you think its simple, feel free to fork the repo and submit a pull request. I'll be unavailable to fix it for the next week or so.

IE7 we should drop support for. Both it and IE6 are used by less than 1% of North American users, 2% of European users and 5% of the world outside China. 

sources:
http://www.ie6countdown.com/#list
http://www.netmarketshare.com/browser-market-share.aspx?qprid=2&qpcustomd=0

Is it worth it to spend development time fixing bugs for such tiny audiences?

**Comment by sorenbs** [comment]
Agree with Matt. We should actively support IE9+, and support IE8 if it is relatively easy. If we promise to support older browsers somewhere we need to update that text :-)

**Comment by starwed** [comment]
Closing due to #639.
