### ISSUE TITLE
Physics Component

### ISSUE THREAD

**Issue by louisstow** [craftyjs/Crafty#32]
Add a physics component that includes gravity and bounce and friction

**Comment by louisstow** [comment]
Too ambiguous. Will revisit later.

**Comment by ponychicken** [comment]
[This](http://www.lukewallin.co.uk/singleplayer_games/sandbox4/sandbox.php) could be useful.
It's GPL

**Comment by maxencefrenette** [comment]
I will need this kind of feature for my game. I will write and share a box2Dweb wrapper for crafty.

**Comment by louisstow** [comment]
That would be brilliant :D

**Comment by sorenbs** [comment]
Gabe Hollombe has done some box2d work https://groups.google.com/d/topic/craftyjs/bnM7_ZbjMDU/discussion

**Comment by sorenbs** [comment]
Would be cool to take advantage of webworkers when supported: http://blog.sethladd.com/2011/09/box2d-and-web-workers-for-javascript.html

**Comment by ahilles107** [comment]
@berseker59 - "I will write and share a box2Dweb wrapper for crafty." - is still actual?

**Comment by maxencefrenette** [comment]
No, sorry, it's harder than it seems =( .

**Comment by mosch** [comment]
Could try to get the Box2D into Crafty, shouldn't be too hard?
http://29a.ch/2010/4/17/box2d-2-flash-ported-javascript

**Comment by sntran** [comment]
It's not easy to make box2Dweb as a Crafty component. In box2D, there is no concept of width and height, but in Crafty, they are required to make it drawable to the canvas.

You may add '2D, Canvas' into the box2D component, but you may need to calculate the MBR, which is quite hard when dealing with polygons and such.

Also, you need a 'world' to create box2D body, which, I haven't found a way to make it work without much coupling.

Ah, what can I say, I have just started reading Crafty source code yesterday. But I believe once we have that component, integrate other Crafty components to make a full physics engine is not so hard.

**Comment by sdrib** [comment]
Is this issue closer to be solved with this component of @shogoki-vnz ?
https://github.com/shogoki-vnz/CraftyBox2D

**Comment by sorenbs** [comment]
I think we should focus our efforts on optimizing  CraftyBox2D. Hopefully @shogoki-vnz will be open to accept pull requests. When this component has matured we can take a decision on whether we should add some simple physics stuff directly into Crafty, or if CraftyBox2D is able to fulfill all needs.
Feel free to reopen this issue if you disagree.

**Comment by sdrib** [comment]
He is! I made a demo and it is already added and Peng Yu made various mods yesterday.

**Comment by sorenbs** [comment]
That's perfect! This community is just getting more awesome each day.

**Comment by glaksmono** [comment]
There is also https://code.google.com/p/jsbox2d/source/list which seems to be more maintained and up-to-date
