### ISSUE TITLE
after Crafty.pause(), an entity can't be controlled any more

### ISSUE THREAD

**Issue by neekey** [craftyjs/Crafty#322]
I have an entity which can be controlled by arrow keys to move around, but when I use Crafty.pause() to pause the game for a while and then use Crafty.pause to run the game again, the entity just can not move

**Comment by austinh** [comment]
I've experienced this too.

It's because the pause function calls .timer.stop() which triggers "CraftyStop", which unbinds events in controls.js. This makes sense, however, there is no "CraftyStart" for when things start up again. There is only "craftyLoad" for when the page loads.

**Comment by BlackScorp** [comment]
http://jsfiddle.net/5GvjW/  here the result, will be fixed in newer version

**Comment by neekey** [comment]
@BlackScorp @austinh Thank you! Hope the new version will coming soon.

**Comment by sorenbs** [comment]
I have changed this slightly so that we don't call CraftyStop when the game is paused. This is because it should be possible to unpause the game using keyboard or mouse input. As far as i can tell the mouse/keyboard dispatch is the only code that binds to CraftyStop.
