### ISSUE TITLE
Collision stops Mouse Component

### ISSUE THREAD

**Issue by austinh** [craftyjs/Crafty#326]
http://jsfiddle.net/JsbF7/13/

If entity has Collision and Mouse components, the Mouse events seemed to be suppressed.
I've looked everywhere in the source code for this.

This also happens with Collision and Draggable (as draggable uses the mouse component)

Simply remove the collision component and Mouse component works. But unfortunately, things like drag/drop might need the collision component with the mouse one.
Anyone want to help? I can't seem to find anything causing this.

**Comment by BlackScorp** [comment]
http://jsfiddle.net/JsbF7/14/  look at this.

collision has currently some bugs. 1) collision is used for the Mouse, i think it would be Better if you could define Click area in mouse component seperated from collision.
2) if you dont setup collision points, it dont take the entity MBR as collision points by default(this feature was in prev versions of crafty now its broken)

**Comment by austinh** [comment]
Thanks, adding .collision() with paremeters solved all of the problems in my game.

I figured it was something like this.

Hopefully in the next version of Crafty the MBR collision points work by default.
I also second the "defining" click area as opposed to using collision bounds. Most of the time they will be the same, but i can definitely think of some uses where I would want them to be different.

**Comment by austinh** [comment]
This seems to be fixed within the most recent commit by sorensb. :)

**Comment by starwed** [comment]
According to the comment by @austinh this is fixed?  Closing.
