### ISSUE TITLE
Document how component-entity system treats properties that are objects

### ISSUE THREAD

**Issue by austinh** [craftyjs/Crafty#327]
https://github.com/craftyjs/Crafty/issues/86 - This issue should be re-opened.

Essentially: properties initiated in a component, which is then extended when an entity is created, are all shared. this should not be the defacto behavior. It should rather be something like shared: {} which makes much more sense.

I've been searching forever to find why my SpecialPhysics component velocity and acceleration variables were applying to ALL of the entities with that component. It was because in the components themselves i was declaring the variables like this:

Crafty.c("Physics", {
accel: { x: 0, y: 1 },
velocity: {x: 2, y: 2}
});

Which meant, when i updated the a component that contained the physics, that it was all shared. This caused quite a bit of annoyance, and DAYS to debug. It wasnt until I found this thread that i found the actual variables were shared. Crafty needs a deep copy extend method. There are too many instances in gaming where this is a necessary behavior. If this wont be implemented, this should at least be in the docs.

**Comment by sorenbs** [comment]
I might take a look at this again. I got a much deeper understanding of Crafty now than i got back then.

Until then - where in the docs do you think people would be likely to see this? I have just added a small section to the Crafty.c docs that will go online in a few days.

**Comment by starwed** [comment]
This actually is documented in [Crafty.c](http://craftyjs.com/api/Crafty-c.html) now, so closing the issue.
