### ISSUE TITLE
please update demos

### ISSUE THREAD

**Issue by ch1ago** [craftyjs/Crafty#328]
https://github.com/craftyjs/Crafty/tree/master/demos/rpg

this function has been deprecated,

.animate("wind", 0, 1, 3)

can somebody please update the sources for this demo?
I hope it should be simple.

**Comment by BlackScorp** [comment]
no this function still exists also demo is correct currently

**Comment by sorenbs** [comment]
Yeah, the demos should be up to date. Ask in the forums if you need any help :-)

**Comment by ch1ago** [comment]
yeah they are, I was having cache problems, sorry I didn't close this on my own.

**Comment by ch1ago** [comment]
@BlackScorp I had downloaded the sources from the running example, where i uses version 0.4.2 :)

**Comment by sorenbs** [comment]
That is pretty old. We should fix that some day. If you feel adventurous feel free to checkout https://github.com/craftyjs/craftyjs.com and replace it with the versions on github.

**Comment by ch1ago** [comment]
oh cool,
btw, I've given a whole OO organization to that tutorial, is a change desired?
