### ISSUE TITLE
[0.5.1] Visible property not functioning properly on Dom entities.

### ISSUE THREAD

**Issue by EzraT** [craftyjs/Crafty#333]
Hello,

I noticed that in 0.5.1 the visible property doesn't work correctly on Dom entities.

Fiddle: http://jsfiddle.net/dAAsx/

It only seems to fail upon defining a new Dom entity, when you try to set it on an existing entity it works fine.

This didn't happen in 0.4.9. 

Thanks in advance.

**Comment by sbyrnes321** [comment]
This is a duplicate of issue 371 -- https://github.com/craftyjs/Crafty/issues/371

**Comment by starwed** [comment]
Closing as duplicate of 371
