### ISSUE TITLE
"text".textFont : "family" is mandatory

### ISSUE THREAD

**Issue by jmaupoux** [craftyjs/Crafty#337]
Hi,

From my multiple tests, it seems the property "family" is required on .textFont() call.
Setting a default value for this property would be great.

I suggest a "global" one where we could define a default value for the font family to use.

Tested on Firefox / Canvas - DOM

**Comment by starwed** [comment]
This is part of the CSS spec: you must set _both_ font-size and font-family when using `style.font` in this way.  Providing a default would be one fix; having the component set them individually would be another.   I'm leaning towards the second option.

_e:_ Oddly enough, you can't set them individually in canvas, so providing a default is the most sensible approach.

**Comment by starwed** [comment]
Ok, fixed by 459.
