### ISSUE TITLE
Viewport for Retina (high resolution) display on iPhone is set incorrectly

### ISSUE THREAD

**Issue by 7even11** [craftyjs/Crafty#340]
On high-resolution (326ppi and like) displays, CSS pixels are interpreted as 1px = 2 device pixels. As you cannot align anything to 1-pixel boundary the only solution is to detect display density using window.devicePixelRatio or @media CSS queries that load alternate CSS file.

When initializing CraftyJS it automatically detects mobile device and adjusts viewport accordingly - except the initialization produces side effect on Retina displays (iPhone 4, iPhone 4s, iPad 3) so that the image is doubled - this is how webkit interprets 1px to 2 actual device pixels to compensate for current images that would be too small otherwise.

So if initializing CraftyJS with:

Crafty.init(640, 960);

it actually creates a picture size 1280x1920 so only quarter is visible.

The problem can be remedied by issuing something like (after initialization):

viewport = document.querySelector("meta[name=viewport]");
viewport.setAttribute('content', 'width=device-width; initial-scale=0.5; maximum-scale=0.5; user-scalable=no;');

Other methods:
&lt;meta id="viewport" name="viewport" content="width=1024, height=768, initial-scale=0, minimum-scale=0.25" /&gt;
document.getElementById("viewport").setAttribute("content", "initial-scale=0.5; maximum-scale=0.5; user-scalable=0;");

For more see: http://stackoverflow.com/questions/3588628/can-i-change-the-viewport-meta-tag-in-mobile-safari-on-the-fly

Crafty method of resizing: Crafty.viewport.scale(0.5); does not produce any effect.

So the issue is that Crafty must do initialization properly either by utilizing window.devicePixelRatio, add additional parameter for initial scale of viewport and / or add additional function for rescaling the display.

Another solution is not to modify the scale which is set by HTML code itself (meta tag) when running on mobile instead of assuming the user didn't set proper meta tag initially.

**Comment by mpetrovic** [comment]
Could you fork the repo and come up with a solution? I don't have an iDevice I can test this on.

**Comment by 7even11** [comment]
Sorry I don't have idea what is forking a repo.

But you can test without iOS device if you are willing to do some additional effort - you need to register (for free) as Apple Developer on their site, then download XCode which comes with iOS simulator. Then open simulator and browse to website you are testing (use "retina" phone simulator). This all means you need MacOS computer or you can use Hackintosh methods - like run it virtually in VirtualBox or similar (which again requires some patching because VirtualBox cannot run MacOS out of a box - Apple doesn't allow that). But given the fact that iOS devices are well over 60% mobile share you might miss out a lot of not having a version that runs properly on them.

**Comment by starwed** [comment]
Anyone have an iPhone/etc that would let them work on a fix for this?  (Is it still an issue?)

**Comment by kevinsimper** [comment]
> Anyone have an iPhone/etc that would let them work on a fix for this? (Is it still an issue?)

It is because Crafty.js sets it to fullscreen no matter what you define, strange behavior, as seen here:

I just wrote about it here, before I saw this #663

https://github.com/craftyjs/Crafty/blob/ca1d96d825d4b37013c2b7248eba823bcb0b6d4b/src/viewport.js#L479-L480

**Comment by glaksmono** [comment]
@starwed So, here are the things that I had to do to support Retina display:

```
  Config.WIDTH = $(window).width() * 2;
  Config.HEIGHT = $(window).height() * 2;
  Config.BOX_SIZE = 30;

  Crafty.init(Config.WIDTH, Config.HEIGHT, $('#game-canvas', page)[0]);
```

and edit the viewport initialization on Crafty to:

```
        this._width = w;
        this._height = h;
```

https://github.com/craftyjs/Crafty/blob/178726feaf01a614f19dc485c237650d8fe65557/src/viewport.js#L482

Then I have to do this, after initializing the Canvas using _Crafty.canvas.init()_:

```
  $('canvas', page).css({width: '320px !important', height: '568px !important'})
```

That will give me the following final element:

```
 <div id="game-canvas" style="width: 640px; height: 1136px; overflow: hidden; position: absolute; left: 0px; top: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); background-image: url(http://localhost:8000/images/bg-1.png); background-position: -216px 0px; background-repeat: initial initial;"><div style="position: absolute; z-index: 10; -webkit-transform: scale(1, 1); left: 0px; top: 0px;"></div><canvas width="640" height="1136" style="position: absolute; left: 0px; top: 0px; width: 320px !important; height: 568px !important;"></canvas></div>
```

**Comment by kevinsimper** [comment]
@glaksmono 

> and edit the viewport initialization on Crafty to:
> 
> ```
>     this._width = w;
>     this._height = h;
> ```

This is not nessasary, since it only get the dom width and heigh IF the width and height is undefined.

Basically you make the canvas twice as large as the screen and then halfs it with css.

That is not a viable solution as you can read here:

> This also means that the following canvas element will be automatically scaled up to 640×480 hardware pixels on a retina device, when drawn on a website. Its internal resolution, however, still is 320×240.
> http://phoboslab.org/log/2012/09/drawing-pixels-is-hard

**Comment by glaksmono** [comment]
@kevinsimper ah, I actually was mistaken.. the Crafty edit should be on this one (as you specified):

https://github.com/craftyjs/Crafty/blob/ca1d96d825d4b37013c2b7248eba823bcb0b6d4b/src/viewport.js#L479-L480

**Comment by kevinsimper** [comment]
@glaksmono It has been fixed in the develop branch :) in this pull request #690 
https://github.com/craftyjs/Crafty/blob/develop/src/viewport.js#L482-L483

**Comment by glaksmono** [comment]
:+1: @kevinsimper that leaves us on how to support Retina on Canvas.. I found it much easier to use DOM to support retina, so I decided to go for that options for now

**Comment by starwed** [comment]
So... is this still an issue?  (I don't have an iOS device to test on.)

**Comment by kevinsimper** [comment]
It is not a issue anymore, it looks the same on mobile as on desktop. I just tested.

Of course there is still the issue with developing for mobile, but I think that is another problem/issue.
