### ISSUE TITLE
Documention of Crafty.sprite should mention optional tileH parameter

### ISSUE THREAD

**Issue by yhslai** [craftyjs/Crafty#341]
I surveyed the [doc](http://craftyjs.com/api/Crafty-sprite.html) but it says `Crafty.sprite` can specify only the tile size. How to specify the width AND height of tiles?

I searched in the [sprite.js](https://github.com/craftyjs/Crafty/blob/master/src/sprite.js) but it seems that `Crafty.sprite` isn't defined by it.

**Comment by thehack** [comment]
I just make all of my sprites only 1 row tall, so height is irrelevant.

**Comment by mpetrovic** [comment]
The docs need updating it seems. 

You can call .sprite() with the following signature:
    Crafty.sprite(tile, tileh, url, map, paddingX, paddingY);

Where tile is the width and tileh is the height of the sprite.

**Comment by sbyrnes321** [comment]
I improved the sprite documentation a while ago -- see 0e225069aa . The documented function signature is still a little misleading, but there is an example that specifically shows how to use the tileH parameter. So I think this issue can be closed.

**Comment by starwed** [comment]
I'll leave it open for now, since the signature should really be fixed too.  (I specifically remember that confusing me!) 

I assigned the bug to myself so I remember to get around to this, though if someone jumps in with a patch that works too.  :)
