### ISSUE TITLE
Crafty.load callbacks are not called when loading the same image on Webkit browsers

### ISSUE THREAD

**Issue by ghost** [craftyjs/Crafty#344]
For details see caveats section at: http://api.jquery.com/load-event/

If you call Crafty.load a second time with images that have already been loaded the callbacks are not called on webkit based browsers.  see http://jsfiddle.net/kFg3S/1/ for an example.

**Comment by mpetrovic** [comment]
Why should they be? The files are already loaded. Should the callbacks really be called multiple times for an image?

**Comment by ghost** [comment]
The callback is called both times in IE and Opera, but not in Chrome and Safari.  The behavior should be consistent across browsers.  You can see this behavior by browsing to the jsfiddle example above in all 4 browsers.

The issue I'm having is that I try to reload a scene, but the load callback never gets called so the scene doesn't get set up properly.

**Comment by mpetrovic** [comment]
I see. I thought people would be using it to do things to the assets, but
its more common to just do other things when the all these assets are
loaded. I'll mark it.

**Comment by ghost** [comment]
Great, thanks!

**Comment by starwed** [comment]
This was fixed by #382 in develop a while ago, I think.  Closing.
