### ISSUE TITLE
Elapsed time

### ISSUE THREAD

**Issue by tylorr** [craftyjs/Crafty#345]
In Crafty, how does one measure the amount of time in seconds since the last frame was drawn?

I want to use the elapsed time for movement logic such as:

pos = pos + speed \* elapsedTime

**Comment by mpetrovic** [comment]
The very last post in this thread details a method for doing so:
https://groups.google.com/forum/?fromgroups=#!topic/craftyjs/qtUQaDzVYAM

**Comment by tylorr** [comment]
Sorry, I am looking for the time since the last frame. I want to be able to use it for my movement logic, something like:

pos = pos + speed \* elapsedTime

I updated the issue to reflect this more clearly.

**Comment by mpetrovic** [comment]
You'll probably want to keep track of it directly. Currently Crafty doesn't have that kind of functionality.

**Comment by starwed** [comment]
Fixed.
