### ISSUE TITLE
Scaling images Android 2.3.4

### ISSUE THREAD

**Issue by tylorr** [craftyjs/Crafty#346]
I am having an issue where Crafty.viewport.scale(0.5) is not scaling images in Android 2.3.4. Is this a problem with the platform or with Crafty? 

EDIT:
Forgot to mention this is when all images use the "DOM" element.

**Comment by mpetrovic** [comment]
Does it scale images in other browsers on the phone?
Does it scale them on desktops? 
Does it scale when you go the other way with the scaling (value > 1)?

**Comment by tylorr** [comment]
I haven't tried on other browsers on phone.

It scales just fine on desktop browser in both directions (newest versions of chrome, firefox, IE)

It does not scale in either direction on my version of Android. And, when I set the background to black, it doesn't crop that either. I only see the top left region when I scale down, and nothing changes when I scale up.

**Comment by mpetrovic** [comment]
Can you put together a jsfiddle that demonstrates the issue? If jsfiddle doesn't work on the phone, then post a [gist](https://gist.github.com/) with a working test case.

**Comment by andreasbotsikas** [comment]
A contestant in our competition also reported this bug. He noticed that this appears only in android 2.x. In android 4.x scaling seems to work fine.

**Comment by starwed** [comment]
Is this present in Android 2.3.3 on?  According to google's [dashboard](http://developer.android.com/about/dashboards/index.html) we probably don't need to worry about prior versions, but about 1/3 of users are still on 2.3.3-2.3.7.

**Comment by starwed** [comment]
I found a [suggested workaround](http://uihacker.blogspot.com/2012/06/android-fix-android-2x-css-transform.html). 

Not sure if it's worth working around this bug unless it exists in more recent versions of android.

**Comment by kevinsimper** [comment]
I don't think it is worth it make custom code to make another div inside the entity, and also since Android phones on 2.3 is more or less used as "dumbphones" now and not for playing javascript html5 games. 2.3 is also under 25% now.

**Comment by starwed** [comment]
Yeah, it's actually at ~20% now.  (I think it was higher even just last month -- guess a lot of folk get new phones for xmas!  :) )

I'm going to go ahead and close this.  (If it turns out to affect later versions, we should reopen.)
