### ISSUE TITLE
Crafty selector returns IDs not Entities

### ISSUE THREAD

**Issue by tylorr** [craftyjs/Crafty#349]
If I run this command:

```
var entities = Crafty("ComponentName");
```

I would expect an array of entities, however, I receive an array of entity IDs. To retrieve the actual entity  I must call `Crafty(entities[i])` for each ID. 

The documentation states that this function returns entities, not IDs. The documentation should be changed to reflect this, or (as I would suggest) the function should be changed to return the actual entities.

**Comment by mpetrovic** [comment]
Yeah, this has been a sticking point with me for a while. The only way to get at the entities proper is to call Crafty on the integer, or call .each() on the object. Not sure what the best approach would be to rectify it though.

**Comment by starwed** [comment]
Possibly a good model would be jQuery's [`get()`](http://api.jquery.com/get/) method.  It returns an array of the actual DOM nodes; here, we could return an array of the actual components.   Calling `get` with an index could also be supported.
