### ISSUE TITLE
Setting text to 0 or ""

### ISSUE THREAD

**Issue by tylorr** [craftyjs/Crafty#351]
When passing the number 0 or the empty string "" to the text function it acts as a getter instead of a setter:

``` javascript
var t = Crafty.e('2D, DOM, Text').text("Hello");
t.text(""); // "Hello"
t.text(0); // "Hello"
```

This is because 0 (obviously) and the empty string "" (not so obviously) returns false:

``` javascript
text: function (text) {
  if (!text) return this._text;
  if (typeof(text) == "function")
    this._text = text.call(this);
  else
    this._text = text;
  this.trigger("Change");
  return this;
}
```

The 0 issue can be avoided by passing "0" or 0.toString() instead, but the empty string problem can't.

It should be something like this instead:

``` javascript
...
if (!(typeof text !== "undefined" && text !== null)) return this._text;
...
```

**Comment by mpetrovic** [comment]
could you fork and make a pull request please?

**Comment by tylorr** [comment]
Here is the [pull request](https://github.com/craftyjs/Crafty/pull/352)
