### ISSUE TITLE
Broken website links

### ISSUE THREAD

**Issue by benbarefield** [craftyjs/Crafty#359]
There are a few broken links on the crafty website:
In the documentation:
Crafty.polygon and Crafty.circle link to:
http://craftyjs.com/api/Crafty-polygon.html
http://craftyjs.com/api/Crafty-circle.html

But the current pages are:
http://craftyjs.com/api/Crafty-Polygon.html
http://craftyjs.com/api/Crafty-Circle.html

The pages should probably be updated so that the links work instead of changing the links.
Also, the github link at the bottom of the site goes to:
https://github.com/louisstow/Crafty
Which doesn't exist.

**Comment by kevinsimper** [comment]
They should make it so the community could help with the website, because I think that crafty.js could really use some help for the documentation.

**Comment by starwed** [comment]
This seems to be fixed now.
