### ISSUE TITLE
Destroy not cleaning up?

### ISSUE THREAD

**Issue by benbarefield** [craftyjs/Crafty#360]
I have a game where I'm creating and destroying a lot of entities in fairly quick succession. Destroy doesn't seem to be cleaning up completely. I may be missing something though.
My entities are destroying themselves, but I've paused in the Chrome debugger and found that some part of Crafty is still keeping around some children:
At _cascade, this.children has a length near 10000. I don't have nearly that many entities in existence, I should have somewhere in the hundreds.
this is "Crafty.fn.Crafty.init"

I've set breakpoints here and watched this number climb even though it really should be stabilizing.

**Comment by mpetrovic** [comment]
Probably a bug with an entity not knowing its children have been deleted. Should be easy to fix, since the child keeps track of its parent.

**Comment by mpetrovic** [comment]
Ready for someone to QA

**Comment by benbarefield** [comment]
I downloaded the latest code and tested with it. The performance looks better, but I seem to have found another bug.
I was planning on having the collision polygon of one of my sprites change based on which way something is facing, so every frame this.collision(new Crafty.polygon()) is being called (yes, this may be a bug in my code), but the old polygon is not being deleted, so in _cascade, the number of items in children is growing unbounded. 

Sorry that I didn't explore more fully to include this in my first post, but this may have been what was causing the problems I brought up initially. I have a few things in my game that change their collision areas based on certain state, so if .collision() isn't going to clean up the old polygon/circle, I'll need to.

**Comment by sbyrnes321** [comment]
As discussed here -- https://groups.google.com/d/msg/craftyjs/5Sj2HG1Aw2c/sCDe3aIa-K4J -- this fix created a new bug. When a parent entity is destroyed, it runs the code

```
for (var i = 0; i < this._children.length; i++) {
    if (this._children[i].destroy) {
        this._children[i].destroy();
    }
}
```

but each time a child is destroyed, it triggers Remove, which runs detach, which in turn splices the child out of parent._children. So the array is being modified while we go through it. In the simplest case, every other child would get skipped. I suggest the following modification of that for loop:

```
for (var i = 0; i < this._children.length; i++) {
    if (this._children[i].destroy) {
        // delete the child's _parent link, or else the child will splice itself out of
        // this._children while destroying itself (which messes up this for-loop iteration).
        delete this._children[i]._parent;
        this._children[i].destroy();
    }
}
```

There are many ways to correct the bug, but I think this way is sensible and robust and speedy. I haven't tested it though.

**Comment by starwed** [comment]
I merged sbyrnes patch, so I'll close this bug.  I'm trusting that the tests included in the patch actually work, let me know if not and I'll reopen.  :)
