### ISSUE TITLE
Remove Component

### ISSUE THREAD

**Issue by benbarefield** [craftyjs/Crafty#366]
I have a suggestion that should be pretty easy to implement for removeComponent. When you call addComponent, init is called on the component if it has it. It would be nice if remove component had a similar method, so that any bindings done in init could be undone after remove.

**Comment by mpetrovic** [comment]
We have a RemoveComponent event that can be used to clean up a component's
bindings.

**Comment by benbarefield** [comment]
Oh, sorry. It's not at the documentation of the removeComponent method. Didn't think to look in the events.
