### ISSUE TITLE
init alpha to 0

### ISSUE THREAD

**Issue by benbarefield** [craftyjs/Crafty#371]
There's a bug in draw regarding alpha, visibility, and probably other properties due to falsey.
Currently, the alpha code is:
if (this._cssStyles.opacity != this._alpha)
If you set alpha to 0 before the first draw call (in init), this will result in true without setting the cssstyle to 0 because the cssstyle will be "" which is == to 0. This line should read:
if (this._cssStyles.opacity !== this._alpha)

I've tested this and it fixed the issue. I've seen the same problem with visibility. I didn't go through all the properties in draw, but I imagine some other properties could run into this same problem.

**Comment by mpetrovic** [comment]
I'm trusting you that this fixes it. With no reproduction code, its kinda difficult to test here.

**Comment by benbarefield** [comment]
Sorry, I can include some, though it seems it's too late:
Crafty.e("2D, DOM, SomeSprite").attr({ x: 5, y: 5, alpha: 0});
Crafty.e("2D, DOM, SomeSprite").attr({ x: 5, y: 5, visible: false });
Both of these should result in nothing actually being drawn, but before your commit they would be shown.

**Comment by sbyrnes321** [comment]
I also noticed the bug where visible:false fails when it's an initial property, and I also noticed that !== fixes it. I was going to suggest it myself, when I saw it had already been done (since the last release). Nice job!

**Comment by starwed** [comment]
This was fixed, yes?

**Comment by sbyrnes321** [comment]
Yes, this was definitely fixed by d2924be.
