### ISSUE TITLE
Empty variable declaration Crafty.stage.inner.style['transform'] =

### ISSUE THREAD

**Issue by kevinsimper** [craftyjs/Crafty#374]
On line 4940 is an empty declaration.

```
 Crafty.stage.inner.style['transform'] = 
```

It gives an error.

```
Uncaught TypeError: Cannot read property 'inner' of undefined 
```

Here is a jsfiddle where the problem is also occuring
http://jsfiddle.net/bsGHJ/1/

**Comment by mpetrovic** [comment]
You didn't call Crafty.init(). The declaration isn't empty, it's on the next line.

**Comment by kevinsimper** [comment]
Thank you, and sorry for such a stupid mistake!

I was following a tutorial, but i missed that they had moved the init line away from the tutorial to another file.
