### ISSUE TITLE
NewComponent Event

### ISSUE THREAD

**Issue by benbarefield** [craftyjs/Crafty#375]
The documentation says the NewComponent event will be fired with the name of the new component being added. Currently it is being fire with the number of components being added. 
I changed my local version so that the loop that extends the component list for the entity fires NewComponent with each component it is adding, after calling init. This behaves the way I would have expected.

**Comment by mpetrovic** [comment]
For efficiency's sake, I passed the list of components added instead of just one. You'll need to check the array for the one you want.

**Comment by starwed** [comment]
This is basically fixed by the referenced commit.
