### ISSUE TITLE
Isometric Demo using Canvas

### ISSUE THREAD

**Issue by ondrajz** [craftyjs/Crafty#384]
I tried to edit the isometric demo you provide to use Canvas instead of DOM elements. It works okay till I change the zoom of the page then it messes up and even changing the zoom to default doesn't help. I am unsure why this is happening since I just started with Crafty.

I am using Chrome Version 23.0.1271.95 m

**Comment by starwed** [comment]
I can't reproduce this issue, so closing.  Feel free to reopen if it is still an issue in the current version of Crafty!
