### ISSUE TITLE
CSS white letters on white background on craftyjs.com

### ISSUE THREAD

**Issue by redexp** [craftyjs/Crafty#386]
All code examples on your site is on white background, I think it should be black, isn't it?

It's on line 98 of global.css
pre code {background-color: whiteSmoke;

Sorry if github is wrong place for site issues.

**Comment by starwed** [comment]
There's already [an issue](https://github.com/craftyjs/craftyjs.com/issues/4) for this in the website's own repo.  No worries about reporting it here! 

So, closing this one.
