### ISSUE TITLE
Craftyjs repositories need explanation.

### ISSUE THREAD

**Issue by merriam** [craftyjs/Crafty#392]
There are four repositories in the CraftyJS project, and each should have a list of the purpose of each repository.  Use this one:  https://gist.github.com/4342298

**Comment by merriam** [comment]
This is repositorylist.md:

---

layout: default

## title: Repository List

# The Repository List

There are several repositories hosted on GitHub under the [craftyjs project](https://github.com/craftyjs):
- [craftyjs.github.com](https://github.com/craftyjs/craftyjs.github.com):  A development section for [craftyjs.com](http://craftyjs.com).  It is updated frequently; it is [the suggested fork](http://craftyjs.com/tutorial/) on the webpage; it contains more files including nonworking demos.  These are the files on the [homepage](http://craftyjs.com). 
- [Crafty](https://github.com/craftyjs/Crafty):  A development section for the library.  It is pointed to for release notes from the [homepage](http://craftyjs.com) and by [CraftyComponents](http://craftycomponents.com); it has the issues ([bug list](https://github.com/craftyjs/Crafty/issues)); it has the most forks; it has the crafty.js broken into seperate files with tools for reassembling.  It does have a copy of some demos and the api code.  
- [craftyjs.com](https://github.com/craftyjs/craftyjs.com):  Another copy of the website, with an index.php.  Does not appear to be frequently updated and may be inactive.
- [CraftyComponents](https://github.com/craftyjs/CraftyComponents):  Web page file for [CraftyComponents](http://craftycomponents.com) which features a lots of snippets (or fiddles) of code, links to FlexPi, and other add-ons.

**Comment by starwed** [comment]
Copied the markdown file [into the wiki](https://github.com/craftyjs/Crafty/wiki/Repositories-Explained).
