### ISSUE TITLE
HTML5 Audio issues

### ISSUE THREAD

**Issue by a-zb** [craftyjs/Crafty#4]
Pull requested.

In reference to this: http://stackoverflow.com/questions/4435009/html5-audio-plays-randomly

I know that short audio clips ( less than about 0.5 second ) have trouble playing in <audio> tags. Unfortunately, the some browsers deal with this better than others. My suggestion is this:

Always use sounds bytes that are longer than that length by padding a short clip at the end with silence. So a 0.1s shoot file, become 0.1s shoot + 0.5s of silence. It should work.  I added a shoot.ogg that is a little longer than original.

Additionally, if we use only one instance of an audio clip per sound effect, we would have to rewind to the beginning of the sound and play it again if we want to press twice fast. 
Triggering audio.play() while a sound is currently playing will not rewind+play automatically.

There are other approaches, but this one at least makes the elevator demo handle "shoot" better. Before my patch, the audio would not be handled well by Chrome 8,9,10 on OSX or
Linux. FF3.6 would also skip sometimes.

Demo : http://loccaro.com/elevatoraction/index.html

TODO: Investigate creating multiple sounds from one sound effect and play all simultaneously.

**Comment by louisstow** [comment]
Nice work. I have noticed however that some longer sounds (like when shooting the light) do not play. Also is there anyway we can add silence dynamically or would developers have to do it themself?

**Comment by a-zb** [comment]
Hmm, I didn't look at the light sound effect, good point. It might be another unrelated thing. Was it playing before, I don't remember it.

Dynamically padding sounds might be tricky and I thought of that as well. If we need it, then we'll come up with a way. I'll do more research to see how that can be done.

**Comment by louisstow** [comment]
Closing this because it is a problem with browsers and there is no real solution.
