### ISSUE TITLE
Non-Existant CDN cdn.crafty-modules.com

### ISSUE THREAD

**Issue by cawoodm** [craftyjs/Crafty#415]
Example here: http://craftycomponents.com/components/single/9/moveto
which references: http://cdn.crafty-modules.com/moveto-RELEASE.js
from crafty-SNAPSHOT.js/6329

Perhaps it should instead reference this?
http://cdn.craftycomponents.com/moveto-release.js

**Comment by starwed** [comment]
I don't see the claimed code on the linked page.  I'm going to close this for now, but reopen if I'm misunderstanding!  :)
