### ISSUE TITLE
DOM vs. Canvas element height

### ISSUE THREAD

**Issue by benbarefield** [craftyjs/Crafty#453]
I'm not sure this would be considered a bug or not, but it isn't behavior I expected
I had a sprite sheet with two different height sprites (25 px and 75 px).
If I did something like this:

``` javascript
Crafty.sprite(25, "MySprite.png", { MySprite : [0, 0] });
...
var thing = Crafty.e("2D, DOM, MySprite, SpriteAnimation")
   .animate("One", 0, 0, 9)
   .animate("Two", 0, 1,9);
...
thing.animate("One", 30, 0);
...
thing.h = 75;
thing.animate("Two", 30, 0);
```

I would see both animations properly. When animation "One" was playing, it would grab a 25x25 pixel frame from the sprite sheet as expected. When animation "Two" is playing, it grabs a 25x75 pixel section from the sprite sheet and plays the 10 frames, also as expected.
If this same code is used, but "DOM" is replaced by "Canvas" in the element creation, the behavior changes. When animation "Two" is playing, the element still becomes 75 pixels tall, but it only grabs a 25x25 pixel section from the sprite sheet and stretches it to fit in the 25x75 pixel element.

**Comment by starwed** [comment]
I think this is kind of related to #423, isn't it?  In the current release, sprites don't scale for DOM elements, while on the canvas it does.

I think that if you specify a certain region of the sprite sheet as `MySprite`, associate it with an element, and then change the height of that element, the _correct_ thing to do is scale the sprite.  So the incorrect behavior is what happens to the DOM, which I think I know how to fix.  (See #460.)

Is there any good use case for the behavior you expected?

**Comment by benbarefield** [comment]
Could be related, I'm not sure, and you're probably right that the proper thing would be for it to scale. I was using this behavior, but there are ways around it. 
I posted the bug mostly because it was inconsistent behavior.

**Comment by starwed** [comment]
Yeah, the inconsistent behavior is definitely a bug!  I'll use #460 to track this issue, and close this one.
