### ISSUE TITLE
Unit tests reveal many problems with IE8 (or at least, IE10 in "IE8 mode")

### ISSUE THREAD

**Issue by sbyrnes321** [craftyjs/Crafty#456]
Well, I have Windows 7, so I can't install IE8. but I can use IE10 with browser mode set to IE8 mode. Maybe someone else will check this with the real IE8.

When I take the latest crafty with the latest "core.html" unit-tests, they pass in firefox, chrome, IE10, and "IE10 in IE9 mode". (Except for the SAT test at the bottom, which always fails, probably the test is out-of-date.)

But for "IE10 in IE8 mode", many of the tests fail.
- The "All components - universal selector" test: "Expected: 7  Result: 8"
- The "CORE: setter" set of tests: "Died on test #1 undefined: Unable to get property 'push' of undefined or null reference"
- The "2D: position" tests: All of them fail except #5.
- The "2D: Intersect" tests 1 and 2 are failing ("Expected: true  Result: false")
- The "2D: child" tests 1-3 are failing (1. "Expected: 51 Result: 0". 2. "Expected: 52 Result: 0" "3. Expected: 50 Result: 0."
- The "2D: child_rotate" tests 2 and 4 are failing (2. "Expected: 35 Result: 15" 4. "Expected: 57 Result: 37")

Many of these, but not all, seem to come from the use of "+=" setters like entity.x += 5, which all seem not to work in IE8 mode. (I could be wrong.)

**Comment by mpetrovic** [comment]
if += doesn't work in IE8, that is a huuuuuge problem.

**Comment by sbyrnes321** [comment]
I further investigated core.html in IE8. So far, I haven't found "real" problems, only problems with the tests.
- `Crafty('*').length` is different in IE8 because there's a special entity (search for `ViewportSetter`) which only exists to update the viewport each frame. (This is a workaround to the lack of getter/setters.) For the same reason `Crafty('*').destroy()` should maybe be avoided. (There's nothing wrong with this, although in my mind it would be simpler to create a global event binding instead of a special entity.)
- Any test like `this.x = 5; console.log(this._x === 5)` will fail in IE8 because of the different getter/setter behavior. It should be modified to `this.x = 5; Crafty.trigger('EnterFrame'); console.log(this._x === 5);` This problem explains most or maybe all of the `2D` tests failing.
- The `this.setter()` method has one behavior when `Crafty.support.setter` or `Crafty.support.defineProperty` is true, and a quite different behavior when both are false (i.e. IE8). The "setter" test expects to see the former behavior, so it fails in IE8.

I hope to edit the tests when I get a chance, because maybe there are legitimate problems in addition to these false positives. For what it's worth, I made a simple few-line script that draws and resizes a box, and it DOES work in IE8.

[Addendum (slightly off-topic): `Crafty.init()` is run twice in core.html. This causes a problem in IE10.]

**Comment by starwed** [comment]
I wonder if it would be better to have a separate "Set" event that triggers after each frame if the current environment lacks setters?  Presumably the way things are now, the `x` and `_x` type properties sync up in an essentially arbitrary order, and there's no guarantee that they're the same after the frame has finished.

This would then let you trigger the process independently of "EnterFrame", which seems like it would be useful for testing.

Maybe I'm misunderstanding how this works in legacy browsers, though?

**Comment by sbyrnes321** [comment]
I just put in a pull request #553. It fixes the false-positives, but some of the unit tests fail for good reason.
- For "modern" browsers, there is an algorithm to set globalZ based on the entity ID number and the z property, mixing those two together. `this._globalZ = parseInt(value + Crafty.zeroFill(this[0], 5), 10);` It seems that this algorithm is not used at all in IE8.
- Rotating a parent in IE8 does not rotate the child.
- There are some IE8 problems that I haven't looked into, relating to disableControl and enableControl, and the rotation / resizing / etc. of hitboxes and/or 2D polygons.

@starwed -- Your idea sounds reasonable on its face. But I think that getting the IE8 behavior to exactly match the IE9+ / chrome / etc. behavior in all reasonable situations is impossible. I could be wrong ... But I hope you don't waste too much time on it. (Unless of course you are personally invested, or people are complaining.)

**Comment by starwed** [comment]
The more I think about it, the more the way of dealing with a lack of setters/getters seems like it couldn't possibly work.

The fallback method assumes that if `_x` and `x` are different, that `x` has the correct value.  But there are many places internally where we directly modify the `_x` type properties!  Which means that the fallback method will then revert these to their previous value.

This might be what is happening with the rotation, for instance -- the parent entity will call `cascade()`, which will set the `._rotation` attribute on the child directly.  Then `_defineGetterSetter_fallback` would set it back to the `.rotation` attribute the next time it triggers.

**Comment by sbyrnes321** [comment]
My assessment is that: Certain simple games might still kinda work in IE8 today, but you would have to be lucky to avoid encountering any bugs.

Eventually there will either be an official decision to stop supporting IE8, or someone will volunteer to spend a lot of time figuring out how to get IE8 working reasonably well.

I think the former is more likely, unless a new volunteer appears. (It won't be me! I don't want to spend any more time thinking about debugging IE8 support.)

**Comment by kevinsimper** [comment]
Does it say anywhere that we support ie8? I do not think the added complexity is worth the trouble for a browser that is on it way out.

**Comment by sbyrnes321** [comment]
I thought there was something that said IE8 was supported, but now I can't find it. Maybe I'm not remembering right. But it's clear that it was supported at one point, because there's a lot of code in crafty to make IE8 work. I don't think that there has ever a definitive decision to end IE8 support. Instead, IE8 has just gradually been accumulating bugs.

If you want to propose DEFINITIVELY ending IE8 support -- including deleting the IE8-specific code throughout the codebase -- I think I would be in favor of that. ...But that's just my personal opinion.

**Comment by starwed** [comment]
Closing due to #639.
