### ISSUE TITLE
Crafty.viewport.bounds being amended

### ISSUE THREAD

**Issue by Avvio** [craftyjs/Crafty#457]
If you set your own custom bounds on the Crafty.viewport it's being changed on the original object every time _clamp is called, which in our case is whenever a 2d sprite moves because we are following it.

If the _clamp function is amended to read the same as below it would work.

```
        var bound;
        if (this.bounds) {
            bound = {
                max: {
                    x: this.bounds.max.x,
                    y: this.bounds.max.y
                },
                min: {
                    x: this.bounds.min.x,
                    y: this.bounds.min.y
                }
            }
        } else {
            bound = Crafty.map.boundaries();
        }
```

This is a bit too verbose really, some sort of deep clone would look cleaner and avoid the original object being modified.

Sorry I haven't given an example with code, I will in a few days hopefully.

**Comment by mpetrovic** [comment]
Why are you setting your own bounds?

**Comment by Avvio** [comment]
The function Crafty.map.boundaries() wasn't correctly calculating the size of our map. We're short on time so rather than try to work out why it was mis-calculating we decided to set the bounds. It's in the documentation and the code clearly shows that you're able to use it. Otherwise what's the point of the line below within _clamp:

``` javascript
var bound = this.bounds || Crafty.map.boundaries();
```

**Comment by Avvio** [comment]
Oh and we're using the isometric map.

**Comment by starwed** [comment]
Oh, this should be easy to fix in a different way.  The problem is that some code needlessly modifies the bounds object:

``` javascript
bound.max.x -= Crafty.viewport.width;
if (Crafty.viewport.x < -bound.max.x) 
    Crafty.viewport.x = -bound.max.x;
```

I think the following would be both easier to read and wouldn't mess with the bounds object:

``` javascript
if (Crafty.viewport.x < -( bound.max.x + Crafty.viewport.width )  )
    Crafty.viewport.x = - ( bound.max.x  + Crafty.viewport.width );
```

(And the same for `y`.)  I'll submit a patch for this shortly.

**Comment by ashes999** [comment]
Setting your own bounds is incredibly useful. This should be documented somewhere. In games with tons of entities, it's a great work-around for poor performance.
