### ISSUE TITLE
Crafty.sprite() is currently broken for DOM sprites created from spritesheets

### ISSUE THREAD

**Issue by zipang** [craftyjs/Crafty#460]
The culprit is the CSS rule `background-size: cover;` introduced in pull request 423. 
(Note : _the bug is only present at the moment in branch master and release 0.5.3 is not affected_)
See my comment in the discussion : https://github.com/craftyjs/Crafty/pull/423

This technique could still be used on sprites created from a single image.

There is still a lot of dicussion on how to achieve this on sprites extracted from spritesheets : 
http://stackoverflow.com/questions/2430206/how-can-i-scale-an-image-in-a-css-sprite

**Comment by starwed** [comment]
Ok, when we merge master and develop again, we'll just leave out the change that caused the breakage.  Lets use this issue to track fixing the fundamental problem -- different scaling behavior for DOM and Canvas sprites.

**Comment by nmfm** [comment]
I think this is also present on 0.5.3

**Comment by starwed** [comment]
@nmfm 0.5.3 is the currently released version that's been out for about half a year.  I haven't heard any reports of sprites being broken; are you sure you're looking at this issue on 0.5.3?

**Comment by EntropyFails** [comment]
I have had this problem on v0.5.3. I've had to comment out the line in order to get sprite() to work with spritesheets.

**Comment by starwed** [comment]
@EntropyFails  What line?  The change discussed here was not in 0.5.3.

Also, 0.5.4 is the current version now.

**Comment by zipang** [comment]
Well i think that EntropyFails like me did try to use the code in the master branch. 
I knew that there had been a 0.5.4 release downloadable from http://craftyjs.com/ and i had a hard time this morning trying to find it in the master branch (untill i noticed the 'release' branch)
The bug still lies inside the master branch. It's very confusing.

https://github.com/cawoodm/Crafty/commit/fe1460ff3f7d9f2a5290b09ca4c3c83dbd015ed7

**Comment by starwed** [comment]
@zipang Some commits were accidentally accepted into master that should have landed in develop; one of them caused this bug.  We'll probably eventually want to just delete the branch named master to avoid confusion. 

Anyway, the root problem of sprites not scaling should be fixed by #507, in a way that _hopefully_ doesn't break anything else.  :)
