### ISSUE TITLE
PHP warnings while running build-api.php

### ISSUE THREAD

**Issue by sbyrnes321** [craftyjs/Crafty#475]
Whenever I run build-api.php, I get the following notification:

"PHP Notice:  Undefined offset: 1 in /home/.../build/build-api.php on line 61"

The same message is printed ~40 times consecutively.

But the overall operation seems successful, insofar as I wind up with documentation that looks OK. Can the warning be ignored? Or is it a sign of a problem?

(I have no experience with PHP, so I can't help here.)

**Comment by starwed** [comment]
Hmm, I do not see any errors on a Mac running 10.6.

The PHP version is `PHP 5.3.15 (cli) (built: Jul 31 2012 18:42:11)`

I likewise have no experience with PHP.

**Comment by sbyrnes321** [comment]
OK, I was using `PHP 5.4.6-1ubuntu1.2 (cli) (built: Mar 11 2013 14:57:54)`. It does seem like there were [changes in the defaults for giving notices and warnings](http://us3.php.net/manual/en/migration54.incompatible.php) between php5.3 and php5.4.

So I guess that this is probably not a "real" problem -- just a change in php to be more vocal with warnings. But still, we should wait for a php expert to check it out, and ideally change the php code so that it doesn't emit these notices. :-D

**Comment by kevzettler** [comment]
This gives more incentive for #472 getting any PHP dependency out and keeping the code base all Javascript seems like a win.
