### ISSUE TITLE
Event for end of frame

### ISSUE THREAD

**Issue by phosphoer** [craftyjs/Crafty#478]
I'm implementing basic collision resolution for aligned boxes, and have run into the following problem:

My object applies its movement vector to its position on the `EnterFrame` event. It responds to the `onHit` message from the `Collision` component to perform collision resolution. Unfortunately, it seems that `EnterFrame` occurs after the collision message is sent, so the collision is resolved, but then right before drawing the object moves back into its original position, slightly penetrating the solid object.

Am I missing the proper way of implementing the behavior I want? (I just picked up Crafty the other day). If not, I was able to solve my problem by modifying Crafty to trigger an "ExitFrame" event right after the draw call, which I think is a useful addition.

**Comment by starwed** [comment]
I've been thinking about adding something like this; things like `PostFrame` and `PreDraw` events might be useful.  Adding more hooks and timing info into the main game loop would probably be a good thing.

> I was able to solve my problem by modifying Crafty to trigger an "ExitFrame" event right after the draw call

Careful with this; the number of "EnterFrame" events per "Draw" is not necessarily constant.  Also,  you can absolutely resolve collision events as they occur without getting any overlaps.  A post frame event would be really useful if you want to handle physics in a nicer way, but simple collision testing should still work fine with the current events.
