### ISSUE TITLE
"Change" event overused and overloaded

### ISSUE THREAD

**Issue by starwed** [craftyjs/Crafty#482]
Every time you use `attr()`, a change event is triggered.  It is handed a map of property names and their new values.

When you assign any of the 2D properties (x, y, w, h, rotation) a change event is also triggered.  In this case, it is handed an object representing the object's _previous_ state.

If you use `attr` to set a 2D property, both will be triggered.

There are two places in Crafty that are bound to this event
- 2D entities need "Change" to know when they need to be redrawn.  The current code doesn't need to be told what the old state was (that's tracked by the drawing routine now).  This was the consumer of the second type of event, which could maybe be replaced by something like "VisibleChange"?
- The viewport.follow function uses "Change" to know when to follow an object.  It likewise doesn't care what object the handler gets.

If anyone tries to consume "Change" events currently they'll be confused by the two types, so we need to clear this up!

**Comment by starwed** [comment]
I propose using an event called `"Invalidate"` to mark when an object needs to be redrawn.  That (somewhat) matches the same concept in Flash and Android environments.  It wouldn't be passed any data -- the object itself will contain all information necessary to draw itself.

`"Change"` could then be used to indicate that some property of the entity had changed.  It could be triggered by anything that functioned like a setter.  I don't think this would need to be used internally in crafty at all -- the one use by `viewport.follow` could just be tied to the `"Moved"` event.  

Thoughts?

**Comment by grozen** [comment]
Sounds like a most blessed fix.
