### ISSUE TITLE
Issue with _cascade and rotated MBRs when resizing entities

### ISSUE THREAD

**Issue by starwed** [craftyjs/Crafty#488]
After I landed my resize patch #485, I realised there's a problematic interaction with cascade.

If a rotated entity's dimensions are changed, that can change the (x,y) of the MBR.  But this probably _shouldn't_ mean that any attached entities should shift along with the MBR, like _cascade seems to think.  That should only happen on an actual move.

More generally it would be nice if _cascade didn't rely on being passed a copy of the old entity; maybe just being passed the specific change would work better.  That would make it simpler to reason about.  Normally cascade is invoked separately for each change in attributes, but maybe there's some place I've missed where it's called all at once?

**Comment by mpetrovic** [comment]
No, it should. cascade is for grouping entities together so they behave as
one. Any attached entities should rotate around the parent's center. We may
need to have a separate method for rotating just the parent, but if that's
what you're trying to do, you're probably thinking about attachment the
wrong way.

**Comment by starwed** [comment]
Hmm, I disagree.  There are three ways the position of the MBR changes: translation, rotation, and scaling.  Currently, if I rotate an object and then increase its height, that can move the MBR to the left.  I don't think attached entities should move in that scenario.

Note that there was a bug in how MBRs were recalculated for resized, rotated objects; this wasn't an issue until that bug was fixed.

Here's a quick illustration of this case, where the MBR will shift to the left on both rotation and change in height.

![mbr example](https://f.cloud.github.com/assets/34907/642677/9d63cbd6-d363-11e2-8c64-0d908126ecef.png)

Currently the green ball would be moved directly to the left in the final step, as `_mbr._x` would change and the attached entity would follow along with it.

An attached object should follow an entity when it moves, and rotate about an entity's origin when it does.  Neither of those requires knowing the parent object's MBR; it's enough to simply know it's position, origin, and rotation.

This could be fixed by (a) not _cascading on a resize, or (b) _cascading based on the objects position, rather than the position of its MBR.

**Comment by starwed** [comment]
Should now be fixed.
