### ISSUE TITLE
CSS line-height property cannot be set for entities with Text component

### ISSUE THREAD

**Issue by mccutcheonk** [craftyjs/Crafty#494]
As of v0.5.4, setting the CSS `line-height` (or `lineHeight`) property has no effect for DOM entities with the Text component. The value of the line-height property is clobbered when the style's font is set in the Draw callback of the Text component (src/text.js:47).

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/font), line-height is a component of the font property. When the font property is set, but no line-height is specified, the line-height will default to `normal`. As such, it seems as though the only correct fix for the current system is to allow line-height to be specified using the `.textFont` method of the Text component, and have it incorporated in the font when it is set.

I'll prepare a pull request as soon as I can. If Im missing something here, please let me know.

**Comment by edgars-vasiljevs** [comment]
I had the same problem and I found a workaround for this bug without any changes to the framework.

``` javascript
.textFont({ size: '14px/1.3' })
```

This sets `font-size` to `14px` and `line-height` to `1.3`

I hope this will help.
