### ISSUE TITLE
Preloading sounds doesn't work

### ISSUE THREAD

**Issue by mauricesvay** [craftyjs/Crafty#502]
It seems that preloading sounds doesn't work :
- Preloader requires Crafty.support.audio and Crafty.audio.supported[ext] to be true to load a sound
- Crafty.audio.supported is populated by Crafty.audio.canPlay
- Crafty.audio.canPlay is only called by Crafty.audio.add

From what I understand, sounds can not be preloaded unless Crafty.audio.add is called once.
Let me know if I missed something.

**Comment by mauricesvay** [comment]
I'm using Crafty 0.5.4 for reference.

**Comment by starwed** [comment]
You're totally right!  Luckily, this should already be fixed in the current develop branch.  (By #487)

A work around in 0.5.4 is to call `Crafty.audio.canPlay()` before loading sounds.
