### ISSUE TITLE
Only using Grunt for building?

### ISSUE THREAD

**Issue by kevinsimper** [craftyjs/Crafty#517]
Wouldn't it be a good idea only using Grunt for the build process? Right now the files are manuelly written in the build-crafty.php, but imported automatic in the grunt build process from package.json

**Comment by starwed** [comment]
I don't want to remove the php builder yet -- it works, and if you have php installed I think they have less dependencies.  I'd also like someone to confirm that the grunt process works on windows.

But yeah, in the future I'd hope to kick the php process out.

**Comment by ericathegreat** [comment]
FYI, I'm running on Windows and Grunt seems to work fine for me. It's also less involved than getting PHP installed and running.

**Comment by kevinsimper** [comment]
Fixed in #568
