### ISSUE TITLE
Keyboard keys get stuck.

### ISSUE THREAD

**Issue by ponychicken** [craftyjs/Crafty#53]
Crafty relies on the onkeyup call. If I switch tabs while using the arrows/whatever keys, the player object continues to move until i press&depress the same key again.

It might be better to instead attach a onkeypress to the document.documentElement (not window for crossbrowser compat)

**Comment by arthurschreiber** [comment]
That won't actually help. The controls component lets you check whether keys are pressed or not, and that won't work anymore with the keypress event.

The best solution (for singleplayer games at least) would be to attach an event handler for the blur event to the window object, so you can stop the game if the user switches tabs.

**Comment by louisstow** [comment]
That's a great idea! Will do.

Maybe I should add a `Crafty.pause()` method that will stop the enterframe and trigger a `pause` event. This can then be called on window blur.

**Comment by ponychicken** [comment]
Done. This probably fixes the performance problems in inactive tabs as well

**Comment by ponychicken** [comment]
afd8d54e6d18dbb8233fb2a89de10d5319f70dee
