### ISSUE TITLE
Crafty.load requires at least one image

### ISSUE THREAD

**Issue by wgmyers** [craftyjs/Crafty#531]
Crafty.load() - in 0.5.4 at least - requires at least one image in order to work. It should not do so.

The following code snippet (in a 'Loading' scene) works:

```
// Loading code will go here
Crafty.load(['assets/null.gif'],
    function() {
        Crafty.scene('Start');
    }
) 
```

It even works if null.gif is a 0 byte file. The following does not: 

```
// Loading code will go here
Crafty.load([],
    function() {
        Crafty.scene('Start');
    }
) 
```

:(

Workaround - if you want to load audio and have no images to load, make a dummy image file and 'load' that first.

**Comment by starwed** [comment]
This should already be fixed in the development branch: can you double check in [one of the testing releases](https://github.com/craftyjs/Crafty/releases)?

**Comment by wgmyers** [comment]
Honestly? I will gladly do so when Ludum Dare is over. Been using crafty.js 0.5.4 - it's great, really easy to learn and use and thank you so much for it - but at the same time I really don't want to mess about with 0.6 right now in case anything else breaks. For now I just want to get my game halfway decent and working and upload it and go to bed already :) It has been a ridiculously long night and is now 7.20am where I am. Still some way to go.

Tomorrow I will happily test the 0.6 build for you :) Please feel free to give me a nudge if I don't.

**Comment by kevinsimper** [comment]
@wgmyers Have you have time to test it yet?

**Comment by starwed** [comment]
I'm going to go ahead and close this -- the bug should be fixed, I just wanted to make sure wgmyers hadn't run into a different issue somehow.
