### ISSUE TITLE
JSHint on Crafty

### ISSUE THREAD

**Issue by kevinsimper** [craftyjs/Crafty#539]
If you run the `grunt check`, the JSHint tool is also run on Crafty.js, but returns a lot of errors.

Is it something that should be enforced?

There is around 200 errors right now.

**Comment by sbyrnes321** [comment]
"Enforced" is unnecessary (and makes newcomers have to jump through more hoops). But it's useful as a list of things that ought to be fixed when someone gets around to it. Things like inserting missing semicolons and rationalized whitespace would be nice (there is a [style guide](https://github.com/craftyjs/Crafty/wiki/Style-Guide) that has long been ignored).

I think I'll fix the jshint errors if I'm ever very bored, but it hasn't happened yet. (I guess I would skip the files where there are pending pull-requests, to avoid merge conflicts).

**Comment by kevinsimper** [comment]
Okay, yes, that sound like the right way :)

**Comment by kenany** [comment]
@potomak is fixing this at #556.

**Comment by kevinsimper** [comment]
Fixed in pull requests.

**Comment by starwed** [comment]
There are actually still a couple of things we should fix (unless I missed a pull request!) so reopening.
