### ISSUE TITLE
Add Travis-ci for continuous integration

### ISSUE THREAD

**Issue by kevinsimper** [craftyjs/Crafty#540]
The repo owner needs to enable Travis-ci integration.

**Comment by kevinsimper** [comment]
![screen shot 2013-09-04 at 13 22 44](https://f.cloud.github.com/assets/1126497/1079874/60aed036-1554-11e3-9a79-c782bd8d9d47.png)

Somebody with admin access has to go to travis-ci.org and activate the service, before it will work.

@louisstow, can you do that? :-)

**Comment by kevinsimper** [comment]
If we added Travis, we could build the crafty.js development source file. Sometimes users report bugs, that we think has been solved, so we ask the user to try it with the latest build. This way we could save a lot of time with bugs.

Normal users who are getting started with Crafty.js, do not know how to build crafty.js dev, without using a lot of time figuring it out.

Lately also many tests has been added or fixed by @sbyrnes321 , so it would be cool to have them ran, whenever a Pull-request is submitted.

**Comment by potomak** [comment]
I think we should also add also the support for running tests using http://ci.testling.com/, some work is required, I'll open a related issue soon.

**Comment by potomak** [comment]
Note: I can't still find any build at https://travis-ci.org/craftyjs/Crafty

**Comment by starwed** [comment]
Someone (@louisstow?)  seems to have flipped the right switch, because I'm now seeing Travis messages integrated into pull requests.

**Comment by kevinsimper** [comment]
No, it is because I have added it to my crafty fork, so on all my pull requests there will be travis-ci messages.

So we still need Louis to add Travis-ci.

**Comment by starwed** [comment]
Aha.  It does seem like this would be quite useful.

**Comment by kevinsimper** [comment]
Yes, very useful, especially on pull request from new people.

**Comment by starwed** [comment]
@louisstow  Could you comment on this?  Even if it's just to say you don't have time to think about the issue right now.  :)

**Comment by starwed** [comment]
Ok, louis added me as an owner, and I enabled travisCI.  It seems to be working -- I got emails about the last two builds passing, any way.

**Comment by kevinsimper** [comment]
@starwed That is really great! Could you enable testling.com also? :)
