### ISSUE TITLE
Animation End Event does not return correct reelID

### ISSUE THREAD

**Issue by steffmeister** [craftyjs/Crafty#541]
Hi,

I think there's an error in the updateSprite function of SpriteAnimation. In line 7304 it says:

```
this.trigger("AnimationEnd", { reel: data.currentReel });
```

which would return eg {"reel":[[0,128],[32,128],[64,128],[96,128]]} 

but shouldn't it be

```
this.trigger("AnimationEnd", { this._currentReelId: data.currentReel });
```

or likewise to return the correct reel Id eg "PlayerRunning"?

I have some working code (some kind of project where I am experiencing this problem) if needed.

**Comment by starwed** [comment]
I think you are looking at the last release.  SpriteAnimation was refactored significantly in the develop branch, so this issue is likely moot?

**Comment by steffmeister** [comment]
Yes you are right. Sorry. This issue can be closed.
