### ISSUE TITLE
Crashing after inactivity

### ISSUE THREAD

**Issue by louisstow** [craftyjs/Crafty#56]
Reports that Crafty crashes when left alone for a few minutes. Becomes very slow to reload when changing tabs.

**Comment by ponychicken** [comment]
Still reproducible with Crafty.pause().
Opened game in 5 tabs, then switched to another non-game tab.
After 10min tabs needed 30sec on a quadcore to recover

**Comment by louisstow** [comment]
I have a feeling it's `requestAnimationFrame`. Maybe we could try stopping it like in `Crafty.stop`.

**Comment by ponychicken** [comment]
Me too. I testing now, whether stopping that helps

**Comment by louisstow** [comment]
In which case we should maybe introduce a `Crafty.start` method with the sole purpose of restarting the `enterframe`.

**Comment by ponychicken** [comment]
Others have the problem as well

http://www.khronos.org/webgl/public-mailing-list/archives/1103/msg00140.html

Quote: We're running into all kinds of weird problems when using it. For example if the tab is hidden for some time, the application often just hangs when you come back to the tab or the response is really springy, something like 3 or more frames behind. I always thought the request was just kind of "dirty flag" not something that is queued up. 
On Tuesday, April 5, 2011 at 12:45 PM, Leo wrote:
Me too. I testing now, whether stopping that helps

**Comment by ponychicken** [comment]
Yep. Using stop leads to much quicker recovery. We don't need start, there's timer.init()

**Comment by louisstow** [comment]
Brilliant. Yeah I guess either use `stop` and `init` or just `pause`.

**Comment by ponychicken** [comment]
Done in 1dde90db76244b68d2e9838779bd8af03be5bc28
