### ISSUE TITLE
A collision .onHitOnce function?

### ISSUE THREAD

**Issue by kevinsimper** [craftyjs/Crafty#566]
Would it be an idea to make a function which only once, every time two entities collides?

Often you want to do something the first time, like talk to a npc, but you only want to init that function once.

Something like this built in:

this.attr({alreadyTouched: {} })

this.onHit("Character1", function() {
        if(this.alreadyTouched['Character1'] !== true){
            console.log('collision')
            this.alreadyTouched['Character1'] = true;
        }
}, function(){
        delete this.touching['Character1'];
});

**Comment by starwed** [comment]
I've noticed that the current `onHIt` seems to confuse a lot of people, but I'm never quite clear on how they expect it to work.

**Comment by kevinsimper** [comment]
onHit fires for evey frame, maybe onHit should only fire once, and then a function called touching('entity', callback)?

**Comment by mpetrovic** [comment]
does onHit fire every frame the two entities are colliding?

If so, then maybe onHit should trigger the first frame two entities are
colliding, and we have another event for every frame two entities are
colliding. onIntersect, whileColliding, something like that

**Comment by kevinsimper** [comment]
@mpetrovic Yes, it fires every frame that they are colliding.
https://github.com/craftyjs/Crafty/blob/develop/src/collision.js line 211

**Comment by mucaho** [comment]
You can also put that example in the [Collision](http://craftyjs.com/api/Collision.html) api documentation instead of adding an explicit api function.

**Comment by kevinsimper** [comment]
This should be a external component and not a core function.

**Comment by bayleedev** [comment]
Maybe instead of `e.onHit` we could move it to `.on('hit')` at which point we could do `once('hit')` ?
