### ISSUE TITLE
Text textFont breaks with font-families containing isolated numbers

### ISSUE THREAD

**Issue by jameshoward** [craftyjs/Crafty#569]
E.g. new `Crafty.e('Text').textFont({ family : 'Times New Roman', size : '20px' }).text('Testing');`

Workaround is to switch to double quotes and wrap the family in single quotes.

E.g. family : `"'Times New Roman'"`

Might be nice to include this in the code instead, automatically wrapping families with spaces in single quotes or alternatively just wrapping them all in singlequotes as I don't believe it matters in CSS.

**Comment by potomak** [comment]
@jameshoward maybe you're using an old version of Crafty. I can't find the `setFont` method anywhere.
If you're talking about the `textFont` method (see http://craftyjs.com/api/Text.html) it works for me on Chromium even without quotes.
Can you please setup a working example of your problem? You can use http://jsfiddle.net/

**Comment by jameshoward** [comment]
Yeah, sorry, I corrected the title to textFont but not the text.

On closer inspection it seems the issue wasn't the spaces but the fact the font-family name has a number in it. 'Museo 300'. My example wasn't a good one.

See http://jsfiddle.net/fF6SU/ - the CSS for 'font' isn't applied, presumably as the string that is built isn't valid because it would be '20px Museo 300' while '20px Times New Roman' is fine.

**Comment by potomak** [comment]
I updated the code: http://jsfiddle.net/fF6SU/2/
I can reproduce the error now.

Let's see what @starwed, @kevinsimper or @sbyrnes321 think about this issue.

**Comment by starwed** [comment]
Yeah, the solution should be to just add quotes around the family when creating the font string.

(We can't set the properties individually because that's not an option when styling Canvas text.)

**Comment by kevinsimper** [comment]
I have made a pull request where I solved it.
