### ISSUE TITLE
Image loading handling on webkit

### ISSUE THREAD

**Issue by potomak** [craftyjs/Crafty#573]
> There's a bug in webkit that means the on load event is never fired (http://code.google.com/p/chromium/issues/detail?id=7731)

Image loading bug in webkit has been resolved in #382 with a workaround that was causing problems with IE, see #549 and #562.

The purpose of this issue is to discuss about a better way to handle images loading.

> There might also be a better way around it; the webkit bug only occurs when you try to load an already loaded image, so perhaps we could directly detect that.

**Comment by donaldducky** [comment]
I've also noticed if you use `.image(url)` twice with the same url (without preloading the images), only one `img.onload` event fires, so the second one doesn't get drawn. I'm trying to load images on the fly.

+1 on updating the image loading method.

**Comment by starwed** [comment]
> I've also noticed if you use .image(url) twice with the same url (without preloading the images), only one img.onload event fires, so the second one doesn't get drawn. I'm trying to load images on the fly.

That's a somewhat separate issue -- when you try to load an "Image" element with a url that hasn't been used yet, it creates a new asset and listens for the onload event.  The second element sees that the asset exists, and so trys to create a pattern with it before it's loaded.

For now, you'd probably be better off using [Crafty.sprite](http://craftyjs.com/api/Crafty-sprite.html) to add images on the fly.  I think it's intelligent enough to notify _all_ the necessary components when the image has loaded.

I think I see how to fix the issue for "Image" in a nice way, though.  (Trigger an event anytime an asset loads and hook into that.)

**Comment by donaldducky** [comment]
Yeah, it's not too complicated of a problem to fix.
I tried searching for image related loading issues and saw this.
If you want, I can create a new issue for it.

I'll try out the Crafty.sprite thing, thanks!

**Comment by starwed** [comment]
I looked into this, and I don't think there's much to be done about the somewhat wonky workarounds for image loading.

AFAICT it isn't causing us any bugs, just making the code kind of ugly.  :)
