### ISSUE TITLE
CocoonJS support

### ISSUE THREAD

**Issue by kevinsimper** [craftyjs/Crafty#576]
There seems to be problems getting Crafty.js running on CocoonJS. We should support that, because it is really great for development games on mobile.

There is already some people who has tried:
https://groups.google.com/forum/#!searchin/craftyjs/CocoonJS$20/craftyjs/bQUhXbdUibk/vVUFrlQjudoJ
https://groups.google.com/forum/#!searchin/craftyjs/CocoonJS$20/craftyjs/DmFavnJooUg/tzLwYngAy3IJ

But no concrete solution.

This is also more of a need of a guide on how to get i running on CocoonJS, which steps that has to be taken.

**Comment by kevinsimper** [comment]
I tried getting Crafty.js running on CocoonJS, but with no luck.

There is something Crafty does, that CocoonJS does not like.

I stripped out all DOM because that will not work in CJS, and just to avoid any coincidence.

You can test with this URL
http://kevinsimper.github.io/Crafty/test/

Did also create a post on their website.
http://support.ludei.com/hc/communities/public/questions/200687968-Canvas-draws-fine-on-computer

You can see the code here:
https://github.com/kevinsimper/Crafty/tree/gh-pages/test

**Comment by mucaho** [comment]
I just had a look at CocoonJS. It's awesome, it would be cool if crafty games could be packaged into a single executable file and distributed cross platform.

**Comment by kevinsimper** [comment]
They updated the Ludei application and improved the bug reporting, so I will give it a new shot :)

**Comment by kevinsimper** [comment]
Ludei has changed a lot since then, don't think it is needed anymore :)
