### ISSUE TITLE
Refactor everything to follow the Style Guide

### ISSUE THREAD

**Issue by louisstow** [craftyjs/Crafty#59]
Also need to move the documentation into the comments.

https://github.com/louisstow/Crafty/wiki/Style-Guide

**Comment by ponychicken** [comment]
Is the doc gonna be generated from the markdown comments?

**Comment by louisstow** [comment]
Yeah. Don't worry about it too much at the moment, have to work on it a bit more. It's mainly the name conventions.

Seeing as Crafty doesn't follow traditional OO, may as well use something else. Gonna play with it some more to find an easier more concise syntax.

**Comment by louisstow** [comment]
Updated the style guide for commenting formats. Follows JavaDoc.

**Comment by louisstow** [comment]
Warning. Going to move files around. Going to generate docs by the file names as categories.

**Comment by louisstow** [comment]
Done
