### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by kevinsimper** [craftyjs/Crafty#591]
Right now even through we have a bower.json file, `bower install crafty` would not work because for that to work, there would have to be compiled version of crafty.js in this repo.

And since this repo is set to start on the develop branch, it would be hard to avoid that crafty.js and crafty-min.js would not committed and then bower users will get the development unstable version.

How can this be solved? If it can't we should delete the bower.json file.

**Comment by starwed** [comment]
I don't really see any good way to solve this, other than having a separate repo for hosting a bower-friendly version.

I actually thought I'd already opened an issue on this, but apparently that was my imagination...  :)

**Comment by hugofirth** [comment]
Did anything come of this? Either porting the unbuilt version to a develop branch or having two separate directories would work. It is somewhat frustrating to have to manually manage a single dependency :)

**Comment by kevinsimper** [comment]
I just added it as a task for the 0.6 milestone: 
https://github.com/craftyjs/Crafty/issues/575

**Comment by hugofirth** [comment]
@kevinsimper awesome thanks :+1:

**Comment by kevinsimper** [comment]
#640
