### ISSUE TITLE
DOM doesn't delete old element

### ISSUE THREAD

**Issue by louisstow** [craftyjs/Crafty#60]
When using DOM and replacing the element with a custom element, it should delete the old element.

**Comment by ponychicken** [comment]
do you mean that

var el = Crafty("DOM, FirstElement").attr.....
el = Crafty("DOM").attr.....

## should delete FirstElement ? 

Leo
Sent with Sparrow

**Comment by louisstow** [comment]
When using `Crafty.e("DOM").DOM(document.getElementById("myent"))`. The element created in `init` should be removed.

**Comment by louisstow** [comment]
Fixed in commit `5c9754d`
