### ISSUE TITLE
Says time instead of frames - viewport documentation

### ISSUE THREAD

**Issue by kevinsimper** [craftyjs/Crafty#616]
It says frames in the description, but says time in the arguments list.

http://ludonomicon.com/crafty/api/Crafty-viewport.html

**Comment by starwed** [comment]
Well, it is a time -- just measured in frames.   But yeah, probably misleading.

fwiw,I plan on rewriting these to be time based after the 0.6 release.

**Comment by starwed** [comment]
As of #648, it _is_ a time.  :)
