### ISSUE TITLE
Line endings in repo

### ISSUE THREAD

**Issue by ponychicken** [craftyjs/Crafty#62]
I'm seeing mixed line endings in some files. Are you ok with moving to unix-style line endings?
If you're using windows you'd need to do `$ git config --global core.autocrlf true` (see http://help.github.com/dealing-with-lineendings/ for details)

**Comment by louisstow** [comment]
Yep that should be fine.  My editor defaults to Macintosh every now and then for some weird reason.

**Comment by ponychicken** [comment]
Done in 1c3e73cd3c3011306e72b56f136b6b31a62c31a3
@sorenbs Please run  `$ git config --global core.autocrlf true` if you're on win or  `$ git config --global core.autocrlf input` if you're on mac or linux

**Comment by sorenbs** [comment]
I did so before pushing the sorenbs branch. Let me know if there is still a problem.
