### ISSUE TITLE
Remove IE8 support

### ISSUE THREAD

**Issue by starwed** [craftyjs/Crafty#639]
I propose removing IE8 support.  
- There's a lot of code that works around IE8 issues
- Despite that, there are still major bugs that would require tons of work to fix
- IE8 doesn't support canvas or several other major features

Even that I would be ok with except that
- No one contributing to Crafty has shown the slightest interest in fixing these
- Almost no one is even in a position to run tests in IE8.  The 0.6 release could completely break IE8 and we might never know.

IE8 support is a millstone round our necks -- let's get rid of it!  :)

**Comment by kevinsimper** [comment]
How do you know what code is made only for IE8?

There is 5 places in the code where is ie8 is mentioned. Like the getter setter of course, but anywhere is where it is not mentioned?

**Comment by starwed** [comment]
There are a couple places I know of.  This would definitely be an incremental process.
- The getter/setter fallbacks
- The way we handle rotations is special cased for IE8 (L63 of DOM.js)
- We have to avoid some nice javascript additions because they're not supported by IE8.  A random example is [Date.now()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now)
- We use `eval` to parse JSON in one place, trying to support old versions of IE.  (This might not actually be necessary for IE8?)

I believe I've seen some other places in the code as well, but the point of this issue is more about making the decision.  :)

**Comment by starwed** [comment]
Anyone have any more thoughts on this?  Otherwise I'm tempted to just say we're dropping support.  (Or more accurately, dropping a half-hearted attempt at support.)

**Comment by kevzettler** [comment]
I'm in favor of mobile support over IE

**Comment by starwed** [comment]
Ok, let's make the call -- IE8 is no longer supported.  I'll keep this open as a tracking bug for patches that remove IE8 specific code.

**Comment by starwed** [comment]
Opened PR #657  to remove explicit IE8 support.  (landed, will probably need some follow up patches as we find more IE8 specific code.)

**Comment by kevinsimper** [comment]
I have looked and could not find any ie8 code more. Are there more?

**Comment by starwed** [comment]
There might be a couple of places where we dance around IE8 specific bugs, but I think all the code that specifically _supports_ IE8 (alternate code paths and the like) is gone.
