### ISSUE TITLE
css3dtransform support not detected correctly in IE11

### ISSUE THREAD

**Issue by kevinsimper** [craftyjs/Crafty#641]
DOM: Internet Explorer 9 and 11 error, 10's fine:
![image](https://f.cloud.github.com/assets/1126497/1693860/df71f714-5e96-11e3-9f58-482d0cf24788.png)

That is the only error i encounted, when doing all the test in internet explorer 9 - 10 - 11.

The test in Crafty.support.css3dtransform is properly wrong in IE11, because it shoud support it.

**Comment by potomak** [comment]
I think it's my fault. The test should actually distinguish between browser which support CSS 3d transforms and those who don't.

**Comment by starwed** [comment]
I think this has been fixed, but I don't have access to a windows machine with IE11, so feel free to reopen if I'm wrong.  :)
