### ISSUE TITLE
Controls should move depending on dt

### ISSUE THREAD

**Issue by kevinsimper** [craftyjs/Crafty#649]
Shouldn't controls now move depending on the dt or should they just be standard components and then if people want something which fits the more advanced steptypes, write their own components?

And how would you do it?

The normal dt is 20 (50 fps) which moves 3 pixels, and you get passed 30 in dt (33,3 fps) that is 1,5 times the normal dt so that would be 3 \* 1,5 = 4.5.

![image](https://f.cloud.github.com/assets/1126497/1701587/15a7da44-6061-11e3-89ac-9d3a362bd880.png)
Ueven edges

Is that the right solution, because it is possible to set half pixels on canvas, but as seen are it giving blured borders, when set to non whole integers. But depending on if you would round up and down to avoid that based of what is the closest whole number, you will be either 2 pixel ahead or backwards when 2 frames has passed.

Or the other solution is to only move when enough time has passed so that the move can be made in whole pixels, but that could make it more complicated, because you have to store when the key was started pressed, and keypresses is often very short.

I am properly overthinking this problem, but there is new things to consider now when the dt is not always deterministic.
https://www.scirra.com/tutorials/67/delta-time-and-framerate-independence#h2a1

**Comment by starwed** [comment]
For Multiway and Twoway, I think the way forward is to just have a component that tracks velocity and handles how the entity's position changes over time.  Then the other components just change that velocity.  I did something similar in the first game I wrote using Crafty -- having a component that moved objects based on velocity and acceleration.

The whole fractional pixel thing is distinct from how the controls components should work.  It can crop up all over the place, and so should probably be something that the base 2D code handles.  (I imagine snapping to the pixel grid would be something you can opt into.)

**Comment by kevinsimper** [comment]
I do understand acceleration and velocity, but can not quite figure it out on top of my head what to do.

What does that mean when compared to Crafty? The "whole fractional pixel"? That is how is should be done, because that is now how it works now today.

Implenting accelration and velocity would be simple to implement, but I can not read from what you have if the controls do indeed have to changed or not?

**Comment by mucaho** [comment]
fixed with #708 .
