### ISSUE TITLE
Stage shouldnt be selectable

### ISSUE THREAD

**Issue by louisstow** [craftyjs/Crafty#65]
Need to add `onselectstart = function() { return false; }` on to `Crafty.stage.elem`

Although some text elements may be wanted to be selectetable... hmmm.

**Comment by ponychicken** [comment]
I'd guess most games don't need selectionable stuff. Maybe introduce the Crafty.config object now & add option to keep selections?

**Comment by louisstow** [comment]
Maybe the text component can have an option for selectable or not?

**Comment by louisstow** [comment]
Fixed in settings
