### ISSUE TITLE
Custom drawing bug #2

### ISSUE THREAD

**Issue by georgii-ivanov** [craftyjs/Crafty#655]
```
window.onload = (function() {
Crafty.init();

Crafty.c("Box", { 
    ready: true,

    init: function() {
        this.addComponent("2D, Canvas");

        this.bind("Draw", function(obj) {
            this._draw(obj.ctx, obj.pos);
        });

        this.bind('EnterFrame', function() {
            this.x += 1;
            this.y += 1;
        });
    },

    _draw: function(ctx, pos) {
        var ctx = Crafty.canvas.context;

        ctx.beginPath();
        ctx.arc(pos._x, pos._y, this.radius, 0, Math.PI * 2, false);

        ctx.shadowColor = "#333";
        ctx.shadowBlur = 5;
        ctx.shadowOffsetX = 0;
        ctx.fill();

        ctx.closePath();
    }
});

Crafty.c("Player1", {
    init: function() {
        this.addComponent("2D, Canvas, player_1");
    }
});

Crafty.c("Player2", {
    init: function() {
        this.addComponent("2D, Canvas, player_2");
    }
});

Crafty.e("Box").attr({x: 160, y: 96, radius: 20, color: "#F00"});
Crafty.e("Box").attr({x: 320, y: 96, radius: 30, color: "#FF0"});
Crafty.e("Box").attr({x: 480, y: 96, radius: 10, color: "#0FF"});

Crafty.sprite('1.png', { player_1: [0, 0, 48, 48] });
Crafty.sprite('2.png', { player_2: [0, 0, 48, 48] });

Crafty.e("Player1").attr({x: 400, y: 50});
Crafty.e("Player2").attr({x: 200, y: 50});
});
```

Try this code.

If object Player1 OR Player2 not rendered, Circle boxes animated fine. BUT IF.... I enable Player2 fallen boxes is not working! WHY???

**Comment by georgii-ivanov** [comment]
just comment line: Crafty.e("Player1").attr({x: 400, y: 50}); or Crafty.e("Player2").attr({x: 200, y: 50});

**Comment by georgii-ivanov** [comment]
I like craftyjs and i want use it but that bug..... arghhhhh..... I already killed all the day to understand this problem

**Comment by starwed** [comment]
Hi, please use the forums for [questions like this](https://groups.google.com/forum/?fromgroups#!forum/craftyjs) -- this issue tracker is for bugs in Crafty.

When drawing entities, Crafty sometimes clips the canvas context using their position and dimensions.   That might be what you're seeing here, since you haven't given the box entities a height or width.

For performance reasons, this will occur when doing a partial redraw, but not when it draws the entire screen.  That generally explains inconsistent behavior like what you're describing.

**Comment by georgii-ivanov** [comment]
How to fix that problem?

**Comment by georgii-ivanov** [comment]
ok. I understood. He uses rect (x; x+w) (y; y+h). But... One problem is here. But i need specify center of circle but not top-left corner. How to do so through the attr () to transmit the coordinates of the center, but to redraw the position of the top left corner

**Comment by starwed** [comment]
The x y coordinates of the "2D" entity are _defined_ to be the upper left corner.  You could always have a method like

``` javascript
place: function(x, y){
     this.x = x - this.radius;
     this.y = y - this.radius;
}
```

although if the circle might change size later, you'd have to decide how to handle that.

**Comment by georgii-ivanov** [comment]
Thanks for the answer, but I had already guessed. But why CraftyJS have no metric from the center of an object?? (aka origin)? I have already found a crutch Crafty.circle(), but why it can not be implemented in the core? 

There is another problem - it is an object's shadow and blur radius. He specified not in pixels and there is a big problem, as it considered when partial rendering?
