### ISSUE TITLE
Abandon setters/getters

### ISSUE THREAD

**Issue by louisstow** [craftyjs/Crafty#66]
Wondering if it would be quicker to just check on enterframe if value changed. Apparently setters are quite slow and if enterframe is occuring anyway, may as well do some checks then.

**Comment by sorenbs** [comment]
Some reports a slowdown of **defineGetter** of ~50-100x compared to direct property access ( http://jsperf.com/transloc-getters ). If that's the case it would probably be better to use the enterframe approach if the property is accessed more than once every 50 frames (which is likely).
I found discussion of this in both mozilla, chrome and coffescript bugtrackers, and at least the guys at mozilla seemed to believe that faulty benchmark had a role to play in the reported numbers.

This benchmark shows a different picture: http://jsperf.com/getter-setter
Chrome 9/10/11 - about the same
FF3.6/FF4 - about the same
IE9 - 2-3x slower
Android 2.2 - 8x slower
iPhone 3 - about the same
iphone 4 - 4x slower
opera 11 - about the same
safari 5 - about the same
It is difficult to benchmark this correctly

It is hard to get these micro benchmarks right, so i will probably try to do some measurements in a real game to get a feel for this.

**Comment by louisstow** [comment]
Great research, thanks. Well Crafty is slow on mobiles so this may be part of the reason. Might have to think of a good way to do this. 

I'm thinking one global enterframe function that loops through entities. Would probably end up slower than setters.

**Comment by sorenbs** [comment]
The findings posted above are not related to Crafty in any way. However i have just done some testing of my getter/setter implementation. The setup is as follows:

I register 50 different getter and setters on an entity using the new getter and setter functions.
I bind to enterframe a function that adds a random value to each.

In step() i time this part to measure how long it takes to calculate 1 frame
while((new Date).getTime() > nextGameTick) {
                    Crafty.trigger("enterframe", {frame: frame++});
                    nextGameTick += skipTicks;
                    loops++;
                    this.fps = loops / this.fpsUpdateFrequency;
                }
And take the average over 1000 frames. Is it reasonable to time this part of the code?

I run my game using the native getter/setters (**defineGetter**/defineProperty) and with the fallback(check value on enterframe)

Browser | native | fallback

Chrome: 0,45 ms | 3,5 ms = 8x
FF4: 2,6 ms | crashed
IE9: 1,78 ms | 9 ms = 5x
Opera: 2,3ms  5 ms = 2x

In all cases the native implementation was faster.

It would be interesting to test how much faster it would be to just access a variable directly, but i wont have time to measure that for a couple of days.

**Comment by louisstow** [comment]
The fallback will be slower because having lots of entities wait for enterframe is generally slow. At least have one enterframe per entity (rather than one for each property per entity).

Ideally there would be one global enterframe event and I guess loop over looking for changed properties. That sounds just as bad lol.

That's the only way I can think of for now.

**Comment by sorenbs** [comment]
That's actually what i do. All 50 getters and 50 setters are added to an array and processed in a loop in a single global enterframe event. Would be fun to test if this is worth it on android, but in desktop browsers it doesn't look that compelling :-)

**Comment by maxencefrenette** [comment]
The advantage of the native setter method is that no matter of how many entities you have it is the same speed. The enterframe loop technique is O(n), wich means that with twice more entities, it will take twice as much time.

In other words, for big games, the defineProperty/**defineSetter** is way faster and for small games, we don't care about performance.

Hope i was clear :S

berseker59

**Comment by louisstow** [comment]
Guess this idea is closed now.
