### ISSUE TITLE
Crafty.init() prevents propagation of `touchmove` events

### ISSUE THREAD

**Issue by ryansmith3136** [craftyjs/Crafty#663]
The problem is that other JS libraries (e.g. scrolling libraries) might rely on this event. Crafty silently prevents the touchmove event from being executed.

Perhaps `Crafty.stop` can remove this listener?

**Comment by ryansmith3136** [comment]
Relevant code: [viewport.js line 16](https://github.com/craftyjs/Crafty/blob/ca1d96d825d4b37013c2b7248eba823bcb0b6d4b/src/viewport.js#L618-620)

**Comment by potomak** [comment]
I had the same problem but I didn't investigate, thanks @ryandotsmith.

**Comment by ryansmith3136** [comment]
Here is a patch that we applied to our local copy of crafty.

https://gist.github.com/ryandotsmith/8057623

**Comment by kevinsimper** [comment]
That is a relevant problem and should be optional.

But i do not see how your gist change anything, you just moved the anonymous function to a named function?

**Comment by starwed** [comment]
> But i do not see how your gist change anything, you just moved the anonymous function to a named function?

They want to unbind the function when Crafty.stop() is called.  To unbind the function, it's necessary to have a reference to it -- impossible with anonymous functions.

**Comment by ryansmith3136** [comment]
That is correct. A named function makes it possible for us to remove the listener.

Here are the docs regarding removing listeners: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget.removeEventListener

**Comment by kevinsimper** [comment]
Ah, the first thing you get blind on is the eyes.

**Comment by potomak** [comment]
> The problem is that other JS libraries (e.g. scrolling libraries) might rely on this event. Crafty silently prevents the touchmove event from being executed.

I think that the problem is worse than that because Crafty is preventing default on `window` so scrolling is completely disabled on touch screens.

**Comment by starwed** [comment]
That's normally what you'd want with games, of course.  But there should definitely be a way to disable it.

**Comment by potomak** [comment]
> That's normally what you'd want with games

when they are full screen...

> But there should definitely be a way to disable it.

I agree.

**Comment by ryansmith3136** [comment]
> On Dec 29, 2013, at 16:11, starwed notifications@github.com wrote:
> 
> That's normally what you'd want with games, of course.

This is true, but we were dealing with a home screen as well. So in this case, crafty modified the global environment which consequently affected screens which were outside of the game.

**Comment by kevinsimper** [comment]
> when they are full screen...

Which you are when you are on mobile, so touchmove should be disabled to avoid strange behavior. 
https://github.com/craftyjs/Crafty/blob/ca1d96d825d4b37013c2b7248eba823bcb0b6d4b/src/viewport.js#L479-L480

But i think it is a error that on mobile it is default fullscreen without any way of changing it :-1:

**Comment by kevinsimper** [comment]
Crafty now only ignores on the crafty stage element, and not the whole window now. This should not prevent scroll now.
