### ISSUE TITLE
SpriteAnimation Examples not working

### ISSUE THREAD

**Issue by mucaho** [craftyjs/Crafty#669]
The examples listed in the [SpriteAnimation API](http://craftyjs.com/api/SpriteAnimation.html) do not work for me.

In particular when defining the reel the automatic way

``` javascript
// Define an animation on the second row of the sprite map (y = 1)
// from the left most sprite (fromX = 0) to the fourth sprite
// on that row (toX = 3), with a duration of 1 second
Crafty.e("2D, DOM, SpriteAnimation, PlayerSprite").reel('PlayerRunning', 1000, 0, 1, 3);
```

it does not work. When defining the reel manually

``` javascript
// This is the same animation definition, but using the alternative method
Crafty.e("2D, DOM, SpriteAnimation, PlayerSprite").reel('PlayerRunning', 1000, [[0, 1], [1, 1], [2, 1], [3, 1]]);
```

it works.

**Comment by potomak** [comment]
I used the first signature without problems in Loop Desert only one week ago, see source at http://giovanni.curlybrackets.it/ld28/loop-desert.js and example at http://giovanni.curlybrackets.it/ld28/

**Comment by mucaho** [comment]
Thx potomak, I have investigated further using the official Crafty v0.6.1

``` html
<html>
  <head></head>
  <body>
    <div id="game"></div>
    <script type="text/javascript" src="crafty.js"></script>
    <script>
        Crafty.init(600, 300, document.getElementById('game'));
        Crafty.background('rgb(127,127,127)');

        // Define a sprite-map component
        Crafty.sprite(16, "squares.gif", {
            PlayerSprite: [0,0]
        });

        var ent = Crafty.e("2D, Canvas, PlayerSprite, SpriteAnimation"); //"DOM" does not work on Chrome for ANY reel animation

        //ent.reel('PlayerRunning', 1000, 0, 0, 1); //this does not work
        ent.reel('PlayerRunning', 1000, [[0, 0], [1, 0]]);

        ent.animate('PlayerRunning', -1);
    </script>
  </body>
</html>
```

The above code does not work with DOM rendering on Chrome.
The commented reel definition does not work (tested in FF&Chrome).

**Comment by starwed** [comment]
> The above code does not work with DOM rendering on Chrome.

This sounds like #664, which should be fixed in the develop branch now.  I suspect that was a buggy behavior in webkit, but I couldn't figure out how to reproduce it outside of Crafty.

> The commented reel definition does not work (tested in FF&Chrome).

The commented out portion specifies a reel consisting of a single frame, while the line below it has two frames.  Does it work if you change it to `ent.reel('PlayerRunning', 1000, 0, 0, 2);`?

It does look like one of the examples needs to be tweaked -- we changed that parameter to be the number of frames (instead of the `toX` position) just before it landed, and I guess I didn't catch everything.  :)

**Comment by mucaho** [comment]
> Does it work if you change it to `ent.reel('PlayerRunning', 1000, 0, 0, 2);`?

Yay it worked! Would you please update the examples / documentation accordingly (considering that you have the most clue how it works :) )?

**Comment by starwed** [comment]
@mucaho Ok, I think I updated the docs correctly? Take a look at #672 if you want to check.
