### ISSUE TITLE
The Storage test fails

### ISSUE THREAD

**Issue by kevinsimper** [craftyjs/Crafty#678]
The storage test fails, which pretty much means that the Crafty.storage does not work.

I vote for that it gets stripped out, because it seems nobody uses it, and if people do, they should use a more crossbrowser friendly library, which also was suggested in #432

**Comment by potomak** [comment]
:+1: 

I'm totally agree about stripping storage out of Crafty.js.

**Comment by starwed** [comment]
I think storage should be a part of Crafty -- a large number of games need this functionality.

We might look at directly incorporating a third-party library with a compatible license, and wrapping it in Crafty-friendly code.

Or perhaps we could just provide wrapppers for a couple of popular libraries.

**Comment by kevinsimper** [comment]
Made a pull request for a new storage function #692
