### ISSUE TITLE
Crafty.m('Score') - Crafty Models!

### ISSUE THREAD

**Issue by bayleedev** [craftyjs/Crafty#683]
What are thoughts on adding model support? Components I feel have logic but should only have view-related logic like position, movement, keyboard shortcuts, etc. Where a model might have more business logic.

For instance you might win or lose the game when one score object gets to 10? I might also need to sync that with the server to keep track of things. One model might also be shared across multiple components as one component displays the score, and another increases it when I score.

I can see it being used like this:

``` javascript
// Scene
var score = Crafty.m('Score').attr({points: 0});
Crafty.e('Score').setupScore(score);
Crafty.e('Ball').setupScore(score);

// Model
Crafty.m('Score', {
    init: function() {
      this.points = 0;
    },
    increment: function() {
      return this.set('points', this.get('points') + 1);
    },
});

// Components
Crafty.c('Score', {
  init: function() {
    this.requires('DOM, 2D, Text, Grid')
      .text('0 Points')
      .attr({w: 300});
  },
  setupScore: function(score) {
    this.score = score;
    this.score.on('change:points', this.updateScore.bind(this));
    return this;
  },
  updateScore: function() {
    this.text(this.score.get('points') + ' Points');
    return this;
  },
});
Crafty.c('Ball', {
  init: function() {
    // stuff
  },
  setupScore: function(score) {
    this.score = score;
    return this;
  },
  gainPoint: function() {
    this.score.increment();
    return this;
  },
});
```

The model events are import to noticing differences:

```
this.score.on('change:points', function() {});
```

I'd be happy to submit a pull request if I knew it was wanted in this repo. If not maybe this could be extracted to another library, or maybe another library could be recommended for doing this for me? Thank you for your time.

**Comment by starwed** [comment]
Maybe I'm being dense, but I guess it's not clear to me from your description what this provides that's currently missing.  The "Score" model doesn't seem to do anything different from a regular component?

What features do models have that components don't?  (The `on()` syntax seems to be `bind()` with a different name, but again, maybe I'm just being dense.)

**Comment by bayleedev** [comment]
Well like I said, a model could be shared across multiple components with shared data and events that bind them. Right now I see components having view and business logic and I feel those should be separate.

You are right though, functionality wise, they don't provide anything components don't... since I believe you can trigger custom events on entities, right?

Maybe I'm just too headstrong about backend patterns since I'm new to game development. I'd rather do it the "right" way so pardon my ignorance.

**Comment by starwed** [comment]
> You are right though, functionality wise, they don't provide anything components don't... since I believe you can trigger custom events on entities, right?

Yes, that's a pretty major part of how Crafty is intended to be used.  You can trigger events both on specific entities or globally.  If you want to create something like your model with the existing code, I'd probably do something like:

``` javascript
Crafty.c("ScoreModel", {
 points: 0,
 init: function(){
     this.bind("IncrementScore", this._incrementScore);
 },
 _incrementScore: function(){
     this.points++;
     Crafty.trigger("UpdateScore", {points: this.points});
  }
});
```

Then the "Ball" component would just trigger "IncrementScore", and the "Score" component would bind to "UpdateScore".   Doing it this way, you wouldn't need to specifically setup the relationship between the components.

You can also simply write regular javascript code to handle this stuff; you don't need to stuff everything into components.  That's, of course, how a lot of Crafty stuff works on the backend.

**Comment by starwed** [comment]
Just to be clear, I have no experience working with the type of setup I think you're used to.  So if there's something I'm missing don't hesitate to lay it out.  :)

**Comment by bayleedev** [comment]
You're triggering/binding to global `Crafty` events though, right? Is it possible to trigger/bind those directly to the entity so it doesn't cloud it up?

**Comment by bayleedev** [comment]
Regardless, because they don't add extra functionality this is probably just me being inexperienced at these game things. If I really want this I can just create a 'Model' and/or 'Observer' components and try my bestest to keep them separate to make me happy. Thanks for talking  it out with me!

**Comment by starwed** [comment]
Sure, that would just require the same sort of glue code you used.  

"Ball" would use the same sort of setup code you had, and then use `this.score.trigger("IncrementScore")`.

The easiest way to trigger an event on a subset of entities is again through components.  `Crafty("MyEventListener").trigger("UpdateScore")` will trigger the event only on entities with the "MyEvenListener" component.  This might be a good way to go about implementing your ideas as new components. :)   

Your "Model" component could include a `register` function that would add an entity -- it could be something like 

``` javascript
   register: function(e){
       e.addComponent("Listener" + this[0]);
       // add an event hook in case a specific model needs to do something else
       this.trigger("EntityRegistered", e);
   },

  triggerListeners: function(event, data){
     Crafty("Listener" + this[0]).trigger(event, data);
  }
```

(The id of an entity is guaranteed to be unique, and accessed by `this[0]`.)

**Comment by bayleedev** [comment]
@starwed looks like `attr` already does events on data changes so I just added a little sugar:

``` javascript
/**
 * Model helps bind data to multiple components.
 *
 * @example
 * ~~~
 * dave = Crafty.e('Model');
 * dave.bind('change:name', function(name) { console.log('Daves new name', name); });
 * bob = Crafty.e('Model');
 * bob.bind('change:name', function(name) { console.log('Bobs new name', name); });
 *
 * dave.attr({name: 'David'}); // => Daves new name David
 * bob.attr('name', 'Robert'); // => Bobs new name Robert
 * ~~~
 */
Crafty.c('Model', {
  init: function() {
    this.bind('Change', this._changed);
  },
  _changed: function(changes) {
    for (key in changes) {
      this.trigger('change:' + key, changes[key]);
    }
  },
});
```

So in theory I could do something like...

``` javascript
// Scene
var score = Crafty.e('ScoreModel').attr({points: 0});
Crafty.e('ScoreText').setupScore(score);
Crafty.e('Ball').setupScore(score);

// Model
Crafty.c('ScoreModel', {
    points: 0,
    init: function() {
      this.requires('Model');
    },
    increment: function() {
      return this.attr('points', this.attr('points') + 1);
    },
});

// Components
Crafty.c('ScoreText', {
  init: function() {
    this.requires('DOM, 2D, Text, Grid')
      .text('0 Points')
      .attr({w: 300});
  },
  setupScore: function(score) {
    this.score = score;
    this.score.on('change:points', this.updateScore.bind(this));
    return this;
  },
  updateScore: function() {
    this.text(this.score.attr('points') + ' Points');
    return this;
  },
});
Crafty.c('Ball', {
  init: function() {
    // stuff
  },
  setupScore: function(score) {
    this.score = score;
    return this;
  },
  gainPoint: function() {
    this.score.increment();
    return this;
  },
});
```

All is right with the world :heart:

**Comment by kevinsimper** [comment]
I think there is a need for models, especially when your game gets very large, but it is more advanced and maybe too complicated for people starting with Crafty.

`.on` would be an awesome function, so that you could bind functions to entity events, instead of global events which can be polluted. Like the event `change:points` could be used by many components.

@blainesch Did you use backbone.js in your example?

**Comment by bayleedev** [comment]
@kevinsimper yes my examples are based on backbone models, which I decided to end up using in my project. The backbone models provide a lot of functionality that took longer than I thought to replace.

Besides syncing the data to the server I did end up making the lot of the functionality in various components. You can see   [that code here](https://github.com/blainesch/pong/commit/5e2530d1f9ba349bd98cc44f139af57719e4e8f3).

**Comment by kevinsimper** [comment]
@blainesch Where or how do you extend the Crafty entity with the Backbone model, because i do not see anywhere in that file that makes use of Backbone events? The "this.trigger" still referer to the global Crafty events

**Comment by bayleedev** [comment]
@kevinsimper I decided to drop creating crafty "component models" idea I linked to above, and just use backbone models completely.

I believe triggers only happen on the specific entity, maybe by accident?

``` javascript
var person = Crafty.e('Person');
person.bind('Change', function() { console.log('Changed person!'); });

var tigger = Crafty.e('Tiger');
tigger.bind('Change' ,function() { console.log("The most wonderful thing about tiggers is that I'm the only one!"); });

Crafty.bind('Change', function() { console.log('Global change!'); });

tigger.attr({friend: 'Piglet'}); // -> "The most wonderful thing about tiggers is that I'm the only one!"
```

**Comment by kevinsimper** [comment]
@blainesch Yes, you are right, you can do events on entities, which are also on local entities only :) But you can not do this: `this.score.on('change:points'` without Backbones model, so you only get a change event when a certain property change. That could be cool to have in Crafty.

**Comment by bayleedev** [comment]
If this was implemented in crafty, how would it look? We could just update `attr` to trigger change events for all attributes? We could add a `model`? Or just tell people to just use backbone? :D

I'd be happy to submit a pr for this.

**Comment by kevinsimper** [comment]
I think it would be a improvement.We should try changing the `.attr` function. I think there should also be a silent option as Backbone does.

The docs should also mention as it is only the public function that trigger change:name events, you will not get events when Crafty change attr internally like when tweening and other.

**Comment by starwed** [comment]
Random thought that might help with this sort of architecture: we could allow something like jquery's selectors to work on event objects.  The syntax could be something like  

``` javascript
Crafty.bind("Change[eventProperty='filteredValue']", doThing)
```

The bound function would only be called when the event matched the stated criteria -- in this case, if the event object had a field `eventProperty` that matched the value `'filteredValue'`.

Some events just pass string values, so you could also do something like this:

``` javascript
Crafty.bind("RemoveComponent['Canvas']", doThing)
```

and it would check the event data directly against the specified value.

This would definitely be _possible_ to implement, but might be tricky to design properly.  :)  It's pretty common to have the first part of a callback checking against the event object, so it would tidy up a lot of code.

_e:_ To check the existence of a property, you could do something like `"Change[points?]"`

**Comment by kevinsimper** [comment]
@starwed That could be nice. What could it be that you would want the `"Change[eventProperty='filteredValue']"` when you know the value.

Would it be an event something like this  `"Change[life='0']"`?

But I would prefer more local events like do that on the entity themselve, also something like points.

**Comment by starwed** [comment]
> What could it be that you would want the "Change[eventProperty='filteredValue']" when you know the value.

Some events might have an `id` type attribute that tells you what is changing.  For instance, the "StartAnimation" event object will tell you what animation is starting.  So you might want something like `e.bind("StartAnimation[id='running']`).

Fairly limited use case, but pretty easy to implement if the `Event[attrib]` syntax already existed.

**Comment by bayleedev** [comment]
So something like:

So for data:

``` coffeescript
person = Crafty.m 'Person'
person.data({name: {first: 'Blaine', middle: 'M', last: 'Sch'}}, silent: true)
person.data 'name.last' # Sch
person.data 'name.last', 'Schmeisser', silent: true
```

Events:
`Change[name]` if anything inside of name changes
`Change[name.first]` if you change the first name
`Change[name.first=='Blaine']` triggers when I set the first name to `Blaine` Only works on string values, maybe numeric.
`Change[name.first!='Blaine']` when the current value is `Blaine` and I change it to something else. Only works on string values. Maybe numeric.
`Delete[name.first]` when first name is deleted, really only useful on nested items.
`Set[name]` When name is created
`Set[name.first]` when 'first' is created within name.

Continuing from the first example:

``` coffeescript
# Change last name. Triggers:
# "Change[name.last]"
# "Change[name.last=='Sch']"
# "Change[name.last!='Schmeisser']"
# "Change[name]"
person.data 'name.last', 'Sch'

# Change name and attributes. Triggers:
# "Change[name]"
# "Delete[name.first]"
# "Delete[name.last]"
# "Delete[name.middle]"
# "Set[name.f]"
# "Set[name.m]"
# "Set[name.l]"
person.data(name: {f: 'Blaine', m: 'M', l: 'Sch'})
```

Unless there are any objections I'll start hacking on this now :shipit:

**Comment by starwed** [comment]
I think at first it'd be a good idea to implement this as an extension to Crafty, rather than part of its core.  Luckily that's pretty easy to do with `Crafty.extends`.

Specific improvements necessary to implement it, like the discussed augmentation of the `bind` syntax, could be merged directly into Crafty.

Then with a working model system, it'd be easier to evaluate whether it would make sense to directly incorporate it.  :)

**Comment by kevinsimper** [comment]
@blainesch I do not think we need other than a change event for starter, where you can define a attribute and an value by doing this `e.bind("change[health='0])`

**Comment by bayleedev** [comment]
@kevinsimper I don't think I understand what you meant.

I believe you were saying you don't think we need anything except for change events, and we should be able to define attributes in a bind call? 

The second part doesn't sound right...

**Comment by mucaho** [comment]
So the PR got merged. Are there additional PR's that will follow-up, or can we close this?
