### ISSUE TITLE
errors running npm install

### ISSUE THREAD

**Issue by mucaho** [craftyjs/Crafty#685]
anyone else having issues running npm install in order to install the node modules? in particular I get a lot of errors mentioning `grunt-browserify` and `npm ERR! git clone git://github.com/feross/base64-js.git undefined`

**Comment by starwed** [comment]
Yeah, I had some errors trying to run `npm update` the other day, but couldn't tell if it was something wrong with our package.json file or my local setup.

I think maybe the way we're specifying which version of browserify to use is causing problems.  When I removed the tilde from `"grunt-browserify": "~1.2.9"` it seemed to fix things.  There's a new version out anyway, so we should probably switch to  `"1.3.x"` or some such.

**Comment by mucaho** [comment]
I tried both `1.2.9` and `1.3.x` with no success. It's rather unfortunate, I can't build crafty at all. I guess the problem is on my end somewhere.

**Comment by kevinsimper** [comment]
I downloaded and uploaded a version of grunt-browserify for you:
http://ge.tt/6QssftC1/v/0

**Comment by mucaho** [comment]
Thank you kevin! You uploaded the dependencies for me, now i just have to paste in the code for grunt-browserify. Closing this issue, as it's only on my end obviously.

**Comment by mucaho** [comment]
Just an update: npm install is magically working again :)

**Comment by mucaho** [comment]
After a while, I wanted to continue working on my PRs again. However, npm install is failing for me again. If you delete your `node_modules` folder, does it work for you guys? which `node -v` (node version) and `npm list -g npm` (npm version) are you using?

**Comment by mucaho** [comment]
I managed to solve the problem by installing `nvm` (Windows Node manager). Using that I updated `node` to `v12.0.0` and now have `npm v2.5.1`.
