### ISSUE TITLE
Crafty ignores polygon onHit()

### ISSUE THREAD

**Issue by danbruegge** [craftyjs/Crafty#709]
Hi, not sure if it is a bug or misuse from my side.

http://jsfiddle.net/haenx/85mhj/

The polygon will completely ignored onHit().

I wrote also a post on stackoverflow for a while. 
https://stackoverflow.com/questions/20002536/craftyjs-ignores-polygon-onhit

**Comment by starwed** [comment]
That fiddle seems to be using a pretty old version of crafty (0.5.3).

That said, it seems like you're just missing the "Collision" component on the enemy.  Crafty falls back to simpler bounding box tests when one of the objects is missing an explicit collision polygon.

I'll go ahead and close this for now, but thanks for the report.  :)

**Comment by danbruegge** [comment]
Ok, this will work: http://jsfiddle.net/85mhj/12/

But how should i know, to define the "Collision" component to the enemy too?

Thanks for the help. :) Thats saved my day!

**Comment by starwed** [comment]
Yeah, looks like the documentation is pretty vague about this.  I'll make sure it gets mentioned.

**Comment by danbruegge** [comment]
Sounds good. Thx! :)

**Comment by kevinsimper** [comment]
> Ok, this will work: http://jsfiddle.net/85mhj/12/

Working jsfiddle to others: http://jsfiddle.net/85mhj/13/

**Comment by danbruegge** [comment]
What has changed?
