### ISSUE TITLE
Reports that pause doesn't reload the screen

### ISSUE THREAD

**Issue by louisstow** [craftyjs/Crafty#71]
Had a report that when changing tabs and going back to the window it becomes a white screen and doesn't come back.

**Comment by louisstow** [comment]
This was due to `window.blur` calling `stop` instead of `pause`

**Comment by ponychicken** [comment]
Nah, the problem was the new `document.body.removeChild(Crafty.stage.elem);` inside stop() as well as this ab87e0a0eb1b80ba818eb66208dd1afea4620fcd . Stop() is actually better for blur (see Issue #56)

**Comment by louisstow** [comment]
Stop is meant to be when the user wants to create a new game almost. Pause should also use `cancelRequestAnimationFrame`.

**Comment by louisstow** [comment]
Fixed
