### ISSUE TITLE
Canvas not being cleared properly while zoomed

### ISSUE THREAD

**Issue by starwed** [craftyjs/Crafty#711]
Reported on [stackoverflow](http://stackoverflow.com/questions/20491607/white-lines-at-zooming)

A jsfiddle using 0.6.2 [reproduces the issue](http://jsfiddle.net/ysDtQ/48/)

**Comment by mucaho** [comment]
I can confirm the lines in Chrome; no problems in FF though

**Comment by starwed** [comment]
I see lines in both Chrome and FF, but in slightly different ways.

After reading over the code again, I don't see anything obvious we're doing wrong.  I'll try to reproduce the issue outside of crafty, in case it's just some canvas bug when you set a transform matrix.

**Comment by starwed** [comment]
Hmm, possibly related is [this report](https://groups.google.com/forum/?fromgroups#!topic/craftyjs/h5MHTMsQcAI).

**Comment by starwed** [comment]
I'm a bit confused why something like this would _start_ appearing in 0.6.2 -- I don't think we even changed the canvas drawing code?

I guess I'll do some sort of bisection to figure out where the problem was introduced.

**Comment by starwed** [comment]
Ok, bisection indicates that it's from [this commit](https://github.com/starwed/Crafty/commit/0ad5c872ba1166533f3e4d17872982a4933c1b5b).

Nothing there directly touches the drawing code -- but notably, Furniman calls `centerOn`, which _is_ affected.  So like the problems with `zoom`, I'd guess it's something about viewports coordinates.

**Comment by starwed** [comment]
Yup, before that commit the viewport coordinates are integers in the testcase, afterwards they're fractional.

Presumably this is the problem with the `zoom` function, too.  When the viewport transformation offsets our pixels from "real" pixels some sort of error creeps in.

**Comment by starwed** [comment]
Ok, so we can half fix this: clearing the canvas area _after_ clipping to it fixes the problem for me in Chrome.

Unfortunately, Firefox behavior here seems broken.  [Here](http://jsfiddle.net/VAXrL/1059/) is a jsfiddle that reproduces the issue.  I'm not really sure how we can work round this when the canvas is zoomed in.

However, we can at least round the actual viewport coordinates to integers when we aren't scaled at all.  That should help mitigate the issue.

**Comment by ZeRo2150** [comment]
I have also an Problem with IE. I have an Canvas initialised with an fixed height and width, and after that i set the scale of the viewport for the actual window viewport. In Chrome everything is fine, but in IE no matter which version 9-11 i get black lines for all animated sprites. Maybe someone could help me to find some solution to maintain an fit to screen behavior.

**Comment by mucaho** [comment]
If I understand correctly the problem is caused by rounding issues involved when redrawing only parts of a **zoomed** viewport.
@starwed Could we make an option (like `Crafty.completeRedraw = false`) that forces the whole viewport to be redrawn every frame?

**Comment by starwed** [comment]
> @starwed Could we make an option (like Crafty.completeRedraw = false) that forces the whole viewport to be redrawn every frame?

My plan for the future was to implement a redraw threshold in canvas layers as an option.  (Currently we do a complete redraw when 60% of entities or more need it -- that seems pretty arbitrary, so might as well let the user set it.)

I haven't had too much time to work on the layers stuff, so we could just allow you the ability to set the canvas redraw threshold directly.

**Comment by starwed** [comment]
It would just be changing [this code](https://github.com/craftyjs/Crafty/blob/develop/src/graphics/canvas-layer.js#L121) to check against a user adjustable value -- and documenting that a value of 0 will force a complete redraw every time.

**Comment by mucaho** [comment]
Hmm, I always thought that we couldn't just increase dirty rectangles by 1 px on each side, but upon further inspection of the implementation it seems that we search for entities that need to be redrawn inside the dirty regions anyway.
@starwed 
Why don't we just make the dirty regions a bit bigger, or am I missing something here?

**Comment by mucaho** [comment]
This bug seems to happen even on an unzoomed viewport (on Macbook 12" with retina display).
See https://groups.google.com/d/msg/craftyjs/uTTU3Cljdig/lWHa-mLjAgAJ.
At this point I'm inclined to hot-fix current code so that the whole viewport is redrawn no matter what, until we resolve this issue.

**Comment by starwed** [comment]
> Why don't we just make the dirty regions a bit bigger, or am I missing something here?

The problem is the interaction of clipping, clearing, and then drawing.  These lines appear at the border of the region we're using.  Moving the dirty region up by 1px just moves where the border is, unfortunately.

I guess theoretically we could try to calculate a clipping region that actually corresponds to screen pixels, and use that instead?

**Comment by starwed** [comment]
> At this point I'm inclined to hot-fix current code so that the whole viewport is redrawn no matter what, until we resolve this issue.

@mucaho  I am ok with such a hotfix.

**Comment by mucaho** [comment]
Bug was recently reported on [gitter](https://gitter.im/craftyjs/Crafty?at=58fbd59c881b89e1017795e8).

--------------------

After many edits to this comment:
I may have found a solution that fixes this!
Motivated by @starwed 's comment
> I guess theoretically we could try to calculate a clipping region that actually corresponds to screen pixels, and use that instead?

So the problem, as far as I understand, is that `canvas.ctx.clearRect(x, y, w, h)` and `canvas.ctx.rect(x, y, w, h); canvas.ctx.clip()` don't operate on the same area when viewport is zoomed (by setting `canvas.ctx.setTransform(...)`. `clearRect` disregards any transformations and only works on default canvas transform.

A possible solution is to perform these two operations with the default, identity transformation matrix. However, for this to work, we have to find out and use the final screen coordinates for the areas of these clear & clip operations:
```js
var view = this._viewportRect(),
    scale = view._scale,
    x0 = rect._x * scale + Math.round(-view._x * scale)
    y0 = rect._y * scale + Math.round(-view._y * scale),
    x1 = (rect._x + rect._w) * scale + Math.round(-view._x * scale),
    y1 = (rect._y + rect._h) * scale + Math.round(-view._y * scale);
```
After performing clear & clip with the standard transformation matrix, we restore the viewport transformation matrix and continue drawing our entities. In order to find candidates for drawing I suggest to widen the search area a bit, just to be safe.

Putting all of this in code (quick & dirty impl): Replace [these src/graphics/canvas-layer.js lines](https://github.com/craftyjs/Crafty/blob/da9c1011ed4e0b1b496da6d7c208239eb57a3f18/src/graphics/canvas-layer.js#L235-L251) with
```js
            // Find the smallest rectangle with integer coordinates that encloses rect
            rect = rectManager.biggerBounds(rect, {});

            var screenRect = rectManager.screenBounds(this._viewportRect(), rect, {});

            // If a dirty rect doesn't overlap with the viewport, skip to the next one
            if (!overlap(rect, view)) continue;

            //search for ents under dirty rect
            q = Crafty.map.search(rect, false);

            ctx.save();
            ctx.beginPath();

            //clear the rect from the main canvas
            //Then clip drawing region to dirty rectangle
            ctx.save();
            ctx.setTransform(1, 0, 0, 1, 0, 0);
            ctx.clearRect(screenRect._x, screenRect._y, screenRect._w, screenRect._h);
            ctx.rect(screenRect._x, screenRect._y, screenRect._w, screenRect._h);
            ctx.restore();

            ctx.clip();
```
whereas the utility `rectManager` methods are
```js
      biggerBounds: function(rect, outRect) {
        outRect = outRect || rect;
        outRect._x = (rect._x - 1 * Crafty.viewport._scale)|0;
        outRect._y = (rect._y - 1 * Crafty.viewport._scale)|0;
        outRect._w = (rect._w + 2 * Crafty.viewport._scale)|0;
        outRect._h = (rect._h + 2 * Crafty.viewport._scale)|0;
        return outRect;
      },

      screenBounds: function(view, rect, outRect) {
        outRect = outRect || rect;

        var scale = view._scale,
            x0 = rect._x * scale + Math.round(-view._x * scale)
            y0 = rect._y * scale + Math.round(-view._y * scale),
            x1 = (rect._x + rect._w) * scale + Math.round(-view._x * scale),
            y1 = (rect._y + rect._h) * scale + Math.round(-view._y * scale);

        outRect._x = (x0 - 1)|0;
        outRect._y = (y0 - 1)|0;
        outRect._w = (x1 - x0 + 2)|0;
        outRect._h = (y1 - y0 + 2)|0;

        return outRect;
      },
```

This approach needs testing, but looks promising.

---------

EDIT: I'll take a stab at implementing this, alongside improving performance by using spatial map cells as dirty regions.

**Comment by mucaho** [comment]
Tested briefly on a colleagues Mac, seems to work. If there are any problem I missed, we can reopen this issue.
