### ISSUE TITLE
Crafty.viewport.reset() does not pan back to 0. Should it?

### ISSUE THREAD

**Issue by sbyrnes321** [craftyjs/Crafty#717]
The documentation implies that if you pan the viewport (e.g. `Crafty.viewport.x += 100`), then running `Crafty.viewport.reset()` should undo that by panning back. But that is not what happens. It does not pan back.

http://jsfiddle.net/T9Mp9/ (using [Crafty 0.6.2](https://github.com/craftyjs/Crafty/releases/tag/0.6.2) )

Is this unclear documentation, or is it a code error?

**Comment by starwed** [comment]
I think it probably should.  (I don't think I actually changed the behavior in [this commit](https://github.com/starwed/Crafty/commit/0ad5c872ba1166533f3e4d17872982a4933c1b5b), though -- I think the old behavior was also to stop existing pans but not reset the position?)
