### ISSUE TITLE
2D Raycast

### ISSUE THREAD

**Issue by mucaho** [craftyjs/Crafty#729]
Feature request from [forum](https://groups.google.com/forum/#!topic/craftyjs/Lyb2FsGyIU4)

> You'd want to examine how the HashMap code works -- it implements a spatial partition we use for broad phase collisions.  Any implementation of raycasting would probably use that as a starting point.  You could step through the grid sections in order, checking in each one for collisions.  That would definitely be more efficient than using a collision entity, since you could just stop once you found an intersection, and could use a test for ray intersection instead of SAT.

**Comment by mucaho** [comment]
@grozen you are our collision expert :) do you have any additional ideas?

**Comment by grozen** [comment]
@mucaho I'd hardly say that as I actually had very little to do with the actual collision detection algorithm. That being said, this sounds like a great idea if you or someone else are up to it.

Assuming this ends up as a new sort of component, it would be very simple to reuse the collision events that became available as part of #699, though obviously it would be prudent to define this as a new collision type (in addition to MBR and SAT that are currently what `.hit` may return).

**Comment by mucaho** [comment]
Ah ok, I thought you were involved in writing the spatial hashmap.

I took the painful (but also performant) approach by stepping through the spatial grid sections iteratively. A preliminary version can be found on my [raycast branch](https://github.com/mucaho/Crafty/tree/raycast). This is entirely based on [this tutorial](http://www.flipcode.com/archives/Raytracing_Topics_Techniques-Part_4_Spatial_Subdivisions.shtml), which is indirectly linked from Crafty's HashMap code.

**Comment by mucaho** [comment]
Update:

I have implemented the algorithm that finds the nearest bounding box or all bounding boxes that are intersected by the ray in the HashMap. Now I have to figure out how to efficiently get the actual intersections, since bounding boxes do not always correspond to the actual entity. The following questions arise:
- (1) We support only rectangular entities?  
  When rectangular entities are rotated, their bounding box is larger than the actual entity, thus we have to use [line segment intersection](http://stackoverflow.com/questions/563198/how-do-you-detect-where-two-line-segments-intersect) in order to determine if the ray intersects with the rotated entitiy and to retrieve actual intersection point(s).

![](http://i61.tinypic.com/16ly9zo.jpg)
- (2) Even if we support only rectangular entities, how will we determine if the ray hits entities that have transparent texture? The entitiy could be completely transparent, thus ray should not intersect with that entity at all

![](http://i61.tinypic.com/10pdbhv.jpg)

Also, @starwed what do you think? Should we handle either case or let the user decide?:
- (1) is possible to implement, but will require additional computation for each bounding box. However we can also provide the method for (1) to the user, so he can get the precise intersection only if he needs it
- (2) I don't have any clue how to solve this or if it's needed

**Comment by starwed** [comment]
I'll have a more in depth look later, but I'd think the easiest tactic would be for it to only work on entities which implement a hitbox.

**Comment by mucaho** [comment]
Ok, thanks for your input, so 
1. find potential candidates in the HashMap using `this._cbr || this._mbr || this` as the bounding box
2. very if ray intersects with potential candidate:
   - if the `Collision` component was added to the entity, it will have  `this.map` as the hitbox; use this hitbox for intersection test
   - if the `Collision` component was not added to the entitiy, omit it

**Comment by starwed** [comment]
IIRC the Collision component will just check for overlap with the MBR if there's no hitbox.

I'd be fine with ignoring non-hitbox entities completely in this case.

**Comment by danielGood** [comment]
Hi, is this issue still open?  I took a shot at my own which can be found here.  http://danielgood.github.io/projects/raycasting/index.html.

**Comment by starwed** [comment]
@danielGood  That looks pretty nice!  Yes, this issue is still open, and thanks for poking at it.

But, if we implement something like this directly in Crafty, there's some existing functionality we'd want to use:  broad-phase collision testing, and the existing mechanisms for defining hitbox polygons.

I did a bit of research/thinking yesterday.
- Looks like we could use [the 2D version of this algorithm](http://www.cse.yorku.ca/~amana/research/grid.pdf) for traversing the broad-phase spatial grid.  
- To start with, it'd be better to only check for collision against entities which already have a hitbox polygon
- The intersection algorithm Daniel seems to be the standard one, so we'd definitely want to use something pretty similar.  But as always we need to avoid creating temporary objects, which'll probably make it look pretty ugly compared to a lot of the reference implementations I've looked at.

If no one else takes this up, I'll probably tackle it after the 0.7 release is done.

**Comment by danielGood** [comment]
Thanks!  I've been working on this for the past half week on and off.  I don't think it would be to hard to integrate what I've written with hitbox polygons, but I think this may make the program less flexible.  I am not that familiar with how certain shapes match up with certain hitboxes.  My biggest concern is diagonal lines which can simulate arcs.    

I'm basing it off of the tutorials  at http://www.redblobgames.com/articles/visibility/ and http://ncase.me/sight-and-light/.
Both these sites contain excellent open-source implementations.

Anyways, I'll continue working on it; it is not where I want it yet.

**Comment by mucaho** [comment]
I paused my work on it, but you can see the current progress in my [raycast2 branch](https://github.com/mucaho/Crafty/tree/raycast2). I wrote some tests, implemented iteration in the broad-phase and the intersection algorithm. However, they are not connected yet. I was planning on continuing the development on it during summer, but feel free to do so before :)
