### ISSUE TITLE
Improve documentation for onHit

### ISSUE THREAD

**Issue by mucaho** [craftyjs/Crafty#739]
There have been couple of issues where people misinterpret the `onHit` functionality. Newest one in the [forum](https://groups.google.com/forum/#!topic/craftyjs/C7PwLOKlgqA). Also #566 

Improve docs so they mention that the **hit callback** of `onHit` will be called **every frame the collision is active**.

**Comment by starwed** [comment]
We landed a [pretty big change](https://github.com/craftyjs/Crafty/pull/699) to onHit recently; that might make this particular type of problem a thing of the past?  There are now proper "HitOn" and "HitOff" events that only trigger with an actual change. 

90% of the time when folk have issues with onHit they should just be using `hit()`, though.  I'm not really sure what's so attractive about onHit.

**Comment by mucaho** [comment]
The `onHit` per se wasn't changed at all if I understand the code correctly. I had the same experience with `onHit` as other folks: _Oh cool there is this method `onHit` which does something automatically for me. Let's just use it over `hit` because it's simpler._
