### ISSUE TITLE
Improve performance of methods that return new objects

### ISSUE THREAD

**Issue by mucaho** [craftyjs/Crafty#746]
Improve the performance of `2D.pos()`, `2D.mbr()` and similar methods to allow passing an optional argument in which the result will be stored.
- [x] `2D.pos(), 2D.mbr()`
- [x] `Crafty.math.Matrix2D`
- [x] `Crafty.map.key`

**Comment by addisonbgross** [comment]
Are you looking to add a constructor to say Crafty.math.Matrix2D that will store the newely created matrix in the argument passed? eg: var matrix; Crafty.math.Matrix2D( matrix )

**Comment by starwed** [comment]
@addisonbgross  Yes, I think that's the idea.  It would allow for easy recycling of objects in contexts where that makes sense, such as iterations.

We actually already do this with `map.key`.

**Comment by addisonbgross** [comment]
I'll get my people on it

**Comment by starwed** [comment]
Closing this; since it now works for `pos` and `mbr`.  `key` already supported it, and `Matrix2D.setValues` works for that object.
