### ISSUE TITLE
More realistic Gravity

### ISSUE THREAD

**Issue by cawoodm** [craftyjs/Crafty#751]
The Gravity compontent in crafty seems needlessly crude and unrealistic.
1. True gravity is a force which works on your velocity but this "gravity" works directly on `this._y`. This means, no matter what speed you are moving up gravity instantaneously starts moving you down instead of slowing you down.
2. True gravity works from below. My tests have shown my player will stick to platforms from below, apparently from the side and even inside. I am not using the standard movement components but my own `Motion` component which has a simple `speed` method.

Improving item 1 is really simple, 2 perhaps less so. Before I go off and re-invent the wheel, is there a better set of components I should be using for motion and why is Crafty so cra..., I mean crude out of the box in this respect?

![image](https://f.cloud.github.com/assets/498834/2365584/817fa1b0-a6d0-11e3-859c-63ce698173a9.jpg)

**Comment by mucaho** [comment]
see #708

**Comment by cawoodm** [comment]
Good to see someone is working on this thanks! Is there a URL I could use for crafty.js which includes this pull request?

**Comment by mucaho** [comment]
You can clone the `develop` branch and merge commits from [the motion branch of my repository](https://github.com/mucaho/Crafty/tree/refactor_twoway_gravity) to get the latest version of crafty with Motion enabled.
Alternatively, you can download an already built version of Crafty-v0.6.1+ with Motion enabled [from this link](https://app.box.com/s/viwi3tz4s6opcn07l5up).
Keep in mind this is not a final version, as it will undergo change in the near future.

If you would like to see another feature in the future, don't hesitate to make an issue like this one again. If you feel up for it, you can even implement the feature yourself and Crafty's friendly contributors will surely steer you in the right direction in case you need help :)

**Comment by mucaho** [comment]
fixed with #708 .
