### ISSUE TITLE
viewport.follow scaling issue

### ISSUE THREAD

**Issue by mucaho** [craftyjs/Crafty#754]
Possible bug reported in [forum post](https://groups.google.com/d/msg/craftyjs/kHu5MAv19BM/rLlpaM6YCiQJ)

> The problem is that .follow doesn't have .scale in account when it calculates how much it have to displace the viewport to center the entity. I've solved the problem with a custom center method, bound to the 'enterFrame' event of the centered entity:
> 
> ``` javascript
>   this.centerViewport = function(entity) {
>     Crafty.viewport.y = (4/3 * Crafty.viewport.height / 2 / Crafty.viewport._scale) - entity.y;
>     Crafty.viewport.x = (Crafty.viewport.width / 2 / Crafty.viewport._scale) - entity.x;
>   }
> ```

I haven't investigated yet. Is this a bug or intended behaviour?

**Comment by georgii-ivanov** [comment]
It is my problem too https://github.com/craftyjs/Crafty/issues/792

**Comment by mucaho** [comment]
This should have been fixed with #934 now, if you encounter any more problems with it feel free to reopen this issue.

**Comment by mucaho** [comment]
`Crafty.viewport.follow` doesn't center screen after `Crafty.viewport.scale()` is called and before entity is moved. Solution: Listen for `ViewportScale` event in addition to `Change` event to trigger center on entity.

**Comment by mucaho** [comment]
> Crafty.viewport.follow doesn't center screen after viewport transformations

fixed with 871ae034d3a46d9eb5dece6ea03e0f74c861346d
