### ISSUE TITLE
Shapes

### ISSUE THREAD

**Issue by louisstow** [craftyjs/Crafty#77]
Shouldn't be too hard now with `.clip()`. Need a good API. Maybe just a wrapper.

**Comment by maxencefrenette** [comment]
We should think about a whole drawing API, better that would include rects, shapes, circles, fill color and stroke color. But, the API has to to be really good...

**Comment by louisstow** [comment]
I think what would be best is to just give the canvas context and let people have at it.

The problem with this is the redraw regions. Though I think that's less of a problem now that `clip()` is used to draw the dirty regions.

**Comment by sntran** [comment]
Since the canvas draws circle using x,y as the origin, it may mess up with Crafty's MBR, but correct me if I'm wrong.

**Comment by louisstow** [comment]
Closing as it is possible to just draw straight to the canvas provided the `w` and `h` are big enough to contain the shape.

See here: http://louisstowasser.com/post/21479078234/custom-canvas-drawing-in-craftyjs
