### ISSUE TITLE
isometric demo on craftyjs.com website uses very old version

### ISSUE THREAD

**Issue by psvensson** [craftyjs/Crafty#771]
Hi, I'm trying to get the iso demo to work with 6.2 and it draws fine with no errors, but no events seem to trigger - so no mousover markers on grass or stone and no tiles deleted when left-clicking

It looks like the events have been refactored since 4.2 (which the online demo uses) but it's quite hard to find example on how to bind to DOM events as the event tests only use generic reactive stuff. 

Any help appreciated. thx!

**Comment by starwed** [comment]
The version on the website needs to be removed -- it's pretty out of date
at this point.

I'm not sure if it helps, but there is a somewhat updated version here:
https://github.com/craftyjs/demos/tree/master/isometric

**Comment by psvensson** [comment]
Wow, that's beautiful. It seems the only changes I needed to make was to camelcase the events, so click -> Click, mouseover -> MouseOver, et.c  It now works. The only difference is that my left click mouse button doesn't geenrate any events, but the right and middle ones do, so I changed the button check to == 1 instead of == 2.

Other than that it works perfectly with 6.2

**Comment by mucaho** [comment]
Hmm would it be possible to remove all demos from craftyjs.com repo and use them from the demo repo instead?

**Comment by mucaho** [comment]
Ok, moved them from the site repo to the demo repo and cleaned them up. Issue can be closed now I hope, otherwise let us know!
