### ISSUE TITLE
Removing assets request, and possible Crafty.audio.remove bug

### ISSUE THREAD

**Issue by heniotierra** [craftyjs/Crafty#776]
Firstly: 
Crafty seems not to have a way to rid off uneeded(read "not needed anymore") sprites in order to free memory. I think that'd be useful.

~~Also, I know Crafty.audio.remove does that for sounds, except it doesn't. I mean, if you try removing audio like that, and then tell Crafty to play the audio again, it will be played normally, as if it had not been deleted.~~

The same thing occurs if you delete an image from Crafty.assets, and then try to create an entity with that sprite: the entity will be created normally.

Secondly:
I'm sorry if this is just me being dumb.

**Comment by heniotierra** [comment]
It so happens I was using Crafty.audio.remove in a wrong way while testing a feature. Sorry for that. Still, there's that sprite matter. Hm... I'm trying to find how to do that on my own.

EDIT: Guess I found how to do it, but it's only in my head, still have to write and test this thing. My idea to free memory from given sprite sheet is: delete all components with that given image, and then delete the asset. Please, tell me if you know that won't work.

EDIT2: Problem is, I don't know how to get a component's image. Crafty.components().componentName.? I think I'd have to access a closure, which is beyond me... Maybe removing sprite components is not feasible in current implementation?

EDIT3: Yes, I think I got it working! I created a function called removeAssets, which recieves an array of assets as argument, which may be sounds or sprites. But that required making some minor modifications/improvements in three files: loader.js, sound.js and sprite.js. I'll explain these.

**Comment by heniotierra** [comment]
**New function to loader.js**
Created new _removeAssets_ function, which removes audio and sprite images/components passed in array.
**New function to audio.js:**
Created new _getNameFromURL_ function, which recieves audio file URL as argument and returns the name of the audio minus extension. This is used in two parts of loader.js, including in _removeAssets_ function.
**Improvement to loader.js load function:**
_load_ function, when creating new audio, uses the new _getNameFromURL_ function to set as command instead of using the whole file name as currently happens. This is an improvement because, since _load_ will select only the first supported audio file from the list of files for a given sound,  you'd have to check which file was actually downloaded. Let's say you pass to _load_ an array containing ["sound.mp3", "sound.ogg"], "sound.mp3" will be selected, but at the time of playing the sound you'd have to know specifically which of the files was downloaded. With this modification you just have to do _Crafty.audio.play("sound")_, and whatever sound was selected will be played.
**Modification to sprite.js**
In order to be able to know which components are related to a given image, I just added a new property to the sprite components, _imgSrc_, which recieves the path of the image.

I'll do a PR as soon as I get some documentation done for this new stuff, unless you have some objection to that. @starwed ?

**Comment by starwed** [comment]
I'm not so certain unloading assets is something that would really matter in most games, but I guess we should probably still support it...

> Let's say you pass to load an array containing ["sound.mp3", "sound.ogg"], "sound.mp3" will be selected, but at the time of playing the sound you'd have to know specifically which of the files was downloaded. With this modification you just have to do Crafty.audio.play("sound"), and whatever sound was selected will be played.

This is already supported by `audio.add`, I think?  But if you pass an array of sounds to `Crafty.load`, it'll actually load _any_ of them that are supported; it won't stop at the first one like `audio.add` does.

You're certainly right that `Crafty.load` needs an overhaul.  Ideally you should be able to just pass in a big json object, which handles things like picking the first supported audio type, or defining spritesheets.  It should also make it easier to organize assets by using a default set of subdirectories.  (So something like `assets/audio` and `assets/sprites` as default paths to audio and sprite objects.)

I have previously doodled out a design for what I think it should look like; I'll post something about that later.  :)

> I just added a new property to the sprite components, imgSrc,

Be aware that this already exists as the `__image` property.  Maybe it should be documented and almost definitely it needs renaming, but we don't want to duplicate it.  :)

**Comment by heniotierra** [comment]
> This is already supported by audio.add, I think?

Yes, but problem is, `Crafty.audio.add` apparently has a bug that makes the sound be redownloaded everytime `Crafty.audio.play("sound")` is called. Or at least I can see it being requested/downloaded at each `Crafty.audio.play` under network tab in Chromium's dev tools. ~~I don't notice this if I load the sounds with `Crafty.load`~~. It also happens with `Crafty.load`.

> But if you pass an array of sounds to Crafty.load, it'll actually load any of them that are supported; it won't stop at the first one like audio.add does.

Yes, you're right. In my game I had done a thingy to overcome this problem, but had forgotten about it. Hm, what if we check if 'filename minus extension' has already been selected(the first supported file), in order to avoid the other files being downloaded too? _getNameFromURL_ could be used for this.

> default set of subdirectories

Default paths, huh? Thinking of Crafty, that sounds a little alien to me. But that may only be me! About the JSON idea, it doesn't sound bad, but maybe that'll make using `Crafty.load` a bit more complicated?

> Be aware that this already exists as the __image property.

Yes, I saw that, but it's inside a closure, inside init. How'd it be accessed? I don't know. :(

**Comment by heniotierra** [comment]
fixed misinformation in response to first quotation

**Comment by starwed** [comment]
> Or at least I can see it being requested/downloaded at each Crafty.audio.play under network tab in Chromium's dev tools

Hmm, Chrome's devtools can be set to disable the cache when open -- maybe that's what is going on?

> About the JSON idea, it doesn't sound bad, but maybe that'll make using Crafty.load a bit more complicated?

I don't think so.  The JSON object would just look something like:

```
{
  audio:{
    beep: ["beep.wav", "beep.mp3", "beep.ogg"],
    boop: "beep.wav"
  },
 images:["badguy.bmp", "goodguy.png"],
 sprites: { 
    "backgroundsheet.png": <data to pass to Crafty.sprite> 
  }
}
```

It would just be a more structured way to define audio and sprite assets.  By default the audio files would be assumed to be in `assets/audio` and the images in `assets/images` (relative to the main page), but you'd be able to override these if you wanted.

**Comment by starwed** [comment]
> Hmm, Chrome's devtools can be set to disable the cache when open -- maybe that's what is going on?

To elaborate, to play multiples of the same sound, it's necessary to use multiple audio elements that use the same src.  If the url isn't cached, that'll cause the browser to redownload the file each time -- but as long as the cache is working, it should be ok.

**Comment by heniotierra** [comment]
> Chrome's devtools can be set to disable the cache when open -- maybe that's what is going on?

"Disable cache" option is not enabled in Chromium... but that may be a Chromium bug, since the same does not happen under Chrome. I'll try to do a clean install of updated Chromium to see if that solves the problem.

EDIT: Did clean reinstall (erasing config files) of updated (from version 28 to version 31) Chromium, but the problem persists.

> I don't think so. The JSON object would just look something like:

~~Yes, that seems nice. :) I just don't get why use default paths. In your mind, would it be possible to change the directories to something other than the default values?~~

EDIT: Oh, you had already answered that!

Hmm, any hint on how to access closures? I've looked around, but all I find is 'it's not possible'.

Oh, and thank you so much for your patience!

**Comment by heniotierra** [comment]
I did it! I refactored the `Crafty.load` function as you proposed, receiving a JSON, then loading audio, images and sprites, and it's working flawlessly! And with the default folders thing. 
Please don't tell me you were working on that too. 
~~Now I'll adapt the Image component to use the preloaded image, in case it has been preloaded.~~ Image component already works with the preloaded images. Awesome!
Then, I'll rewrite the `removeAssets` function, and finally write the new documentation.

EDIT: Only documentation is left.

**Comment by starwed** [comment]
> Please don't tell me you were working on that too. 

I haven't written any code, but I _did_ spend a long time thinking about the API design.  So, I'll likely be super-picky when it comes to yours.  :P

**Comment by heniotierra** [comment]
Yes, I'd understand that. ;)
Here is my PR: https://github.com/craftyjs/Crafty/pull/777
