### ISSUE TITLE
Use 3D transforms to turn on accelleration

### ISSUE THREAD

**Issue by louisstow** [craftyjs/Crafty#78]
Hack to turn on hardware acc. by applying a CSS3 transform and hiding it. Can also use rotate3d for othe transforms.

**Comment by maxencefrenette** [comment]
I don't think this is needed, IE9 does hardware acceleration on everything and other brower will do so to stay in the race.

**Comment by louisstow** [comment]
Yeah, can still just replace transforms with 3D for now. According to JSGameBench it performs as well as and sometimes faster.

**Comment by louisstow** [comment]
Done
