### ISSUE TITLE
License info should be much more obvious; make GPL version clear.

### ISSUE THREAD

**Issue by ghost** [craftyjs/Crafty#781]
I have found nothing about the license on GitHub. There should be a LICENSE file or something in README.
In the footer website, it is written "Crafty is distributed under the MIT or GPL license". But what parts are under MIT or GPL? What version(s) of GPL?

**Comment by starwed** [comment]
> I have found nothing about the license on GitHub. There should be a LICENSE file or something in README.

You're right... the current licensing info is hidden in a pretty weird place; when you compile `crafty.js` with grunt it adds in a banner that [includes the line](https://github.com/craftyjs/Crafty/blob/develop/Gruntfile.js):

> Dual licensed under the MIT or GPL licenses.

This kind of answers your second question -- the intent is that it's [dual licensed](http://stackoverflow.com/questions/3336161/mit-gpl-dual-license-in-commercial-software) under both, so you someone using the code or forking it could do so under the terms of _either_ license.  But looking at the actual text, it doesn't seem to specify which version of the GPL.

None of the original authors are currently working on Crafty, and I'm not quite sure what to do about the ambiguity of the GPL notice.  The MIT license is pretty permissive, though, and I _believe_ you can even redistribute MIT licensed code under GPL 2 with no problems, so this shouldn't be too much of an issue.  I'll do some more research on the matter!

I'll tag @louisstow  in case he has something to add as the original author!  :)

**Comment by starwed** [comment]
(Just wanted to note that anything under GPL 1 or 2 can use any later version, so it's certainly ok to use a GPL3 license if you want!)

**Comment by ghost** [comment]
Ok, thanks for the answer.
GPL2 is incompatible with GPL3 : https://www.gnu.org/licenses/license-list.html#GPLv2
If we believe the FST, MIT license is compatible with GNU GPL, consequently I do not understand why it is dual-license. https://www.gnu.org/licenses/license-list.html#Expat https://www.gnu.org/licenses/license-list.html#X11License

**Comment by starwed** [comment]
> GPL2 is incompatible with GPL3 

Ah, didn't realise that the "or later" clause was optional.

There is at least on difference: If you want to do something like fork the dual-licensed code under the GPL only, then you don't need to keep the original MIT license around.  If it was MIT-only to begin with, you could redistributed under the GPL, but you couldn't remove the MIT notice on the original code.

**Comment by Jookia** [comment]
There's no GPL license document included so I'm unsure if you even can infer that you can specify the license version as it's in the license itself. It'd be great to get clarification on this, or remove it all together and no longer dual license to avoid confusion.

**Comment by starwed** [comment]
Reading some more about it, I think we should follow the example of jQuery and license only under the MIT.  There's a [blog post](http://blog.jquery.com/2012/09/10/jquery-licensing-changes/) about their licensing change that explains some of the issues.

But basically, if we distribute under the MIT, it's permissive enough that you can then make changes and relicense under the GPL if you'd like.

**Comment by Jookia** [comment]
This is a tricky situation. Given the ambiguity it'd probably be best to the Expat (MIT) license.

**Comment by mucaho** [comment]
Once the decision is made, the `licenses` property needs to be renamed to `license` in the `package.json` file (it's deprecated as described in https://docs.npmjs.com/files/package.json#license).

Both `bower.json` and `package.json` license fields are furthermore invalid, the GPL version needs to be explicitly specified, as per https://spdx.org/licenses/. So if the decision is made in favor of GPL 3, package.json will look like `"license": "(GPL-3.0 OR MIT)"` and bower.json will look like `"license": ["GPL-3.0", "MIT"]`.

(btw once decision is proposed, it needs to be approved by the author of this project - louisstow)

**Comment by mucaho** [comment]
@louisstow  would you prefer to:
- remove the GPL license and let MIT licensees (Crafty's users) [sublicense it as GPL](http://programmers.stackexchange.com/a/105926/111715)?
- or set an explicit GPL version, like `GPL-2.0`, `GPL-2.0+`, `GPL-3.0` or `GPL-3.0+`?

**Comment by starwed** [comment]
Fixed by switching explicitly to the MIT license and adding a license file.
