### ISSUE TITLE
Better documentation for "KeyDown" and related

### ISSUE THREAD

**Issue by gulgiraf** [craftyjs/Crafty#782]
Hi,
I was wondering if there is an alternative to isDown that only triggers at the moment you press the key.

Something like this:
this.isPressed
and this.isReleased

**Comment by starwed** [comment]
You can just hook in to Crafty's "KeyDown" event.  It's described [here](http://craftyjs.com/api/KeyboardEvent.html), though no doubt the documentation could be better.

**Comment by gulgiraf** [comment]
I know, but how about if I want to check doing the EnterFrame event?

**Comment by starwed** [comment]
I'm having trouble seeing what sort of use case the keydown event doesn't cover.  Could you give some more context on what you want to do?

**Comment by kevinsimper** [comment]
@gulgiraf The `Crafty.keys.LEFT_ARROW` will always be true if the key is down. So you can use that to check on in EnterFrame event.
