### ISSUE TITLE
Make private members public so we can duck punch Crafty

### ISSUE THREAD

**Issue by gregtillbrook** [craftyjs/Crafty#789]
Id really like to be able to [Duck Punch](http://www.paulirish.com/2010/duck-punching-with-jquery/) Crafty to make tweaks to my tastes but in a managed way. To give 2 examples; 
1. hacking `Crafty.prototype.addComponent` (so I can solve my need in #786) and 
2. adding some getter methods to Crafty.timer

Unfortunately this is currently impossible because of private variables used in the library e.g.

``` javascript
    // Internal variables
    GUID, frame, components, entities, handlers, onloads,
    slice, rlist, rspace, milliSecPerFrame;
```

Making these members public will not just benefit small hacks like I want to make - it also potentially enables third party mods and addons.

What do you think?

**Comment by sbyrnes321** [comment]
FYI, not all the "private variables" you mentioned are actually really private...

You can get `entities` by `Crafty.debug()`, and you can get `handlers` by `Crafty.debug('handlers')` -- [link to code](https://github.com/craftyjs/Crafty/blob/develop/src/core.js#L1654). You can get `components` by `Crafty.components()`.

`slice` is an alias of `Array.prototype.slice`, and `rlist` and `rspace` are just simple regular expressions defined a few lines later.

I'm not sure about the others.

**Comment by gregtillbrook** [comment]
Ah, thanks for the tip. Id missed `Crafty.components()` and that was the main blocker to changing `addComponent`. Cool.

There are no accessors for the Crafty.timer members unless Im wrong?

**Comment by austinh** [comment]
+1

**Comment by gregtillbrook** [comment]
Would you be interested in a pull request for these changes?

**Comment by starwed** [comment]
Yeah, that would be good.  I think some of them should probably be kind of interconnected -- it would be nice if setting FPS or milliSecPerFrame changed each other (they're just inverses).

I'm not sure there's really a specific reason why all of those are private.  I suppose it's possible it might affect the access speed?  Only way to know that is to test it, of course!

**Comment by kevinsimper** [comment]
@gregtillbrook If you submit a pull request I will look at it! :)

**Comment by kevinsimper** [comment]
Closing this in favour of Pull Requests
