### ISSUE TITLE
Some demos are broken on Google Chrome 12 (dev channel) OSX

### ISSUE THREAD

**Issue by tomasztunik** [craftyjs/Crafty#79]
Haven't tested on Windows, Firefox 4 works fine. Google Chrome throws no errors.

There are problems with Fruit Assassin and Asteroids - in the first one I believe the values for positioning the fruits are wrong and they spawn off the viewport, In the later the asteroids don't move and you are being hit by invisible entities - Maybe something connected to position calculation and lightbox?

**Comment by louisstow** [comment]
So thats a version that isn't released right? That might be a problem with the browser.

**Comment by ponychicken** [comment]
It's definitively a Chrome Bug, I even rolled back to avoid it

**Comment by tomasztunik** [comment]
Good to know - been sitting on dev channel for so long that I've stopped to think about it as unstable version which it is.
