### ISSUE TITLE
Crafty change scene and disappearing components

### ISSUE THREAD

**Issue by austinh** [craftyjs/Crafty#790]
Im getting this error when I change scenes

this._currentReelId is undefined

Also my sprite related components seem to disappear, like anything that was loaded in via the loader assetsObj is being deleted during a scene change. :(

**Comment by heniotierra** [comment]
Hum... I guess you're using this, right? https://github.com/craftyjs/Crafty/blob/develop/src/loader.js

And you're not calling removeAssets at some point, are you?

If you could make a fiddle showing the problem, that would be good.

**Comment by starwed** [comment]
@austinh Just checking -- did you resolve this issue?
