### ISSUE TITLE
Viewport entity following and canvas zoom/scale conflict bug

### ISSUE THREAD

**Issue by georgii-ivanov** [craftyjs/Crafty#792]
Possible bug is reported in forum post: https://groups.google.com/forum/#!searchin/craftyjs/viewport$20follow$20zoom/craftyjs/lApstQMSg3c/lbsI8t-UFtEJ

Please read this topic and fix it.

JsFiddle here:

http://jsfiddle.net/drG26/3/

**Comment by mucaho** [comment]
This should have been fixed with #934 now, if you encounter any more problems with it feel free to reopen this issue.
