### ISSUE TITLE
Entity with Image component won't be resized

### ISSUE THREAD

**Issue by heniotierra** [craftyjs/Crafty#795]
I don't know if this is due to the nature of the Image component or a bug, but if you create an entity with the Image component and then try to change the width or height of that entity, its image won't be resized.

**Comment by kevinsimper** [comment]
Hey @heniotierra 

Yeah, that is because of how the Image component is working. You should use the sprite component instead, it works more the way you would expect :)

**Comment by heniotierra** [comment]
Yes, I know that about sprite component, but was thinking whether this could/should be implemented in case it wasn't a bug. But it's ok. Thanks! (y)
