### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by katin** [craftyjs/Crafty#803]
http://craftyjs.com/api/SpriteAnimation.html

in the "See Also" section, the link:

```
crafty.sprite
```

...brings up a 404. I think it wants to go to http://craftyjs.com/api/Sprite.html ?

**Comment by katin** [comment]
Ah - I think this is the right link:
http://craftyjs.com/api/Crafty-sprite.html

...one case-letter difference~

**Comment by kevinsimper** [comment]
Hi @katin 

I seem to havd fixed it in e7ab075

Is it correct?

**Comment by katin** [comment]
Yes. (I had created the issue just before you responded on the forum... I'll learn my way around yet!)
Tested good.
Thanks! Great response time.  :)
