### ISSUE TITLE
Text code calls Crafty.toRGB() which doesn't exist anymore

### ISSUE THREAD

**Issue by sbyrnes321** [craftyjs/Crafty#804]
The function `Crafty.toRGB()` is called here:

https://github.com/craftyjs/Crafty/blob/develop/src/text.js#L173

but the function doesn't exist anymore. It was deleted in this pull request: https://github.com/craftyjs/Crafty/pull/770

Thanks in advance!

**Comment by kevinsimper** [comment]
Should we removed that function, because you can define the color by just doing `.color('white');`?

Because https://github.com/craftyjs/Crafty/blob/develop/src/text.js#L62 and https://github.com/craftyjs/Crafty/blob/develop/src/color.js#L170 is basically the same functionality.

**Comment by sbyrnes321** [comment]
@kevinsimper : I don't think we can remove textColor() like that. Maybe textColor() is equivalent to color() for canvas text, but it seems to be different for DOM text.

**Comment by kevinsimper** [comment]
Would it be an idea to simplify it? Like CSS is also using `color`
