### ISSUE TITLE
Crafty.js 6.3

### ISSUE THREAD

**Issue by kevinsimper** [craftyjs/Crafty#806]
It is soon time for a new version to be released.

All of the changes since last release can be seen here:
https://github.com/craftyjs/Crafty/compare/release...develop

Some of the things that has to go into the Changelog:
- Removed support for old browsers (IE7 - Getter Setters)
- New Crafty Component `Model` which means you can bind to values changing like Backbone events
- New function `Crafty.pixelart(true);`
- Improved loader functionality
- Remove of Craftycomponent.com module loader
- Lot of bugs fixed and tests added
- Improved tests setup

What more should we add to the changelog?

**Comment by sbyrnes321** [comment]
Sure! As long as it says more explicitly how `Crafty.load()` has changed. For example, replace `Crafty.load(['foo.png', 'bar.png']);` with `Crafty.paths({'images': './' }); Crafty.load({'images': ['foo.png', 'bar.png']});`

Don't want anyone to overlook this important incompatible change!

**Comment by heniotierra** [comment]
Before the release, maybe [this PR](https://github.com/craftyjs/Crafty/pull/813) should be merged?

**Comment by kevinsimper** [comment]
@sbyrnes321 I changed it so that you do not have to define paths as this would as you point out break backward compatibility.

But check out the testing release :)
