### ISSUE TITLE
Cannot read property 'elem' of undefined 

### ISSUE THREAD

**Issue by TatianaC** [craftyjs/Crafty#808]
I'm working through  thorough tutorial on building a game with Crafty: http://buildnewgames.com/introduction-to-crafty/ and I've run into a snag with the Crafty.js code. In my console, it says this: 

Uncaught TypeError: Cannot read property 'elem' of undefined crafty.js
Crafty.extend.canvas.init crafty.js
Crafty.c.init crafty.js
Crafty.fn.Crafty.addComponent crafty.js
Crafty.extend.e crafty.js
(anonymous function)

And this is the line that problem was referring to: Crafty.stage.elem.appendChild(c);

I'm not entirely sure what the problem is or how to fix it or even what code you need to see to get a better understanding of what's going on. But thanks for your help!

**Comment by kevinsimper** [comment]
What code are you trying to run?

The code is quite lengthy, but i would very much like to help you!

**Comment by kevinsimper** [comment]
I am going to close, but if you have anything to add, you are welcome to write here again!
