### ISSUE TITLE
relative positioning breaks mouse events

### ISSUE THREAD

**Issue by gisly** [craftyjs/Crafty#814]
Hi!

I've got a strange issue with Crafty. I've already written about it to the mailing group.

I'm developing a game with CraftyJS v. 0.6.2.
Recently, I've had to make one html element positioned relatively. I did in a very dumb way, simply creating it as a Crafty entity and then setting position to relative.
However, this code breaks all mouse events for other entities in Crafty (no reaction to click, drag etc).
Here is an example:
http://jsfiddle.net/gisly/k3auxuej/1/

In Chrome and Firefox on Windows I cannot drag the "DraggableCard" entity normally. Actually, the drag zone to drag it is way above the element.

However, if I comment out the "$(".relativelyPositioned").css('position', 'relative');" line, I can drag the element normally.

**Comment by starwed** [comment]
I'm not a big CSS expert.  But using Firefox's dev console, I can see that by making the div have `position:relative` it changes the dimensions of the `#cr-stage` element.  Normally it simply has dimension 0, but apparently with a `position:relative` child this changes, and it takes on the dimensions of that object.  (I'd assume if you had multiple such children, it would take on min dimensions to enclose them.)

This then messes up all the calculations that are used for figuring out mouse position and the css transforms.

The tempting answer is just "don't do that", but if we're obviously doing something dumb here, I'd welcome a patch!  :)

**Comment by kevinsimper** [comment]
It seems that there is a problem with Translate3d and position that gives some funny results, https://www.google.dk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=translate3d+position+relative

I do not see a solution just like, but you are welcome to open this issue again if there is a way to fix it.
