### ISSUE TITLE
Canvas elements aren't stroke()'d

### ISSUE THREAD

**Issue by statico** [craftyjs/Crafty#82]
I created a quick border component (in CoffeeScript):

```
Crafty.c 'Border',
  _borderWidth: 0
  _borderColor: ""

  init: ->

    @bind 'draw', (e) ->
      if e.type == 'DOM'
        e.style.borderWidth = "#{@_borderWidth}px"
        e.style.borderStyle = 'solid'
        e.style.borderColor = @_borderColor
      else if e.type == 'canvas'
        e.ctx.strokeStyle = @_borderColor
        e.ctx.lineWidth = @_borderWidth

  border: (@_borderWidth, @_borderColor) ->
    this.trigger 'change'
```

The DOM implementation works fine but the canvas implementation doesn't work. I've tried adding a `stroke()` call in the `draw` callback and in `DrawManager`'s loop, but no luck.

**Comment by louisstow** [comment]
The problem is most likely due to the redraw regions. I need to think of a way to allow custom canvas drawing that automatically gets redrawn.
