### ISSUE TITLE
Mouseup event with right button ends drag

### ISSUE THREAD

**Issue by rhys-vdw** [craftyjs/Crafty#820]
The `Draggable` component only starts a drag on _left_ mouse down, but will end it on either _right or left_ up.

I'd like to be able to right click while dragging something around. It seems natural to be able to do so. If you agree, I can submit a pull request with a fix.

[Relevant code here](https://github.com/craftyjs/Crafty/blob/e7ab075da3460b4d9ebda6004bc44d42d1e9f582/src/controls.js#L521-L535)

**Comment by starwed** [comment]
Playing around, I _think_ this matches what OSX seems to do with drag/drop.  But it's a little hard to tell with a trackpad -- maybe you could test how your OS handles drag operations?

It seems there are some differences between dragging to change the location continuosly (like dragging a window around) and dragging which has a discrete target.  The former isn't interrupted by a right click, but the latter is.  But maybe these aren't general rules, and there's just inconsistency?

We should probably mirror how HTML5 drag/drop events work, but I couldn't find these sorts of details in the spec.  (Might just be missing it.)  Perhaps the intention is to match OS behavior.

**Comment by rhys-vdw** [comment]
I'm not sure about HTML spec 5 drag/drop behaviour. [This w3schools demo](http://www.w3schools.com/html/html5_draganddrop.asp) allows you to right click while dragging (in Chrome under Windows 7).

Both windows and OSX permit a right click while dragging windows around. Neither will open a context menu while doing so.

Finder allows right click while dragging files with no effect.

Windows Explorer will cancel a file drag with a right click, sending the item being dragged back to its original location. It also performs the right click event on the object being dragged, opening its context menu under the mouse (even though the icon has disappeared).

My use case is to be able to drag and drop an item, but to be able to rotate it with right click while dragging.

I think the best solution is to stop the drag only on left click. The API makes it trivial to add in a event listener that calls `stopDrag()` on right click, but difficult to go the other way. I'd essentially have to duplicate the entire `Draggable` component to get the behaviour I'm after.

**Comment by starwed** [comment]
> I think the best solution is to stop the drag only on left click. The API makes it trivial to add in a event listener that calls stopDrag() on right click, but difficult to go the other way. I'd essentially have to duplicate the entire Draggable component to get the behaviour I'm after.

That sounds pretty reasonable to me.  If you want to submit a PR, go for it!
