### ISSUE TITLE
Crafty.stop(true) removes all components with no way to reload them

### ISSUE THREAD

**Issue by sullivanpt** [craftyjs/Crafty#827]
According to the docs one should be able to call "Crafty.stop(true); Crafty.init();" -- (for example if one wants to launch a new game hosted in SPA).

However, Crafty.stop(true) calls initState() [core.js:940] which resets components to the empty object [core.js::48].  And since the built in components only register themselves when first loaded (e.g. Crafty.c("2D", ... ) [2D.js::77]), they are gone with no hope of returning without a page refresh.

I'm not sure what's supposed to happen here. In a simple fix Crafty.stop(true) would not flush components. Even better maybe, components would register themselves into a 'staging' area so game developers can explicitly cherry-pick only the components they want to register into the engine?

**Comment by kevinsimper** [comment]
If you do `Crafty.stop(true);Crafty.init()` you would have to run the code for the entities again, you could do that by wrapping your entites in a function so you can run them easy again.

**Comment by sullivanpt** [comment]
I agree the approach of reloading my own entities is correct, but the reason I opened this ticket is because I cannot reload the default entities like '2D' etc. without modifying the crafty.js file.

Sent from my Windows Phone

**Comment by kevinsimper** [comment]
Do you have some code that you can show?

**Comment by starwed** [comment]
The code is in `initState()` -- it literally just sets the `components` map to an empty object, thus preventing you from using any of them.

Seems like there should probably be a way to stop crafty without destroying the components/etc -- we could have a separate `destroy` method for those who wanted it.

**Comment by kevinsimper** [comment]
If you call `Crafty.stop();` without the true, dosn't it do that?

**Comment by sullivanpt** [comment]
No, I'm looking for a way to reset crafty to its initial startup state. Craft.stop() just halts the engine but doesn't unload the dynamic DOM elements, my custom components etc.

I tried working around this by copying code from scene clean up, but it doesn't clean up enough internal state. (sad face).

**Comment by sullivanpt** [comment]
Following up on this thought. I think the right thing to do is to change all the built in components to register themselves in an additional list named builtIn. Then in Crafty.init, instead of setting member variables components to empty, it would set it to built in, thus recreating original loaded state. However, the fly in the ointment: If a component maintains any state internally (closure variables) these would not be reset; I'm not sure how often internal state is kept for a component?

**Comment by starwed** [comment]
> However, the fly in the ointment: If a component maintains any state internally (closure variables) these would not be reset; I'm not sure how often internal state is kept for a component?

Generally, component's shouldn't be keeping internal state like that; the only exception I can think of is perhaps the components generated by `Crafty.sprite`, which include some information about the image texture through a closure.

Is there a reason you want to unload the custom components at all?  What sort of internal state is giving you issues?

**Comment by sullivanpt** [comment]
I experimenting with building a single page application (no full page refresh) that hosts multiple distinct games.  Admittedly this is pretty far afield of a normal use case, but the docs for Crafty.stop(true) imply it should work.  What else is Crafty.stop(true) useful for?

**Comment by kevinsimper** [comment]
I can see what you mean now, we could do a better reset, but i am a little bit twisted about what we should keep, I am more for reseting all to zero and that you then have to register your components again yourself.

**Comment by kevinsimper** [comment]
I propose that we take out the ´components´ from the `initState` function.

That can have some side effects, but you will actually be able to do `Crafty.stop(true); Crafty.init()`.

**Comment by sullivanpt** [comment]
Yes, I agree removing 'components' from initState is the most expedient solution.  It solves the basic use case, i.e. this code snippet will no longer crash:

<pre>
  Crafty.stop(true);
  Crafty.init();
  Crafty.e('Color')
    .color('rgb(255,0,0)');
</pre>

The downside is one can no longer remove built in or custom components. But stop(true) is already a rare edge case, we don't need to complicate it.  And the removal of components could be handled with a new construct like 'Crafty.c("2D", null)' if someone asks for it.

**Comment by kevinsimper** [comment]
I have submitted a pull request that solves the problem.

When i did the test all the other test failed when I did `Crafty.stop(true)`, so that was interesting.
