### ISSUE TITLE
Its possible to unbind unrelated function from entity

### ISSUE THREAD

**Issue by mpetrovic** [craftyjs/Crafty#83]
If there is one handler for a given entity on an event, and you try to unbind a different handler, the 1 handler will be removed. 

Example:
http://jsfiddle.net/ZZATL/
Check your console to see it happening.

This is counter-intuitive. Unless I specify that function, or all functions, a handler shouldn't be unbound. If I try to unbind a specific function, under no circumstances should something else be unbound.

**Comment by sorenbs** [comment]
I agree and have changed the behavior. The code is available in the snapshot: https://s3.amazonaws.com/craftyjs/crafty-SNAPSHOT.js

If you want to test it, you should be aware that some things have been renamed as described in the blog.
