### ISSUE TITLE
Black line appears in top border of sprite

### ISSUE THREAD

**Issue by heniotierra** [craftyjs/Crafty#836]
The couple kissing is a sprite animation and the moon is also a sprite, using canvas for everything:
https://drive.google.com/file/d/0B_OhLP63F8vZdF9tUHZFLUhzTW8/view?usp=sharing

**Comment by starwed** [comment]
Perhaps it's #711?  That caused lines of the background color to appear around sprites in some circumstances, in particular if you've zoomed the viewport.

There's a [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=967142) that prevents us from making a universal fix to the issue, unfortunately.

**Comment by heniotierra** [comment]
Yes, that must be the same issue... I'm also using zoom in this scene. The problem appears in both Firefox and Chrome. I guess I should close this?

**Comment by heniotierra** [comment]
Confirmed that the color of the line changes according to background color. Closing as duplicate...
