### ISSUE TITLE
Multiway disable control issue

### ISSUE THREAD

**Issue by VHonzik** [craftyjs/Crafty#842]
Good afternoon everyone,
I used Crafty in recent Ludum Dare (was very content with it) and discovered a small annoyance. I would not necessary label it as a bug.

When entity is using `Multiway` component and `.disableControl` is called, the `_movement` attribute is still updated in `_keydown` function when a button is pressed. While the entity is not moved because of the first line in `_enterframe`, user code can still rely on  `_movement`. Prime example of such usage is  [Darren Torpey excellent tutorial](http://buildnewgames.com/introduction-to-crafty/) linked from Crafty website, where `_movement` is used to stop movement on collision.

I believe it would make sense to not update the movement in `_keydown`  using the same check as in `_enterframe`:

``` javascript
if (this.disableControls) return;
```

I would be happy to get my hands dirty and submit pull request with a fix, but I wanted to check if is not an intentional design decision.

**Comment by starwed** [comment]
That seems pretty reasonable to me.

(I guess I should point out that at some point, those components will probably be completely replaced.)

**Comment by VHonzik** [comment]
> (I guess I should point out that at some point, those components will probably be completely replaced.)

Is it worth doing then? 

Also I checked the unit tests and they are counting on the current behavior.

**Comment by starwed** [comment]
> Is it worth doing then? 

As long as the work isn't too involved, I think small improvements still make a lot of sense.

> Also I checked the unit tests and they are counting on the current behavior.

The description of `disableControl` claims that the component will ignore keyboard input, so it should be ok to change the tests.  :)

**Comment by VHonzik** [comment]
Fair enough :) I am on it then.
