### ISSUE TITLE
KeyDown only fire once

### ISSUE THREAD

**Issue by sorenbs** [craftyjs/Crafty#85]
Change behavior of KeyDown to only fire once for every time a key is pressed. The current implementation fires at the same rate a pressed key would cause the browser to type the letter in a text field, which is inconsistent across browsers and shouldn't be exposed by Crafty.

**Comment by sorenbs** [comment]
As i didn't fully comprehend the flow of the code my 'solution' had the unwanted implication that if two entities which where created with the Keyboard component, only one would receive KeyDown event.
This is because the two entities would receive separate events from the browser, and the entity receiving the first event would mark that key as already pressed down, preventing the other entity from firing a KeyDown event.
My proposal is to move the keyboard events out of the keyboard component and register it at Load just as the mouse events are. Then there will be only one keydown event from the browser, and we can use Crafty.trigger('KeyDown", e) to notify all interested entities. This makes sense as keyboard really events global.
Any thoughts?

**Comment by mpetrovic** [comment]
Sounds good. It should also be easier on memory and faster in general since every keyboard object won't have a pair of event handlers to go with it.
