### ISSUE TITLE
Speed docs on website doesn't match code

### ISSUE THREAD

**Issue by wallaceicy06** [craftyjs/Crafty#857]
When I was reading the docs on [multiway](http://craftyjs.com/api/Multiway.html), the section on speed adjustment seemed a bit confusing. It suggested that speed could be altered after the fact by calling

```
 entity.speed(2);
```

but after reading into the [code](https://github.com/craftyjs/Crafty/blob/988730189ca2a63fdd62d2cf5b5d990bcf613e14/src/controls/controls.js#L867), the `speed` method actually expects an x, y tuple. Maybe I'm misreading the docs on the website, but I could not find any literature on the latter method.

**Comment by starwed** [comment]
Yeah, looks like it's missing the documentation for that method signature.

Calling `entity.speed(2)` does work, though, because if the first argument isn't an object it creates one with `x` and `y` properties equal to the requested speed.

**Comment by heniotierra** [comment]
This has been fixed already, by [this commit](https://github.com/heniotierra/Crafty/commit/9aac89eea4c0e9e7e112568469dce52cd37794f5).
@starwed Maybe you're thinking of `.multiway`? It does what you said.

**Comment by starwed** [comment]
Yup, was thinking of `.multiway()`.

Since it is already fixed I'll go ahead and close, but thanks for the report!

**Comment by starwed** [comment]
Oh, I guess I should clarify for OP: since the docs are generated from the source code, a bug that's fixed there won't show up in the official docs right away.  It'll be fixed when we push docs for the next release.

And thanks for opening the issue!  :)
