### ISSUE TITLE
extend with objects

### ISSUE THREAD

**Issue by sorenbs** [craftyjs/Crafty#86]
When a component has a private property that is an object, is is shared among all entities. See this example:

```
Crafty.c("Aa", {
            _priv: { a:0 },
            _c: 0,

            aa: function() {
                this._priv.a++;
                console.log("a: " + this._priv.a);

                this._c++;
                console.log("c: " + this._c);
            }
        })

        Crafty.e("Aa").aa();
        Crafty.e("Aa").aa();

Output:

a: 1
c: 1
a: 2
c: 1
```

I think this not what you expect in most cases. 
I think we need to implement deep copy in the extend method (like http://my.opera.com/GreyWyvern/blog/show.dml/1725165). 
I gave this a quick try, but either i made some mistake in the implementation, or Crafty depends on this behavior internally.

A workaround is to create the object in init instead of doing it declaratively as above.

**Comment by louisstow** [comment]
It has it's benefits but yes it does get annoying. It would be nice if there was a way to share data between entities but most of the time users would want a deep copy.

**Comment by sorenbs** [comment]
Maybee there could be some explicit way to scope a variable to the component? A simple way to do it would be to have a convention that if a variable is called, say componentStore the deep copy algorithm would copy it by reference instead, making it possible to use that as a component scoped object to put shared stuff in.

**Comment by louisstow** [comment]
I like that idea.

**Comment by mpetrovic** [comment]
To be honest, I thought that's what closures were for. Private shared variables go in a closure. Private unique and public variables go in the component itself. 

That's the impression I got from looking at Crafty itself, at least. Closures are a new concept for me.

**Comment by sorenbs** [comment]
Just to be clear:

I think we all agree that when doing

```
Crafaty.c("MyComp", {
    a: { }
}
```

a should not be shared among all entities with this component (as it is now).

Some times you want to be able to create an attribute that is shared among all entities with the component. My proposal is to enable this:

```
Crafaty.c("MyComp", {
    componentStore: { a:"I am shared" }
}
```

I think this will be very easy to understand and use.

**Comment by atimmer** [comment]
just for my reference in classic OOP, this would be class variables wouldn't they?

In that case having a reserved variable in the component like 'componentStore' is a good idea.

**Comment by louisstow** [comment]
I agree. But perhaps a more descriptive name like `shared`

**Comment by sorenbs** [comment]
For some reason i never got it working going the deepcopy route. I think it broke something in Crafty that relied on the existing behavior. Will close this issue for now, but feel free to reopen.

For reference, the workaround is to instantiate the object in the init function instead.

**Comment by austinh** [comment]
I've been searching forever to find why my SpecialPhysics component velocity and acceleration variables were applying to ALL of the entities with that component. It was because in the components themselves i was declaring the variables like this:

Crafty.c("Physics", {
    accel: { x: 0, y: 1 },
    velocity: {x: 2, y: 2}
});

Which meant, when i updated the a component that contained the physics, that it was all shared. This caused quite a bit of annoyance, and DAYS to debug. It wasnt until I found this thread that i found the actual variables were shared. Crafty needs a deep copy extend method. There are too many instances in gaming where this is a necessary behavior. If this wont be implemented, this should at least be in the docs.
