### ISSUE TITLE
no TouchCancel event

### ISSUE THREAD

**Issue by heniotierra** [craftyjs/Crafty#860]
There's no call to `.trigger("TouchCancel")`, although this event is mentioned in the documentation. Sorry, forgot to add it!

This can be solved in three ways: treating `touchcancel` as `touchend` (as we do for `touchleave`) or addding the call to `.trigger("TouchCancel")` or removing the mention to the event from the docs.

**Comment by heniotierra** [comment]
Ahem, I found another error in the docs. Will send fixes for both problems...

**Comment by heniotierra** [comment]
These are the fixes for the two problems mentioned above
https://github.com/craftyjs/Crafty/pull/864 https://github.com/craftyjs/Crafty/pull/865

**Comment by starwed** [comment]
Should now be fixed, so closing.
