### ISSUE TITLE
Cannot draw image with canvas

### ISSUE THREAD

**Issue by atimmer** [craftyjs/Crafty#88]
If I have an object with the components 'image' and 'canvas' I don't see anything even if everything is at the right settings. Then I digged a bit in the Crafty source and found this (which should draw an image):

//skip if no image
if(!this.ready || !this._pattern) return;

var context = e.ctx;

context.fillStyle = this._pattern;

//context.save();
//context.translate(e.pos._x, e.pos._y);
context.fillRect(this._x,this._y,this._w, this._h);
//context.restore();

As far as I know you can draw images on canvas with drawImage, not with fillRect.
I think there should be something like this:

context.drawImage(this.img, this._x, this._y);

PS. I tried to fix it but I couldn't get it working. So I don't have something like "Input this here and here and it will work"

**Comment by louisstow** [comment]
The reason for `fillRect` is because `image` is used to create repeating backgrounds. Could you link to a jsfiddle so we can have a look?

**Comment by atimmer** [comment]
Here is a jsfiddle:

http://jsfiddle.net/3wHXJ/16/

**Comment by adamaflynn** [comment]
Use "Canvas" and "Image" as your component names and it should work.

**Comment by adamaflynn** [comment]
Although, playing around with that demo, the x/y properties seem to be x/y of the image itself (not the canvas). Is this by design? I expected x/y controlled where on the canvas the image would be rendered instead of just cropping out part of the image.

**Comment by atimmer** [comment]
That fixes it and on the other issue, I think you can fix it this way: (uncommenting the lines and using 0 and 0 instead of x and y)

context.save();
context.translate(e.pos._x, e.pos._y);
context.fillRect(0,0,this._w, this._h);
context.restore();

**Comment by ponychicken** [comment]
Components were renamed to uppercase. Use Crafty.e("2D", "Image", "Canvas");

**Comment by ponychicken** [comment]
Opened #90 for the other problem
