### ISSUE TITLE
Update documentation/site generation

### ISSUE THREAD

**Issue by starwed** [craftyjs/Crafty#880]
I've been working on updating both how we generate the api docs, and how we display them.  The current status:
- I first wrote a script that takes our source code, and converts the jsdoc like syntax to a json object.
- Then I wrote some a little one-page app that uses React for converting json to html, and does layout with Bootstrap derived CSS/LESS.  You can see the makeshift result [here](http://ludonomicon.com/crafty/api/public/r3.html).  (There are still a few quirks (such as overly long method names overlapping!) but it's at least functional.)

Supposedly the various technologies I used allow server-side rendering, so we could still serve the docs as a set of static html files.  The dynamic approach will probably be nice when checking documentation you've just edited, though!

I'm not sure how we should plan on integrating any of this either into the repo, or the craftyjs.com site.

I'm also not super tied to any of the technologies above -- if someone could get jsdocs producing good output, or thought that angular/ember/etc would work better than react, that'd be fine!  I just wanted to get something working.

I'll probably open a PR so that folk can see the work I've done so far, but I also wanted to open an issue specifically for discussing this.

**Comment by mucaho** [comment]
I don't know which is the best approach, but here are some alternatives to consider
- [jsdox](http://jsdox.org/) converts jsdoc to markdown  
  an example page can be seen [here](https://github.com/mucaho/npm_crafty/wiki/Net#npm_craftynet), although it didn't render [custom type definitions](http://usejsdoc.org/tags-typedef.html) and [externals](http://usejsdoc.org/tags-external.html) for me, but I highly doubt Crafty documentation uses these features
- [jsdoc-react](https://github.com/nullobject/jsdoc-react) converts jsdoc to minimal, readable html  
  an example can be seen [here](http://nullobject.github.io/fkit/api.html), in my opinion very clean  
  it also uses react and bootstrap under the hood, perhaps interesting for you to take a look at  
  also doesn't render some exotic jsdoc tags, but I doubt Crafty uses those anyway

**Comment by starwed** [comment]
The problem (I've had in the past) with jsdocs is that Crafty doesn't use jsdocs tags the "correct" way.  It would require a bit of effort to switch over.  @kevinsimper  made a start of such a conversion #807.

I just found it easier to write my own parser than to either customize jsdocs or alter our own documentation, but I certainly don't have any problem with someone else making the attempt.  :)

I also think that once we have a source->json->docs pipeline set up, it'll be relatively easy to swap out just part of it.

**Comment by starwed** [comment]
I now have a working version of craftyjs.github.com that uses node+assemble to produce the site, rather than relying on github's jekyll backend.  That basically just required reorganizing things and tweaking some syntax here and there, but I also switched to using highlight.js instead of pygment.  (Highlight is what I was using in the updated api docs, so they'd be able to share a stylesheet this way.)

If we go this route, would it make more sense for the site generation code to live in the github pages repo, its own repo, or this repo?  @kevinsimper

**Comment by starwed** [comment]
I opened craftyjs/craftyjs.github.com#52 to demonstrate the changes I made.

**Comment by starwed** [comment]
I now have working
- A version of the main site that uses bootstrap for layout, combining their LESS files with some of our own to style the site
- A script that generates a json file from our source files
- A script that uses React to generate the api docs from json

I think I'll simply push the updated site layout sometime quite soon -- if there are problems with it, that'll be concrete motivation to fix them!  I have some uncertainty about the best way to organize all this, but again, that'll probably be easiest to talk about once it exists.

**Comment by starwed** [comment]
I updated [craftyjs.com](http://craftyjs.com).  I'm certainly not a graphic designer, so I'm pretty open to suggested changes to the appearance, logo, etc.

**Comment by mucaho** [comment]
Looks good. The individual methods in the API documentation could use a little emphasis/color/spacing in my opinion.
EDIT: `grunt api` doesn't do anything for me, how do I generate the documentation to check if I made any errors?

**Comment by starwed** [comment]
Currently you'd have to run `grunt api` in the Crafty repo, then manually copy the files to `craftyjs.github.com/source/api`.   Then `grunt` in the site repo will build the actual webpages.

What I've pushed so far was only the general site restyle; the api needs more semantic info, which means changing how its generated.

**Comment by starwed** [comment]
Oh, and I want to include a way to directly view the api docs in the main Crafty repo; hopefully that'll just meaning including a slightly tweaked version of the react script.

**Comment by starwed** [comment]
I updated the [api docs](http://craftyjs.com/api) on craftyjs.com.  Let me know if you spot any issues!  (You might have to force refresh to see the new styles?)

There are some _existing_ issues with how documentation is formatted that the new style makes more obvious, but we should fix those in the source.

**Comment by mucaho** [comment]
~~So there's no way to view the final version locally? Can you view the bare-bones to see if it got parsed correctly (like signature, example, etc..)?~~ That's what #906 is for :)

I like it, especially the different color backgrounds for different parts of documentation. The gray background feels a bit sad, what do you think about a [third violet-ish color](http://paletton.com/palette.php?uid=53p0u0k8fSD0d%2BZ40YzcKJFh4y2)?

![sample_color](https://cloud.githubusercontent.com/assets/3935691/7682162/4af15122-fd76-11e4-98c9-b2810c74df9d.png)

**Comment by starwed** [comment]
I'd prefer grey for the examples, since they have color added by the syntax highlighting, and that grey is presumably optimized for contrast with the colors.  I'm using a css file for highlight.js that's supposed to match github's highlighting -- you can browse through some of the available styles [here](https://highlightjs.org/static/demo/).  Maybe there's one that would better fit in with the rest of the site, but I am a bit partial to the neutrality of the grey.

**Comment by starwed** [comment]
> Can you view the bare-bones to see if it got parsed correctly (like signature, example, etc..)?

It'll be pretty easy to modify the React script in the site repo to work as an offline viewer for the json file.  (That's basically how it _started_ before I made it into a static generator!  Just a matter of making it play nicely as a grunt task.)

**Comment by ashes999** [comment]
:+1:  great job on the new documentation, it feels more clear and readable. The colour difference between blue/green is a bit too subtle, but it works.
