### ISSUE TITLE
Crafty.stop generates invalid call to requestAnimationFrame

### ISSUE THREAD

**Issue by letmaik** [craftyjs/Crafty#887]
Tested with Firefox. Whenever Crafty.stop() is called I get a `TypeError: Argument 1 of Window.requestAnimationFrame is not an object.` inside the dev console at line `requestID = onFrame(tick);` of this block:

```
                    tick = function () {
                        Crafty.timer.step();
                        requestID = onFrame(tick);
                        //console.log(requestID + ', ' + frame)
                    };
```

I guess when stop sets tick to null then in the last run of that block it tries to invoke onFrame(null) which fails.

**Comment by starwed** [comment]
Hmm, I can't reproduce this.  What browser/environment are you encountering the error in?

**Comment by letmaik** [comment]
Firefox and Chrome, Windows and Linux. Can you see the error when you go to http://neothemachine.github.io/hungrymonkey/ and just wait until the timer goes to 0?

**Comment by starwed** [comment]
Yeah, I do see it then.  Looks like it occurs only when `Crafty.stop()` is called from within the game loop, which makes sense.

**Comment by starwed** [comment]
The fix was pretty simple, so I went ahead and opened  a PR.
