### ISSUE TITLE
Clarify error on unknown required component

### ISSUE THREAD

**Issue by ashes999** [craftyjs/Crafty#891]
When you try to create a entity that requires a component which doesn't exist, you get a cryptic error (`Uncaught TypeError: undefined is not a function`). Can this be reworked for a more friendly error?

Simplest repro case:

```
Crafty.e('2D, OtherTag', {
  init: function() {
    this.requires('SomethingThatDoesntExist');
  }
});
```

Instead of this error, how about a helpful error message, such as `Can't find required component "SomethingThatDoesntExist" for entity "2D, OtherTag"`?

**Comment by mucaho** [comment]
I can't reproduce the error message. Which crafty version and browser do you use? Adding an undefined component _should_ never produce an error and is even suggested in tutorials.

**Comment by ashes999** [comment]
You're right, it doesn't repro with this minimal case. I'll keep an eye open and post a complete example once I can get this error. It happened to me a few times already.

I'm using Crafty v0.6.2 with Google Chrome.

**Comment by mucaho** [comment]
I just noticed, that your repro example is a little bit weird:
Do you want to create an entity?

``` js
Crafty.e('2D, OtherTag');
```

or do you want to create a component?

``` js
Crafty.c("MyComponent", {
    init: function() {
        this.requires('SomethingThatDoesntExist');
    }
});
```

**Comment by ashes999** [comment]
I think this happened when I was trying to create an entity. You can add custom code directly to entities (you don't need to put everything in components) -- or maybe I'm just confused.

I'm going to close this until I can repro it.

**Comment by mucaho** [comment]
This is `Crafty.e` source

``` js
e: function () {
    var id = UID();
    entities[id] = null;
    entities[id] = Crafty(id);

    if (arguments.length > 0) {
        entities[id].addComponent.apply(entities[id], arguments);
    }
    entities[id].setName('Entity #' + id); //set default entity human readable name
    entities[id].addComponent("obj"); //every entity automatically assumes obj

    Crafty.trigger("NewEntity", {
        id: id
    });

    return entities[id];
}
```

`addComponent` accepts either single string argument with comma-separated component names or multiple string arguments representing each component name respectively

``` js
this.addComponent("2D, Canvas");
this.addComponent("2D", "Canvas");
```

Unless I'm confused ( :) ), you can't add custom code directly to entities. However, in the current development build you can create systems with `Crafty.s`. You can read about it in the initial PR #878 .

EDIT: If you want to add custom code you usually do it outside of the constructor

``` js
Crafty.e('2D, OtherTag')
         .requires('OtherTag')
         ...
```

**Comment by starwed** [comment]
Yeah, an entity is just a collection of components -- the way to add custom code is to define a new component and add _that_ to the entity.

(I guess you can also use `.extend()` to add properties and methods, but that won't work for fields with special meanings like `init` or `remove`.)
