### ISSUE TITLE
Holding jump makes you fall through the floor (dev)

### ISSUE THREAD

**Issue by ashes999** [craftyjs/Crafty#894]
I just cloned and built CraftyJS locally, in order to get the "double jump" example from the `controls.js` file to work. It works!

One problem I ran into: if you jump (or double-jump), and hold down the jump button until you land on the ground, and _then_ release it, you fall through the floor. This occurs regardless of if you jump or double-jump.

I can provide some code if this is not trivially reproducible for you (I have to check in some local changes first on my project).

**Comment by mucaho** [comment]
Unfortunately, I could not reproduce this :( Does this happen on first jump when you create the game or also on subsequent jumps?

Does this [minimal example](https://github.com/craftyjs/demos/blob/master/devDemos/example_doublejump.html) work for you (make sure to replace the link to crafty library)? If it works, maybe you could try to adapt the code so the bug shows up.

**Comment by ashes999** [comment]
Yes, that example works for me, even with my local build of Crafty. I'll try to adapt it to see what differences cause this behaviour. If this example works, it may be a problem in my code.

**Comment by ashes999** [comment]
Got it. The bug occurs if I add logic to also jump when you press space.  

I'll revert my code and stick to WASD. Thanks for the demos link, that's very useful to me.
