### ISSUE TITLE
Twoway - allow keys for jumping to be configurable

### ISSUE THREAD

**Issue by mucaho** [craftyjs/Crafty#895]
Feature request from [forum post](https://groups.google.com/forum/#!topic/craftyjs/KD5Femb99JM).

**Comment by petarov** [comment]
Whops, didn't see this issue. I added [something here](https://github.com/craftyjs/Crafty/pull/898). Let me know, if it's good enough. ;)

**Comment by mucaho** [comment]
fixed in #898 / #900
