### ISSUE TITLE
Improve checkHits and onHit functionality

### ISSUE THREAD

**Issue by mucaho** [craftyjs/Crafty#899]
Feature request from [forum post](https://groups.google.com/forum/#!topic/craftyjs/GOQvUYrc0jU)

Without changing the ease-of-use of `checkHits` and `onHit` `Collision` methods, they could also inform user that the colliding entities, having the desired component, have changed. 
Possibilities include introducing a new event that is fired each time the colliding entities change (e.g. `HitOn(component)` -> `HitChange(component, oldestHitList)` -> ... -> `HitChange(component, newestHitList)` -> `HitOff(component)` ), or restructuring the event completely (e.g. seperate `HitOn(component, entity)` & `HitOff(component, entity)` events for each colliding entity.)

**Comment by grozen** [comment]
This can definitely be useful, but won't using `resetHitChecks` from the respective `HitOn` handler be sufficient? This will cause additional `HitOn`s to fire even though the collision is still "active". While not as convenient, it will keep the performance penalty an opt-in affair, as what we are essentially suggesting will incur some sort of penalty. Not a very big one, mind you, though I guess that is ultimately up to how many different entities you are colliding with and need to track.

**Comment by mucaho** [comment]
Very fair point regarding the performance - we would need to keep track of each individual entity that is colliding. 
What's the purpose of `resetHitChecks` exactly? Wouldn't it be easier to trigger a separate event (e.g. `HitList(component, colliders)`) with the current colliding entities **every frame**? Is there a use-case I am missing, where resetting the notification about current colliding entities would come in handy?

**Comment by grozen** [comment]
Having collision events fire each frame even while a collision is underway (`HitOn` already returns all the colliders as part of the event data) is equivalent to calling `resetHitChecks` constantly (for example, at the end of a `HitOn` handler).

The only reason I implemented the events this way as part of #147 is that the notion of notifying about a collision only once was already in the code-base. If I remember correctly, I added `resetHitChecks` precisely to circumvent that behavior when desired.

**Comment by mucaho** [comment]
Ok, thank you for clarifying. I thought about it long and hard and think have come to a solution which offers the requested feature (collision events per entity), improves performance (in some cases) and streamlines the current implementation:
- First of all, change the implementation so that `Crafty.map.search` is called exactly once per frame. Current implementation of `onHit` and `checkHits` calls `hit` separately for each component resulting in multiple calls to `Crafty.map.search`. The code can be adapted to call `Crafty.map.search` exactly once and propagate the collisions to the collision handlers of `onHit` and `checkHits`. This was already discussed in #699, specifically [here](https://github.com/craftyjs/Crafty/pull/699#issuecomment-33630281) and [here](https://github.com/craftyjs/Crafty/pull/699#issuecomment-33695106).
- `onHit`: make it trigger `HitOn(component)`, `HitList(component, colliders)`, `HitOff(component)` 
  - the `HitList` event is triggered every frame, regardless if it's different from last frame (as determining if the hitList is different would require keeping track of colliding entities)
- `checkHits`: make it trigger `HitOn(component)`, `HitList(component, colliders)`, `HitListChange(component, colliders)`, `HitOff(component)`, `HitColliderOn(component, collider)`, `HitColliderOff(component, collider)`  
  - `HitOn`, `HitList` & `HitOff` are the same as in point above
  - additionally colliding entities are tracked for each component (e.g. using their ids) - `HitColliderOn` & `HitColliderOff` are fired appropriately
  - since we keep track of entity ids we can also determine if hitList of current frame is different from hitList of previous frame - fire `HitListChange` appropriately
- still not sure whether to fire multiple events about colliding entities that belong to multiple components (`HitList`, `HitListChange`, `HitColliderOn` & `HitColliderOff`) - remove the `component` event argument from these events?. If we include it, entities that have 2 or more components we are interested in will be contained in multiple events - user code might behave erroneously 

Implications of the proposed implementation:
- breaks backwards compatibility with `HitOn` (in current codebase it's fired with the component and hitList as the event argument) - in proposed implementation it's only fired with the component as the event argument
- `onHit` serves now as a simple convenience method used primarily for tracking collisions with components
- `checkHits` serves now as an advanced convenience method which also keeps track of collision with entities that have the desired component
- `onHit` performance increases iff user is interested in collisions with multiple components
- `checkHits` performance decreases
- eliminates the need for `resetHitChecks`, which just doesn't sit right with me (this is mostly subjective and we can change that ofc)

Thoughts? Terminology ok? Too complex? We can do something entirely different instead. but we sure cover many use-cases with this, don't we? :)

**Comment by starwed** [comment]
It's worth remembering that someone can always just use `.hit()` and analyze the results.  That way you know exactly how it works, and know exactly when it's called, and ultimately it isn't that much more work then hooking into these sorts of events.

Since I tend to think that's superior in most cases, that's invariably what I do, so I'm not sure I have much opinion here... I think it'd be ok to err on the side of it being simple, and only useful for some common use cases.  When people want more control, then they can use the underlying collision functions that this is built on.

**Comment by mucaho** [comment]
Closing this for now in favor of preserving compatibility & complexity and also promoting use of `hit`.
If there are additional requests we _could_ then provide the requested functionality with yet another sets of methods that co-exist with the current ones.
