### ISSUE TITLE
Drawing image via canvas: X,Y crop image instead of setting position

### ISSUE THREAD

**Issue by ponychicken** [craftyjs/Crafty#90]
Introduced in e4c9b56699e444aee643f25c621867d830588a37
@louisstow Why did you uncomment the `context.translate(e.pos._x, e.pos._y);` part?

**Comment by louisstow** [comment]
You mean comment or uncomment? I removed the canvasDraw method and merged it straight into the callback. Is there a JSFiddle of it drawing incorrectly? Also is it with the latest version or the dev version?

**Comment by ponychicken** [comment]
Yeah, meant comment. Here you go:
http://jsfiddle.net/3wHXJ/23/ <- Uncomment line 7 and observe the change. This part hasn't changed since 0.4.2

**Comment by louisstow** [comment]
Will have to revisit issue in next version
