### ISSUE TITLE
Nightly has different motion behaviour (jumps are higher)

### ISSUE THREAD

**Issue by letmaik** [craftyjs/Crafty#905]
I believe this is connected to @mucaho's improved motion system. Basically, using identical gravity etc. values for twoway, I get different jumping heights. Is that supposed to be? If so, it has to be mentioned in some migration/release notes later on. 

You can very easily verify this behaviour by cloning https://github.com/neothemachine/hungrymonkey and then in `index.html` commenting out one or the other crafty include (0.6.3 vs nightly) and then see how high the monkey is jumping (e.g. use your finger to capture the highest height...).

**Comment by mucaho** [comment]
see also [timing_gravity.html](https://github.com/craftyjs/demos/blob/master/devDemos/example_timing_gravity.html) and [timing_jump.html](https://github.com/craftyjs/demos/blob/master/devDemos/example_timing_jump.html).
[What has changed?](https://github.com/craftyjs/Crafty/pull/708#issuecomment-33746297), [Why is it different?](https://github.com/craftyjs/Crafty/pull/708#issuecomment-33967610), [Does it really affect outcome?](http://jsfiddle.net/fWQvj/)

**Comment by letmaik** [comment]
I see, so basically the old formula calculated things slightly wrong and this is corrected now, hence the differences. Still, has to be mentioned with the next release. You may close this issue or leave it as a reminder.

**Comment by mucaho** [comment]
~~Hmm, even so, these formulas shouldn't produce _that_ different results. I guess the biggest culprit is that jumping behaves differently now - it adds upwards velocity now, whereas before it manipulated the `y` directly.~~ Incorrect, net effect of old and new jump behavior should be same.
Yeah, there are couple of backward-incompatible changes we must not forget to address in change log.

**Comment by mucaho** [comment]
added to [0.7 release notes](https://github.com/craftyjs/Crafty/wiki/0.7.0-release-notes)
