### ISSUE TITLE
Custom collision hitbox ignored

### ISSUE THREAD

**Issue by nzifnab** [craftyjs/Crafty#932]
I added the `Collision` component to my `Player` component, and specified the hitbox to match the height of the sprite that I'm using using the `collision()` method. However, when I call the `onHit` method, it gets ran when the hitbox is _not_ intersecting the object in question - it seems to only care about the position of the entire entity.

I have a jsfiddle to demonstrate the issue:  http://jsfiddle.net/nzifnab/LvarggL1/3/

The blue box is the player entity itself, but the brownish box is what I see when I add the "SolidHitBox" component so I can see where the hitbox is.

If you use the arrow keys to move to the right, that entity box is the one that is hitting the block and stopping your movement -- not the hitbox. The player should be able to pass under the block without issue, but cannot.

Any idea what I'm doing wrong?

EDIT: I made the jsfiddle use fourway to make it easier to move around the block and see where the collision is occurring.

Edit2: I attempted to use the nightly build of crafty here: http://jsfiddle.net/nzifnab/LvarggL1/5/

This exhibits the same behavior where the hitbox is not working properly. I had to add a 'console.log' instead of stopping movement, because `this._movement` appears to have been changed/removed.

**Comment by mucaho** [comment]
Both entities need to have the `Collision` component, if you want to check for `SAT` collisions between them (collision checks between any two entities given that at least one entity has a custom hitbox). See [your updated example](http://jsfiddle.net/LvarggL1/7/).
There have been other users confused about this before (rightfully so), I will leave this issue open until we improve the documentation.

**Comment by nzifnab** [comment]
Hmm.  I'm not sure, but this seems like strange behavior. Since the `Player` is the one that is going to be colliding with things, shouldn't it just always respect the custom hitbox?

I haven't dug into the code enough to fully understand what you're doing there, and it may have to do with the fact that the custom box could be any kind of convex polygon (though in my use-case I'm just using rectangles)... but it seems like if there's a custom hitbox, you just use _that_ instead of the x/y/w/h of the entity when determining collsion with non-"Collision"-component objects, every single time.

In fact, if no custom hitbox is defined, it should just define a "custom" hitbox that is the size of the entity, so that the code simply always checks against the hitbox, and never checks against the entity's actual coordinates.

Is there a specific reason this isn't the case? It's a bit unintuitive to add "Collision" to objects that don't collide with anything else except the player.

**Comment by mucaho** [comment]
> Is there a specific reason _to not always respect the custom hitbox_ ?

Performance! You don't always need those expensive `SAT` checks, so it's up to you to decide when you want to sacrifice performance in favor of precision of collision checks. e.g you can set up a custom hitbox for expensive, precise `SAT` collisions with bullets, but also use the default hitbox (axis-aligned minimal bounding rectangle) for inexpensive, "good enough" `MBR` collisions with walls.

**Comment by nzifnab** [comment]
Hmm. Performance is a great reason... but in my case I still want the hitbox to be a rectangle, but the size of it _changes_.  It's easier for me to change the size of the custom hitbox and change out the sprite when the player, for instance, ducks, then it is for me to change the size of the entire entity, because then I have to modify the `y` coordinate as well, and the same-size-elements on my spritesheet won't line up as well, etc... (And I've had some problems using the `crop` method, but that's a question/issue for another thread)

I wonder if there's a middle ground where, if I define a custom hit box that is a rectangle, it could just _always_ use that hitbox and use the MBR collision method.

Of course, MBR is super simple to implement so I might just do it myself, but at that point I'm barely using Crafty for anything, since I've already had to swap out the `Fourway` for my own custom motion logic (although maybe the new `Motion` component would more suit my needs).

In any case, thanks for the response :)  I might go the route of modifying the size of the entity itself - there's no reason for me to take the SAT performance hit.

**Comment by mucaho** [comment]
> I wonder if there's a middle ground where, if I define a custom hit box that is a rectangle, it could just always use that hitbox and use the MBR collision method.

Sure, create another entity that has the exact dimensions as the desired hitbox. [Attach it to your player entity](http://craftyjs.com/api/2D.html#-attach) - it will move with the player entity. Don't add any `Collision` components. You can now listen for `MBR` collisions on this child entity and in response perform modifications on its `_parent` entity.
This is a common use-case so I have opened the issue #933. It will hopefully be added in future, thanks!

> since I've already had to swap out the Fourway for my own custom motion logic 

Creating your own components is even encouraged! :) If you made a component that could be of use to others, [feel free to share it](http://craftyjs.com/components/)! There are also other components on the net, that haven't yet been listed there.
If there's some generic / basic stuff missing in Crafty make sure to let us know.

**Comment by mucaho** [comment]
Documentation has been updated, I hope it's clear now when custom hitbox is used. On the contrary, feel free to reopen if there are further problems with it.

**Comment by Aliance** [comment]
I think I have the same issue.

I draw a 10x10 map. I have three components:
- a border tile 32x32 px at the edge of the map;
- a grass tile 32x32 px in free space;
- the character 50x50px.

The character is centered in the grass tiles by its bottom border. It moves by 32px (tween). And I try to make a collision with borders, but I want to hit only bottom 32x32 pixels of 50x50 character. I make a polygon (and it is success because i check it with `SolidHitBox`), but the `onHit` event fires on each character pixels :( That i'm doing wrong?

**Comment by Aliance** [comment]
**Update:** I think I solve my problem, but it's strange for me. I added the collision component to border (before this it was only at character). This helps me:

> - _SAT:_ Collision between any two convex polygons. Used when both colliding entities have the `Collision` component applied to them.

**Comment by Aliance** [comment]
@mucaho can you help me with stopping tween movement on collision hit? Live example: http://jsfiddle.net/Aliance/efL9k1nj/

**Comment by mucaho** [comment]
@Aliance 
You can [cancel your tween animation](http://craftyjs.com/api/Tween.html#-cancelTween) and then [correct the collision overlap](http://craftyjs.com/api/Collision.html#-hit).
In your code that would look like:

``` js
    stopMovement: function(hitDatas) {
        var hitData = hitDatas[0];
        console.log('[hit] %O', hitData);
        console.log('hero: %O', this);
        // stop tween/animation of hero movement
        this.cancelTween("x");
        this.cancelTween("y");
        // correct the collision overlap
        this.x -= hitData.overlap * hitData.normal.x;
        this.y -= hitData.overlap * hitData.normal.y;
    }
```

See the [new version of your jsfiddle](http://jsfiddle.net/efL9k1nj/1/)

**Comment by Aliance** [comment]
@mucaho 
Unfortunately, your example won't works as i expected - the hero character moves a few pixels on border.

Furthermore, second argument of the onHit method (`callback`) will calling each frame (as you [told](https://github.com/craftyjs/Crafty/blob/develop/src/spatial/collision.js#L327-L328)), but the third argument of the onHit method (`callbackOff`) [don't have any data passed](https://github.com/craftyjs/Crafty/blob/develop/src/spatial/collision.js#L344), may be this is omission? If it so, I can fix it in #949

**Comment by mucaho** [comment]
> the hero character moves a few pixels on border

Fix your numbers; e.g. use same movement amount as tile width & height. See [new, dirty example](http://jsfiddle.net/efL9k1nj/2/).
Try to avoid decimal numbers (e.g. `1.000000130`) as much as possible. You could `Math.round` the `this.x` and `this.y` after correcting the collision overlap.
There are also other ways to solve this, e.g. move in grid coordinates rather than x/y values. Check neighbors to see if they are walls before moving; don't allow movement into wall tiles.
By the way, possible bug: When you press any arrow key twice in quick succession, your player character will move only half a square.

> the onHit method (callbackOff) don't have any data passed

There is no data to pass, since there is no `hitData`, return value of `hit` function is `false`.

**Comment by Aliance** [comment]
As I see you decrease hero w/d to 30x30 pixels, but It's not okay, 'cause I need a character _higher_ than tile w/h. Look at this [new jsfiddle](http://jsfiddle.net/Aliance/efL9k1nj/4/), this suits me, except the thing, that moving to border cause 1 px padding. I think it's because firstly hero move to 1 px, then fires the hit event, and only then movement stops. Do i need to move hero 1px _back_?

I agree about decimal numbers, I'll try to find them :)

> There are also other ways to solve this, e.g. move in grid coordinates rather than x/y values.

Can you describe you idea in a few words?

> Check neighbors to see if they are walls before moving; don't allow movement into wall tiles.

Yes, I've already thinking about it, but all examples in the web about _crafty movement stop_ made with `this.x -= this._movements.x`. Ok, I'll try to edit my code in so, thanks. 

> By the way, possible bug: When you press any arrow key twice in quick succession, your player character will move only half a square.

Yes, I've already mentioned this bug too. I think the solve is to stop event triggers while prev. animation is not finished.

**Comment by mucaho** [comment]
I think you are still misscalculating things. [This example](http://jsfiddle.net/efL9k1nj/5/) works for me pixel-perfect.

>  but all examples in the web about crafty movement stop made with this.x -= this._movements.x

This is for arbitrary movement, but if you move a fixed distance, it's faster and arguably better to think in grid tiles, rather than arbitrary x/y position.

**Comment by Aliance** [comment]
Thanks for the example. Yes, It works for mee too. But I have a bit more complecated align. I'll try it with my coordinates and give you a feedback

**Comment by mucaho** [comment]
@Aliance 
[Here is an example](http://jsfiddle.net/efL9k1nj/6/) variant that checks neighbors for grid collisions. That should hopefully resolve the alignment issue, and should be more performant.
