### ISSUE TITLE
Has Fourway slowed down recently?

### ISSUE THREAD

**Issue by ashes999** [craftyjs/Crafty#945]
For one of my projects, I was using Crafty 0.6.3 with `fourway(8)`. This ran at a reasonable speed (cross an 800px-wide screen in a few seconds).

Recently, I switched to a local build, and I noticed that this slowed down, a lot (order of magnitude -- takes about 13 seconds to cross that distance).

Is this real (I'm not imagining things), intentional, or a regression?

**Comment by mucaho** [comment]
The develop build has undergone big changes recently in regards to speed parameters. It is now specified in pixels / second. You can read more about it in #923.
See also [conversion rates](https://github.com/craftyjs/Crafty/pull/923#issuecomment-120718636).

**Comment by ashes999** [comment]
This is a Good Thing. Thanks for clarifying.
