### ISSUE TITLE
viewport.follow overrides viewport.zoom

### ISSUE THREAD

**Issue by gopeter** [craftyjs/Crafty#953]
I'm trying to zoom into my game and follow the player, but it seems, that `viewport.follow` overrides `viewport.zoom` (tested with latest nightly build – apparently this issue was resolved here: #792, #934).

When defining `zoom` before `follow` nothing happens:

```
Crafty.viewport.zoom(5, player.x, player.y, 10);        
Crafty.viewport.follow(player, 0, 0);    
```

Fiddle: http://jsfiddle.net/drG26/7/

When defining `follow` before `zoom`, follow doesn't work anymore:

```
Crafty.viewport.zoom(5, player.x, player.y, 10);        
Crafty.viewport.follow(player, 0, 0);    
```

Fiddle: http://jsfiddle.net/drG26/8/

**Comment by mucaho** [comment]
If I'm not mistaken this works as expected: Multiple camera / viewport animations can not run at the same time, hence the previous animation is cancelled when activating a new one - here both `follow` and `zoom` are camera animations.
I tested both your cases, and in both cases the last animation specified is applied.

There are two workarounds for your particular issue:
- If you don't care about the "zooming in" animation, just set `Crafty.viewport.scale(zoomFactor)` and then `Crafty.viewport.follow(...)`
- If you care about the zooming animation, start it, wait for it to finish, and in response to that trigger the follow:

``` js
Crafty.one("CameraAnimationDone", function() {
    Crafty.viewport.follow(player);
});
Crafty.viewport.zoom(5, player.x, player.y, 2000);
```

[Here is the updated fiddle with the latter case](http://jsfiddle.net/drG26/10/).
You can also take a look at some more viewport animations in the [dev demo](https://github.com/craftyjs/demos/blob/master/devDemos/example_viewport_zoom.html).
If you would like multiple camera animations to work in tandem, we can open a feature request, which will hopefully be implemented in future.

EDIT:
In any case we should improve the documentation to better explain the current functionality.
Calling [`Crafty.viewport.zoom`](http://craftyjs.com/api/Crafty-viewport.html#Crafty-viewport-zoom) (or any other camera animation) with `0` animation time should probably instantly scale and center the viewport at the specified coordinates without interrupting the current camera animation.

**Comment by mucaho** [comment]
Ok, updated the documentation with 4a46cde430f2533546a887479bcdbeeabdb5fdf3, that should hopefully clear up things now.

**Comment by gopeter** [comment]
Great, thank you very much! Documentation is now much clearer :)
