### ISSUE TITLE
Changing scenes with viewport cause DOM appendings

### ISSUE THREAD

**Issue by Aliance** [craftyjs/Crafty#956]
Look at [this small demo](http://jsfiddle.net/Aliance/dxzLxt17/3/). There are:
- black movable character;
- green grass, on which the character moves;
- red buildings, visiting which will cause another scene enter (scene with bigger viewport)

On this another scene there is only one button, clicking on it = returning again to main game scene. Try to do this manipulations a few times. Then inspect DOM, you can find the `container` element (this is my main stage element), and a couple of divs inside it. Is it okay if entering a new scene will cause a new div to be append to main `container`?

May be I do something wrong?

**Comment by starwed** [comment]
> Is it okay if entering a new scene will cause a new div to be append to main container?

In the standard use case, you don't need to call `viewport.init()` directly.  It's handled by the original call to `Crafty.init()`.  This is what was creating the extra divs.

I think the viewport docs should definitely mention this issue, though!
