### ISSUE TITLE
Deleting empty event handlers?

### ISSUE THREAD

**Issue by 200sc** [craftyjs/Crafty#957]
I've been working with a team on an isometric Crafty game for a few months now, and we've got a map of ~36000 tiles. These tiles all have the following binding on initialization:

``` javascript
this.one('EnterFrame', function() {
        this.base.z = this._z;
});
```

. . . because they don't have their z value when they are initialized, but I digress.

With base Crafty, this is incredibly slow. It's slow because when Crafty goes to check on all of the EnterFrame callbacks, [here](https://github.com/craftyjs/Crafty/blob/develop/src/core/core.js#L1635): 

``` javascript
trigger: function (event, data) {
        // (To learn how the handlers object works, see inline comment at Crafty.bind)
        var hdl = handlers[event] || (handlers[event] = {}),
            h, i, l, callbacks, context;
        //loop over every object bound
        for (h in hdl) {

            // Check whether h needs to be processed
            if (!hdl.hasOwnProperty(h)) continue;
            callbacks = hdl[h];
            if (!callbacks || callbacks.length === 0) continue; // <----- HERE
```

It loops through every single tile every single frame, continuing each time. This takes our game's framerate down to ~10 fps, whereas if we modify this line to be this:

``` javascript
if (!callbacks || callbacks.length === 0) {
    delete handlers[event][h];
    continue;
}
```

We get up to the default max of 50 fps no problem. Instead of looping through all of these entities, who have no intention of binding to EnterFrame again, every single frame, it loops through them once and then runs with no issues (so far).

Is there a reason Crafty doesn't remove handlers after they are unbound, or doesn't remove empty handlers? It seems like it could drastically improve performance if you have a lot of entities that run .one bindings. Then again, I don't know if there are any major consequences to doing it.

**Comment by starwed** [comment]
> Is there a reason Crafty doesn't remove handlers after they are unbound, or doesn't remove empty handlers? It seems like it could drastically improve performance if you have a lot of entities that run .one bindings. Then again, I don't know if there are any major consequences to doing it.

It sounds like a pretty reasonable change to me.  I'll whip up a quick patch and open a PR.  (Events work a little differently in the develop branch, but it should still be a pretty straight forward change.)

**Comment by starwed** [comment]
(As an aside, there's actually an event triggered when you set or change the `z` property: the dubiously named "reorder".  I don't think it's documented, and it should definitely be renamed so that the capitalization is consistent.)

**Comment by 200sc** [comment]
Great! I'll look into 'reorder', too.
