### ISSUE TITLE
How can I use web fonts / google fonts?

### ISSUE THREAD

**Issue by ashes999** [craftyjs/Crafty#968]
Hi,

I want to use Google Fonts, which (from the forums) looks like it's supported, but I'm not clear on how to go about adding it.

Here's [a quick JSFiddle that works](https://jsfiddle.net/rhr595mr/). Sort of.

It loads two fonts from Google (Indie Flower and Scheherazade for English and Arabic respectively). When you load the fiddle in Chrome (Windows and Ubuntu), you don't see the fonts apply until you resize the windows. If you hit "Run" about ten times, you should see the fonts apply approximately twice.

This is also probably specific to JSFiddle, but I had to import the fonts through JS, which is ugly:

```
WebFontConfig = {
    google: { families: [ 'Scheherazade::arabic,latin', 'Indie+Flower::latin' ] }
  };
  (function() {
    var wf = document.createElement('script');
    wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
      '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
    wf.type = 'text/javascript';
    wf.async = 'true';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(wf, s);
  })();
```

My specific questions:

1) Is this the right way to include web fonts (minus how I loaded them)?
2) Is there a work-around for the refresh issue?

**Comment by mucaho** [comment]
According to a [stackoverflow answer](http://stackoverflow.com/a/7289880/3041008) the fonts are loaded asynchronously. You can add the `active` callback to the `WebFontConfig` object, which will be called once the fonts are loaded. This is good point in time to setup the font entity. See the [updated jsfiddle](https://jsfiddle.net/rhr595mr/1/) - seems to work for me on Win64 Firefox and Chrome.

``` js
WebFontConfig = {
    google: { families: [ 'Scheherazade::arabic,latin', 'Indie+Flower::latin' ] },
    /* code to execute once all font families are loaded */
    active: function() {
      Crafty.scene("main");
    }
};
```

**Comment by ashes999** [comment]
2) That's awesome, thanks.
1) So is this the right/best/recommended way to use google fonts?

**Comment by mucaho** [comment]
Probably :). I just learned about it, so don't know much about it, but you may find additional information on [typekit/webfontloader](https://github.com/typekit/webfontloader).

**Comment by ashes999** [comment]
Great, thanks. (It would be wonderful if you could document this somewhere.)

**Comment by mucaho** [comment]
Added to [Wiki FAQ](https://github.com/craftyjs/Crafty/wiki/Crafty-FAQ-%28draft%29#how-can-i-use-webfonts) - you could explain it in more detail there if you'd like to; and as an [example](https://github.com/craftyjs/demos/blob/master/devDemos/example_webfont.html).

**Comment by ashes999** [comment]
That's excellent, thanks.
