### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by CubixSystem** [craftyjs/Crafty#971]
New version is awesome! Thanks all for great work.
Please update [npm](https://www.npmjs.com/package/craftyjs) package.

**Comment by starwed** [comment]
Paging @kevinsimper :)

**Comment by rhys-vdw** [comment]
:+1:  Also could there be a link to the npm page in the README?

**Comment by kevinsimper** [comment]
It's done, https://www.npmjs.com/package/craftyjs

Is there anyone I can add to that repository? The deployment is basicly just `npm publish`, so it is very easy once you have access :+1:

**Comment by mucaho** [comment]
Great, thanks! @starwed do you have an account there, so kevin can add you there? If you want to add me, I use the same nick there.

**Comment by kevinsimper** [comment]
@mucaho You have been added :+1:

**Comment by mucaho** [comment]
@kevinsimper Thanks! :+1:
