### ISSUE TITLE
CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated.

### ISSUE THREAD

**Issue by Sebring** [craftyjs/Crafty#980]
**Heads up for deprecated function**

Using Chrome 46 I got this warning in the console:

'CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated. Please use 'CanvasRenderingContext2D.imageSmoothingEnabled'

**Comment by starwed** [comment]
For compatibility we set both the regular and vendor-prefixed properties.  (As in the example on [this page](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled)).

To remove it, we'd need to know whether any currently popular browsers still rely on it -- I'd guess mobile probably lags behind desktop here.

**Comment by Sebring** [comment]
Ah yes of course, same as all those css-prefixes one needs, I should have figured.
Closing issue, thanks for reply,
