### ISSUE TITLE
Upgrade travis infrastructure

### ISSUE THREAD

**Issue by starwed** [craftyjs/Crafty#982]
A notice from Travis CI: 

> This job ran on our legacy infrastructure. Please read [our docs on how to upgrade](https://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade)

We should investigate this and, presumably, upgrade to their new infrastructure.

**Comment by starwed** [comment]
Actually, looks like @mucaho  already took care of adding `sudo: false` to the .travis.ytml file.  :)

Is there anything about the new infrastructure we can take advantage of that requires further changes?  Or should I close this issue?

**Comment by mucaho** [comment]
Nah, that's it as far as I know :+1:
