### ISSUE TITLE
Release minor version bump 0.7.1

### ISSUE THREAD

**Issue by starwed** [craftyjs/Crafty#983]
I just cherry-picked a couple important fixes into the testing branch, and pushed it as version 0.7.1-rc.

The two fixes were
- @mucaho's changes to the release process that should help fix bower
- @matthijsgroen changes that properly unregister WebGL entities when they're destroyed

Are there any other fixes that should definitely be merged in?

**Comment by mucaho** [comment]
The versions and dist files in the testing branch look good to me. However, there is a `src/version.js` file which is probably a remnant from the old src hierarchy, which should probably be removed.

**Comment by mucaho** [comment]
Voting to include #989 in that release, which currently prevents linking online snippets with Crafty v0.7.

**Comment by starwed** [comment]
I added a [release candidate for 0.7.1](https://github.com/craftyjs/Crafty/releases).

**Comment by mucaho** [comment]
Thanks, I tested both bower and jsfiddle - both displayed correct version using the new build artifacts :+1:

**Comment by starwed** [comment]
@mucaho Should I go ahead and release this, or are there some additional tests we should run for bower?

**Comment by mucaho** [comment]
Ran another simple demo game using **bower**, seems to work fine. Remember that only the browser version of crafty is shipped via bower. If you use bower programmatically from node, you won't get Crafty's server version (but you probably use npm on the server anyway):
- Install crafty via bower

``` sh
bower init
bower install crafty#0.7.1-rc2 --save
bower list -p
```
- Use crafty via bower
  `<script src="bower_components/crafty/dist/crafty.js"></script>`

[Jsfiddle](http://jsfiddle.net/k5q1sovr/) seems to work fine too. However, I don't get any error messages for using the storage functionality. Could you try using the `embed` feature of that jsfiddle and see if any errors pop-up?

Other than that, looks good for release in those aspects.

**Comment by starwed** [comment]
As long as there are no regressions, and it fixes a couple of errors, lets just go ahead and do the release?

**Comment by starwed** [comment]
(I pushed the release, just need to update the website now.)

**Comment by starwed** [comment]
Updated the site, so closing this now.  (AFAIK no docs needed updating, so I didn't update api.json)

**Comment by mucaho** [comment]
JSFiddle works with the new version, however the new release didn't go that well for bower.  
`dist/crafty.js` and `dist/crafty-min.js` are missing from the repository, so the 0.7.1 release is broken again for bower :(. If I remember correctly we didn't gitignore those files so that they would be pushed to GitHub with next `grunt release`.

**Comment by starwed** [comment]
> JSFiddle works with the new version, however the new release didn't go that well for bower.
> 
> dist/crafty.js and dist/crafty-min.js are missing from the repository, so the 0.7.1 release is broken again for bower :(. If I remember correctly we didn't gitignore those files so that they would be pushed to GitHub with next grunt release.

@mucaho  I think what happened is that I tagged the wrong commit through the UI -- those files _are_ in the release branch, but it looks like when I created the 0.7.1 release it tagged the develop branch instead.  :|

**Comment by starwed** [comment]
I might have fixed the tagging issue -- I deleted the tag, which seemed to put the release back into the "DRAFT" state on github.  Then I pointed it at the correct branch and published it again.

It's possible that bower will have cached some info and this will screw things up.

**Comment by mucaho** [comment]
[JSFiddle](http://jsfiddle.net/k5q1sovr/3/) is still working.
Bower worked also! Anyone that already downloaded `0.7.1` will have to do `bower cache clean` though, to be able to install fresh version (I had to do it too).
Nice, we can treat this issue as properly closed now :)

**Comment by mucaho** [comment]
Well, we forgot node :) I published the new version.
Seems to work for both the server version

``` bash
npm install craftyjs
node
>> var Crafty = require('craftyjs')();
>> Crafty.getVersion(); //prints 0.7.1
```

and client version

``` html
<html>
  <head>
  </head>
  <body>
    <script src="https://wzrd.in/bundle/craftyjs@latest"></script>
    <script>
    var Crafty = require("craftyjs");
    console.log(Crafty.getVersion()); // prints 0.7.1
    Crafty.init();
    Crafty.background('rgb(127,127,127)');
    </script>
  </body>
</html>
```
