### ISSUE TITLE
Keyframe system

### ISSUE THREAD

**Issue by mpetrovic** [craftyjs/Crafty#99]
Crafty has systems for animating a sprite, and simple tweens, but these still require a lot of manual labor to do anything more complex than that. I'm looking to create something a little more robust to facilitate more complex animations.

The plan:
Each entity will maintain a list of animations.
Each animation is given a string to reference it, and an array of keyframes. 
Each keyframe consists of a frame number, what sprite reel to play, and any attributes that should be tweened. 

Every frame, it checks to see if a keyframe is defined. If it is, it plays the reel, and builds the tween call. If an attribute doesn't exist, it's ignored.

Thoughts?

**Comment by louisstow** [comment]
I like it. Got a proposed interface we can implement?

**Comment by mpetrovic** [comment]
not sure how to write one of these, so I'm going to wing it.

function keyframe(string animationName, object keyframe, ...):
takes any number of keyframe objects and adds them to the array of keys. The array is keyed off their frame number.

function play(string animationName, number keyframe)
plays the animation, optionally from the given keyframe
if it's paused and no string is given, it continues playing

function pause() 
pauses the animation

keyframe object: {
frame: number
sprite: 'reel',
x: number,
so on: and so forth,
interpolation: to do later
}

**Comment by louisstow** [comment]
So it should combine tweening and sprite animation? Looks good. Will write
my proposed api tonight
On 17/06/2011 1:02 PM, "mpetrovic" <
reply@reply.github.com>
wrote:

**Comment by mpetrovic** [comment]
It should be one stop for any kind of animation we have. We only have Sprite and Tween at the moment, but if any others should arise, they would be added to Keyframe as well.

**Comment by louisstow** [comment]
I think i'll end up just merging them into one. Here's my proposed API:

```
var anim = Crafty.animation("FadeOut", 10).keyframe(5, {alpha: 0.5, frame: [0,0]}).keyframe(10, {alpha: 1.0});
ent.addAnimation(anim).playAnimation("FadeOut");
```

**Comment by mpetrovic** [comment]
What is the 2nd argument on .animation() for? If it's for the length, that seems unnecessary. The animation would only last as long as there are keyframes for.

Also, how about linking animations to sprite maps themselves? Just to reduce the amount of object management developers have to do. 

<pre>Crafty.animation("sprite", "animationName")</pre>


Then every entity that uses "sprite" will have the animation already. It'll make things easier for dealing sprites that are used a lot but temporarily, like monsters or level elements.

**Comment by louisstow** [comment]
The 2nd argument would be duration. As in how long to play the animation for. Although if the keyframes are just referring to the amount of enterframe calls then it's not necessary.

There could be different sprite maps though.

**Comment by mpetrovic** [comment]
The keyframe should refer to the time since the animation started. The animation is over when we hit the last keyframe.

I see animations as being fairly sprite specific. Even if they could be used on multiple sprites, I still think animation storage should be at component level and not the entity.

**Comment by louisstow** [comment]
Not time, amount of frames since started.

I see what you mean but the current implementation wouldn't work without prior knowledge of every sprite component in the sprite map.

Say I have two sprites called `mysprite` and `mysprite2`.

   Crafty.animation("mysprite", "animation");

That means any entity with `mysprite` can use the animation but what about `mysprite2`?

**Comment by mpetrovic** [comment]
Ok, I've soured on the idea. Not for that reason, but to keep components and data separate. Animations should probably be data, rather than specific to any component. 

I still don't think people are going to be reusing animations between sprites. Different sprites should be different things in the game. If a set of sprites are different states of the same thing, they should be animations rather than separate sprite components that are switched between. Maybe that's just my time with Flash talking, though.

**Comment by mpetrovic** [comment]
So I've been thinking about this, and I still don't like this 'one size fits all' approach to animations. I still think they're going to be unique to entities, rather than something that gets dropped in place on a number of them quickly. 

The most common use-case I see is cutscenes, and any game someone wants to make that's more complex graphically than an NES game. In both cases, animation reuse is not going to be useful. 

My primary argument against keeping animations in the global Crafty namespace is most keyframe animations will be one-offs. Use it once, and it becomes irrelevant. There'll be some keyframed animations that can be reused, but for the most part, no. That animations object would get huge, filled with no longer needed animations. 
My secondary argument is label reuse. If I want 5 entities to have the same type of animation but with different timing (because their sprite reels are different lengths), I don't want to have 5 unique names for that animation.

**Comment by louisstow** [comment]
That is a good point. So have the animation for an entity. I can still see the need for having the same animation for multiple entities. I guess in that situation you should have a component to add the animation on each of the entities.

**Comment by louisstow** [comment]
Implemented with an editor
