### ISSUE TITLE
mirror image

### ISSUE THREAD

**Issue by proyb6** [craftyjs/Crafty#993]
using .flip("Y"), it flipped the image from the center but I would need to flip an image as a reflection in the water, setting origin("bottom") didn't help.

**Comment by 200sc** [comment]
Modify the reflection's y value.

https://jsfiddle.net/8dftkzq6/3/

**Comment by matthijsgroen** [comment]
@proyb6 Is this issue still relevant?

**Comment by starwed** [comment]
I don't think there's any action that needs to be taken here, so closing.

As always, feel free to reopen if you feel there's a bugfix or enhancement that would help.
