### ISSUE TITLE
Disappear on the next frame

### ISSUE THREAD

**Issue by proyb6** [craftyjs/Crafty#996]
Tested on Electron in Mac OS X
https://groups.google.com/forum/#!topic/craftyjs/XJGMo17c96w

I found a confusing behaviour that need a critical fix by this week.

**Comment by 200sc** [comment]
What is e.x? Can you demonstrate this bug in a code snippet that we can run?

**Comment by proyb6** [comment]
Here, create a test red rectangle shape in Crafty component and then mouse wheel up or down one step, it will disappear.

If the aaa is replace with a hardcode number e.g. aaa=100 then it will simple stay visible and never disappear. Just why would e.x would be different from a number?

```
Crafty.c("drawTest", {
init: function(){/*Nothing in init scope*/},
sdraw: function(e) {
var ctx1=document.createElement("canvas");
ctx1.width=e.arrayx[e.arrayx.length-1]-e.x;
var ctx = ctx1.getContext("2d");
ctx.rect(0,0,500,1000);
ctx.fillStyle="red";
ctx.fill();

var aaa=e.x
Crafty.e("2D, Canvas, Image, nn").attr({x: aaa, y: 0, w: ctx1.width, h: ctx1.height})
.image(ctx1.toDataURL());
}

for(var t in getItem)
Crafty.e("drawTest").sdraw({
    x:  getItem[t].x,
    y:  getItem[t].y,
    vx: arrayx
});

//Mouse Wheel
//Move notes left or right, direction up +1, down -1
Crafty.bind("MouseWheelScroll", function(evt) {
Crafty("nn").each(function() {
    this.x+=(evt.direction*100)
});
}else if((Crafty("sig").get(0)._x<0)&&evt.direction==1){
Crafty("nn").each(function() {
    this.x+=(evt.direction*100)
});
});
```

**Comment by proyb6** [comment]
Upon using DOM in replace of Canvas
Crafty.e("2D, DOM, Image, nn")

The image will stay visible even with aaa=e.x;
But the image will move and stuck at x,y 0,0 position after wheel up or down.

Why Canvas is different from DOM in this case?

**Comment by 200sc** [comment]
So I can't run that code, because I don't have a definition for sig or nn (which might not be anything else) or getItem or arrayx. Can you give us a snippet that has everything defined? What I suspect is happening is that for one of your each in getItem, x is NaN. Can you console.log(x) when you assign it?

**Comment by proyb6** [comment]
"sig" and "nn" is just a name for mouse wheel for Crafty("") selector only it doesn't have any components or entities.

getItem is a javascript object getitem={}
arrayx=[0,100,200,300]

Extensively testing for the last few days, I didn't come across anything with NaN. I believe it could be a rendering behaviour issue.

The console.log of x will appear with a number e.g. 100

**Comment by proyb6** [comment]
If it's possible, would you mind guide me with your own example with these features?

Create a red box with Canvas and covert to Crafty Image and add to stage with the named "nn"
Wheel up or down the red box using Crafty selector to move the box in horizontal position.

**Comment by proyb6** [comment]
Argh, it appear to be caught by sloppy value type, all I could simply cast Number(aaa) for mouse wheel with proper calculation. Before that, the number was appear to append "100-100-100-100"

Got to be more safe with types.

```
Crafty.e("2D, Canvas, Image, rednn").attr({
      x: Number(aaa),
      y: 550,
      w: ctx1.width,
      h: ctx1.height
    }).image(ctx1.toDataURL());
```
