### ISSUE TITLE
Pausing the game

### ISSUE THREAD

**Issue by matthijsgroen** [craftyjs/Crafty#997]
I would like to see some improvements on how to pause the game:

Right now, there is a Crafty.pause() and Crafty.unpause()
They however are not pausing the game, but pausing the entire engine.

For now I bind stuff to a 'GameLoop' event instead of 'EnterFrame' and have a simple inbetween mechanic

`Crafty.bind('EnterFrame', function(fd) { if (Game.paused) return; Crafty.trigger('GameLoop', fd); });`

This way I can pause the gameplay, and keep the engine running (to display a pause menu, etc)

For Tweens, this works nicely because they can be paused and unpaused.
However, some Crafty components can not be stopped this way:
- Delay
- Particles

Would it be nice to have `pause()` and `unpause()` methods for these as well?

( I will try to submit pull requests for these if these are sane improvements )

**Comment by starwed** [comment]
I think it would make sense for "Pause" to just affect "EnterFrame", or at least to have a method that does that.  The current pause could perhaps be named suspend?

(I haven't looked, but it's possible you could workaround this in the current engine by setting the timestep to a fixed amount of 0?)

**Comment by starwed** [comment]
I guess the case where you want rendering suspended is when someone has switched away from the browser window.  I think that's behind the current design of `pause()`.

However, since we run the game loop after animationFrameReady, my understanding is that this shouldn't really be much of a concern -- modern browsers won't trigger that when the window isn't actually visible.

**Comment by matthijsgroen** [comment]
I do not want to suspend rendering. I want to pause the game, not the engine. Imagine playing a game, pressing pause, the gameplay pauses and a menu shows with options like:
- Resume
- Settings
- Exit

And this menu is rendered by Crafty as well, has perhaps its own tweens, delays, and particles.

**Comment by 200sc** [comment]
So like a scene change that pauses the scene you leave instead of destroying that scene's elements?

It seems like that'd be the way to group entities so you were only pausing the ones that were a part of the base game. It'd also be useful, for example, for things like RPGs if you wanted to cut from a world map to a battle without having to store and load the map's state?

**Comment by matthijsgroen** [comment]
I'm saying that I want to be in control in which elements to pause. I know what elements are forming the game play, but at the moment delays and particles are not pausible (which I want to add later tonight).

The Crafty.pause() pauses the whole engine which is fine. Since Crafty cannot decide which components are gameplay and which not (and shouldn't). each developer decides that in their own engine powered by Crafty.

**Comment by 200sc** [comment]
So you're advocating for a specific label like "GameEntity" and a specific Crafty function like "Crafty.pauseGame()" that would cease the activity of all "GameEntity"s? 

I feel like this could be accomplished better with some type of nested context switching. It avoids having a magic "GameEntity" word that a developer would have to have all their entities require, and it would have the benefit of nesting the functionality. For example, say you had a pause menu which itself was animated and one of the options in the pause menu modified how the menu was animated, through another menu. We can't separately pause more than one group of entities with this implementation.

**Comment by 200sc** [comment]
Or maybe a Crafty.pause(entityName), that would pause anything with that required? You could also go somewhere in-between and have a 'Pausable' component which you could then entity.definePauseGroup("Game"); on, which would be better for memory bloat.

**Comment by matthijsgroen** [comment]
No I especially do not want 'magic' behaviour. That would be against the openess of Crafty. I like how crafty does not dictate things and gives freedom to the developer to implement their own engine how they see fit. The only thing right now to pause the gameplay for me and keep the rest of the engine running normally is that I cannot Pause delays and particles. I am already capable of pausing tweens.

**Comment by 200sc** [comment]
So what about the last suggestion I made? If you don't like that, can you come up with the function you want to call? Or are you saying you don't want anything to be done, because you're going to fix the delays and particles?

**Comment by matthijsgroen** [comment]
I have a lot of own animation components for bezierpaths etc. If Crafty is going to dictate how to pause, I have to conform my code to how crafty wants it. It loses developer freedom. If a component has a Tween, a Delay and Particles I see some conflicting pausing behaviour there. I would be helped more with a `.pauseTweens()` which is already there `.pauseDelays()` and `.pauseParticles()`.

This way we give full control to the devs, without templating how a developer should build their game.
